### ISSUE TITLE
unable to use jupyter configs

### ISSUE THREAD

**Issue by Bamieh** [jupyterhub/jupyterhub#1071]
Hello,

I am trying to use a custom `pre_save_hook` via jupyter config file, however i am unable to get jupyterhub to detect it.
i have the config file saved at the user level and on global level aswell. i tried saving it as `ipython_notebook_config.py` in accordance to the documentation, and as `jupyter_notebook_config.py` according to jupyter docs, all my attempts are failing.

```
COPY src/ipython_notebook_config.py $HOME/.ipython/profile_default/ipython_notebook_config.py
COPY src/ipython_notebook_config.py /.ipython/profile_default/ipython_notebook_config.py
```

thanks

**Comment by willingc** [comment]
Hi @Bamieh,

What documentation are you using that is recommending this information since it is outdated? Jupyter does not have the concept of profiles since v4.0. This [reference](https://jupyter.readthedocs.io/en/latest/migrating.html#finding-the-location-of-important-files) explains the file structure when using Jupyter.

It is best to use `jupyter_notebook_config.py` for `pre_save_hook` as described in [this section](https://jupyter-notebook.readthedocs.io/en/latest/extending/savehooks.html).

**Comment by Bamieh** [comment]
@willingc thanks for the fast reply! i got the "outdated" information from [here](https://jupyterhub.readthedocs.io/en/latest/getting-started.html#spawners-and-single-user-notebook-servers)

>Since the single-user server extends the notebook server application, it still loads configuration from the ipython_notebook_config.py config file. Each user may have one of these files in $HOME/.ipython/profile_default/. IPython also supports loading system-wide config files from /etc/ipython/, which is the place to put configuration that you want to affect all of your users.

i was able to use my configs using the "--configs" command when calling my spawner, however, i am unable to know where to put the config file for auto read? i have it inside `$HOME/.ipython/profile_default/jupyter_notebook_config.py` or at root as specified by jupyter, yet no luck.
