### ISSUE TITLE
GPU Support out of the box?

### ISSUE THREAD

**Issue by angrylandmammal** [jupyterhub/jupyterhub#1120]
Hi there!

I'm really struggling with setting up Jupyterhub for my team, and also being able to leverage my new shiny GPU!

I read through the entirety of this article: https://zonca.github.io/2016/10/dockerspawner-cuda.html

However, and sadly, it's outdated as I'm trying to use Ubuntu 16.04 (server), CUDA 8.0+. I'm working on it and have tiny bits of progress but the documentation here:

https://github.com/jupyterhub/jupyterhub-deploy-docker
https://jupyterhub.readthedocs.io/en/latest/
and
https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/getting-started.md

is fragmented and makes it difficult to understand how to set this up properly for team use, and to have Jupyterhub utilize your GPU.

Happy to share what I've come up with so far, if anyone else could point me to some clear-cut instructions I'd be grateful!

Best,
HJ

**Comment by willingc** [comment]
Hi @hayjoss,

> I read through the entirety of this article: https://zonca.github.io/2016/10/dockerspawner-cuda.html

This is the best resource for GPU that I have seen. @zonca, if you have a free moment, what if any differences would a more recent Ubuntu or CUDA have on this deployment.

> Happy to share what I've come up with so far

PRs for documentation are welcomed :-) Feel free to copy it into this issue too.

**Comment by johnhaley81** [comment]
👋 

I've been trying to get this running as well but I run into lots of issues around the nvidia docker volume for the cuda lib files being mounted. When starting a `jupyterhub-user` container I get errors saying that it can't create the user volumes since they already exist.

So I deleted the old user volumes and then launched it again with `driver=nvidia-docker` and then when it was trying to create the user volumes it got `bad volume format` and wasn't able to start the container. It can't create the user volumes with that driver for whatever reason.

But when I take out the driver it tries to recreate the `nvidia_driver_384.90` volume instead of just mounting the volume that's already there. Which it shouldn't need to do since it's already there. Is there a way to just use the driver to mount this one volume and `local` to mount the user volumes?

@angrylandmammal were you able to get this to work at all?

**Comment by adler-j** [comment]
Also working hard on getting this to work but to no/marginal success. Has anyone progressed on with this?

**Comment by bccomm** [comment]
In my case, the relevant configuration lines in jupyterhub_config.py were:

``` python
c.JupyterHub.spawner_class = 'dockerspawner.SystemUserSpawner'
c.SystemUserSpawner.image = 'local/our_custom_nbimage'
c.SystemUserSpawner.links = { 'jupyterhub' : 'jupyterhub' }  # Probably unnecessary

c.SystemUserSpawner.use_internal_ip = True
c.SystemUserSpawner.network_name = 'jhnet'

c.SystemUserSpawner.volumes = { "nvidia_driver_384.81":"/usr/local/nvidia",
                                "/share":"/share"
}
c.SystemUserSpawner.extra_host_config = {
    "network_mode": "jhnet",
    "devices": [ "/dev/nvidia-uvm:/dev/nvidia-uvm:mrw",
                 "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools:mrw",
                 "/dev/nvidia-modeset:/dev/nvidia-modeset:mrw",
                 "/dev/nvidia0:/dev/nvidia0:mrw",
                 "/dev/nvidia1:/dev/nvidia1:mrw",
                 "/dev/nvidiactl:/dev/nvidiactl:mrw"
    ]
}
```
Note that the "devices" format accepted by docker-py has changed since @zonica 's article: http://docker-py.readthedocs.io/en/stable/containers.html?highlight=devices

I'm using the older nvidia container runtime, not nvidia-docker2. I didn't have to specify the volume driver, and there didn't seem to be a problem mixing in volumes and bind mounts alongside the nvidia_driver. I *did* have several iterations of mistyping the volume name for the driver, so make sure that it is correct (make sure you aren't swapping underscores and periods, for example...). Look at `docker volume ls` to see what nvidia-docker is already exposing. If you don't see anything whose driver is "nvidia-docker", make sure the nvidia-docker service didn't fail to start. It sometimes does so silently.

There was also an issue with the Dockerspawner package, though I can't remember what it was right now. I worked around that by simply installing it directly from github inside the Jupyterhub container.

My setup with Systemuserspawner also triggered this bug, since I'm also using LDAP authentication: https://github.com/moby/moby/issues/5419 . Maybe not relevant here, but the workaround is just to patch /usr/local/bin/start.sh (notebook container) to modify /etc/passwd directly instead of running usermod.

**Comment by willingc** [comment]
@minrk I'm going to close this as it's not something that is frequently asked. I'm not sure that we have any concrete guidance on it for documentation.
