### ISSUE TITLE
Question: which spawner can work on Windows?

### ISSUE THREAD

**Issue by rs2** [jupyterhub/jupyterhub#1158]
**Disclaimer** It's a question, not an issue.

While `ldapauthenticator` can work on Windows, I could not find a suitable non-container spawner. Is there a way to make JupyterHub work on Windows at all?

**Comment by willingc** [comment]
Hi @rs2,

Let me make sure that I understand your question correctly.

Can JupyterHub run on Windows? JupyterHub can not be deployed using a Windows server https://github.com/jupyterhub/jupyterhub/blob/master/setup.py#L25. In particular, the Hub may not run on Windows, and we do not support spawners running on Windows.

A user running Windows can access a JupyterHub provided single user notebook server since this user would be accessing a JupyterHub URL from their browser.

I recommend looking at [Zero to JupyterHub documentation](https://zero-to-jupyterhub.readthedocs.io) if you wish to use a cloud provider to deploy JupyterHub.

**Comment by fenderrex** [comment]
Windows 10 offers a ubuntu terminal in it's dev tools, I don't know how it works with GPU passthrough for machine learning, it would be nice to use my oculus gaming pc serving my computer science club with jupyterhub. Maybe ill try proxmox again... or set up a reboot when i leave I think grub may have some tools. but renting a PC is not pratical when i have a $500 GPU and only one use for it...

**Comment by fenderrex** [comment]
Could anaconda provide enough of a isolated eviorment? Anaconda provides multiple python environment management, if I can manage a anacondahub could It manage individual jbooks safely?

**Comment by G2Jose** [comment]
Looking at this open issue https://github.com/Microsoft/WSL/issues/829, it looks like windows does not (yet) have GPU support on WSL

**Comment by ociule** [comment]
FWIW, using [jupyterhub-winauthenticator](https://github.com/ni/jupyterhub-winauthenticator) and [jupyterhub-winlocalprocessspawner](https://github.com/ni/jupyterhub-winlocalprocessspawner) works fine on Windows, with jupyterhub master.
