### ISSUE TITLE
Any way to give a different hub IP to singleuser servers?

### ISSUE THREAD

**Issue by DeepHorizons** [jupyterhub/jupyterhub#1163]
My current setup uses Jupyterhub 0.7.2 in a docker container, using a modified version of the batchspawner to start singleuser servers on a cluster. `JupyterHub.hub_ip` is set to `0.0.0.0`, but it binds to `127.0.0.1`.  This address is given to the singleuser server under the `--hub-api-url` argument. This isn't OK since the singleuser servers are running on different machines than the hub. I can't set the `hub_ip` to the public address because it is running in a docker container and can't bind to that address.

Is there any way from the config to tell the singleuser servers that it should connect to a different IP than the `hub_ip`? I'm currently doing a janky hack in the spawner to inject the correct address that obviously isn't the correct way to do it.

**Comment by minrk** [comment]
Setting `hub_ip` does set the bind ip. If you set this to 0.0.0.0, 127.0.0.1 is used for connecting unless overridden somewhere. Some Spawners (e.g. DockerSpawner) set a separate `hub_connect_ip`, but this should be handled at the Hub level so that different spawners don't need to reimplement this. I'll work on it.
