### ISSUE TITLE
Decouple Handlers from Hub

### ISSUE THREAD

**Issue by Carreau** [jupyterhub/jupyterhub#1270]
I was trying to write #1263 (HubDispatcher), not on top of Hub, but one of the tight coupling here is the request handler has a `hub` property and make a few uses of it. (`self.hub.base_url`, `self.hub.base_url`,`self.hub.cookie_name`, `self._set_user_cookie(user, self.hub.server`). 

As authenticator do inherit their handler from `BaseHandler`, then they are coupled to the existence of a `Hub` thing. 

If we could transform the need for a hub to separate parameters that would make reusing handler in another context – like when you do not have a Hub –  Easier.

**Comment by yuvipanda** [comment]
A more general question is why do we have a hub object in the database? Am confused about what use it is meant for...

**Comment by minrk** [comment]
> A more general question is why do we have a hub object in the database?

All info about the Hub is removed from the db in master. This lives only in config now. Hub is a simple Python object.

As for decoupling, since these are properties the absence of `.hub` should only be noticed if it's used, so I'm not sure. The hub object encapsulates information about the Hub, so it's probably good to have in any Handler that needs it, and Authenticator handlers need that information for cookies, redirects, etc.. I'm not sure what the benefit would be of requiring several `hub_` settings over requiring one `hub` setting.

What about adding:

    from jupyterhub.objects import Hub
    hub = jupyterhub.objects.Hub.from_url('http://1.2.3.4:8081/hub/')
 
Would that be sufficient?

Setting cookies requires full access to the database for the User object, which seems a higher bar than a small wrapper around url and cookie info.

**Comment by Carreau** [comment]
> What about adding:
> 
> from jupyterhub.objects import Hub
> hub = jupyterhub.objects.Hub.from_url('http://1.2.3.4:8081/hub/')
> Would that be sufficient?

It probably would, I'll try. I mostly get thrown off by various level of indirection.

**Comment by manics** [comment]
Is this still relevant to the current JupyterHub?

**Comment by manics** [comment]
No response, closing
