### ISSUE TITLE
JupyterHub master not reliably checking if user servers are running on startup

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1313]
How to reproduce:

1. Start JupyterHub (with KubeSpawner)
2. Spawn a user
3. Stop JupyterHub
4. Start JupyterHub again

Expected:

1. On startup, JupyterHub looks at all users to see if they are still running, and updates its own state

What happens:

```
[D 2017-08-05 10:29:30.533 JupyterHub app:1215] test not running, status is 0.
```

despite the fact that the pod is running.

**Comment by yuvipanda** [comment]
It looks like `spawner.server` is never actually set.

**Comment by yuvipanda** [comment]
Possibly a missing `db.commit()` somwhere?

**Comment by minrk** [comment]
I typed out a comment yesterday but apparently forgot to post it.

It definitely could be a missing `db.commit()`, but i doubt it because I was able to test and confirm that resuming containers is working with local spawners.I think this might be an issue in KubeSpawner?

If `spawner.server` is never set, it shouldn't get to the `status is 0` message. This event should only occur if `spawner.server` is set, indicating from db state that a server was running, but `Spawner.poll()` returns 0.

This could be a problem in KubeSpawner.load_state or KubeSpawner.poll. My initial guess is that it's related to the reflector, which is perhaps not aware of the pods when it resumes in this way.

**Comment by minrk** [comment]
Hm, now I was able to run this with KubeSpawner via the helm-chart (jupyterhub-0.8 branch, local minikube), and again confirmed that it's resuming correctly, so it's at least not *always* failing.

Here are a couple more questions:

1. Had the user's pod finished starting when you restarted JupyterHub, or did you restart JupyterHub mid-spawn?

**Comment by yuvipanda** [comment]
I can't reproduce this anymore, so going to close.
