### ISSUE TITLE
Using Jupyterhub 0.7.2 API

### ISSUE THREAD

**Issue by surya4ecap** [jupyterhub/jupyterhub#1360]
Hi guys,

I'm planning to use jupyterhub api to see the user list, login and start server for user too. 
I try and follow these tutorial:
1. http://jupyterhub.readthedocs.io/en/0.7.2/_static/rest-api/index.html
2. http://jupyterhub.readthedocs.io/en/latest/reference/rest.html
3. https://github.com/jupyterhub/jupyterhub-tutorial/blob/master/docs/rest-api.ipynb

It always get 403 Forbidden. When i tried a simple curl for jupyterhub version it works:
`curl -i -X GET http://127.0.0.1:8081/hub/api`
Kindly give me some advice for this. Thank you.

Best regards

**Comment by willingc** [comment]
When you access the api, you will need to authenticate with a token. This section in the documentation explains how to authenticate: http://jupyterhub.readthedocs.io/en/latest/reference/rest.html#make-an-api-request
By authenticating successfully, you will be able to access the api without 403 errors.

The API request for version does not require authentication which is why it worked.

**Comment by surya4ecap** [comment]
Thanks for the response @willingc 
I found out about api token issue. After you create API token for **specific user**, make sure put the user as **'admin'**. For example add below value on jupyterhub_config.py:

- `# Admin Jupyter`
- `c.Authenticator.admin_users = {'administrator'}`

I can running the api now. Anyway, is there any API for login to jupyterhub? For example passing username and password to API.

Kindly give an advice. Thanks

**Comment by harschware** [comment]
There's an interesting gist (https://gist.github.com/minrk/3045784d928a98c445ed997cb6b55c62) in issue #1261 that might interest you
