### ISSUE TITLE
If the singleuser server running is a Jupyter notebook server & doesn't have a version header, fail explicitly

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1367]
Currently, if you have a JupyterHub 0.8 server but a Jupyterhub <0.8 singleuser server, it'll end up in a redirect loop. This is IMO unideal, since a lot of people will run into it. We should fail with an explicit error that has an useful error message.

**Comment by minrk** [comment]
#1368 doesn't go as far as to fail pre-emptively, which I think is a bit at odds of our long-term goals of reducing sensitivity to Hub version. Instead, it throws an informative, lengthy (user-facing!) error containing both the single-user server and Hub versions during the actual failure likely to be caused by this, which is a redirect loop caused by failure to implement OAuth in the case of the 0.7-0.8 transition.
