### ISSUE TITLE
User not informed their server didn't start

### ISSUE THREAD

**Issue by DeepHorizons** [jupyterhub/jupyterhub#1389]
With my current setup of Jupyterhub, sometimes the singleuser server will fail to start. One thing I have noticed however is that while the hub will see that the server did not start, the error will not be propagated to the user, and the user will wait the until the timeout period passes.

The two cases I am currently seeing is
1. The server fails before the spawners `start()` method returns. In this case the hub logs an error, raises an assertion exception in `start()`, and then just kinda does nothing.
2. The spawners`start()` returns, but the server fails while Jupyterhub waits for it. Here the only log is `Spawner failed to start`.

In both cases I can see the hub return a `500` for `/hub/user/<user>` but then it continues returning `200` after that.

My questions are:
1. Is there a specific exception [type] that should be raised in the `start()` method to tell the user there was a problem and they should try again?
2. Is there any specific reason the hub isn't telling the user the server didn't start during the http_timeout period?

**Comment by minrk** [comment]
> The server fails before the spawners start() method returns. In this case the hub logs an error, raises an assertion exception in start(), and then just kinda does nothing.

In this case, the request that triggered the spawn will throw 500 if it's still waiting. If the request that triggered the spawn is closed (e.g. if the spawn was slow), then nobody is waiting for it, so there is no HTTP error to raise.

> The spawners `start()` returns, but the server fails while Jupyterhub waits for it. Here the only log is Spawner failed to start.

If this happens, there is likely an error logged by the single-user server when it fails to start. What Spawner are you using? What do you see in the logs for the single-user server? If this is the default spawner, it will be in the same terminal output as the Hub. If it's DockerSpawner, then it will be in the logs of the `jupyter-<username>` container.


> Is there a specific exception [type] that should be raised in the start() method to tell the user there was a problem and they should try again?

No, any error should propagate to the user just fine, assuming the request is still waiting for it. I think the question is whether a user request is still waiting on that response, which I think we can address elsewhere.

> Is there any specific reason the hub isn't telling the user the server didn't start during the http_timeout period?

There are three basic cases:

1. error during start: raises 500 immediately with `Failed to start your server. Please contact admin.`. The full error is logged in jupyterhub.
2. `start()` finishes, but server has exited before becoming responsive (raises 500 with `Spawner failed to start` message.
3. `start()` finishes and server starts up, but fails to become responsive at the expected URL within a timeout. This will raise 500 with 

If the slow_spawn_timeout is hit before the error occurs, the request that triggered the spawn will get a pending status ( status: 200 and spawn_pending page for the human-facing URLs, status 202 for API endpoints). If this happens, any error raised in the Spawner is not hooked up to any HTTP request and the error doesn't propagate to the user because the user isn't waiting for the request that triggered the spawn anymore. We should be able to improve this by holding on to the Future for the spawn and waiting on that when we render the pending page. This should make it more likely

In the future, we might want to save a "last spawn failed" state and show that failure in certain cases. However, the implicit spawn triggered by visiting `/user/:name` makes it complicated to decide exactly what should be done when.

**Comment by DeepHorizons** [comment]
Aha! I was unaware of the slow_spawn_timeout and its effects. That sounds like whats happening, most spawns take longer than the default 10 seconds. Is there a way to set the slow_spawn_timeout? It's not in the hub config. Also, whats the purpose of slow_spawn_timeout?

To answer your other questions, I'm using the BatchSpawner (SlurmSpawner in particular). I have an idea why the severs are not starting (something on my end) but I wanted to let users know when it didn't work so they could try again [sooner]. I was just really confused when the hub clearly knew that the server didn't start but didn't notify the user.

Thanks a bunch by the way, and great work!

**Comment by minrk** [comment]
slow_spawn_timeout has to be a value small enough that HTTP requests won't timeout (e.g. less than 15-30 seconds, depending on what proxies/load balancers might be participating). It's a cutoff for showing the "please wait..." page, not a timeout for actual failure. That timeout is `Spawner.start_timeout`, and can safely be a very long time (60s by default, could be minutes for BatchSpawner). However the effect is that failure *reporting* is not as good once this has happened. #1393 should fix that.
