### ISSUE TITLE
Allow multiple simultaneous containers for a single user.

### ISSUE THREAD

**Issue by athornton** [jupyterhub/jupyterhub#1390]
Opening an issue as requested by Yuvi Panda.

My use-case is this: I have an options form that allows me to choose one of several container images, which represent different tags of our software stack.  Each spawned container contains image name, user name, and tag.  

Currently a single user can have one image running at a time.  What I would like is a mechanism for a user to have multiple containers (each with a unique name) running simultaneously.  This would make it easier for users to look for regressions between builds.

For reasons related to our stack construction, it's infeasible, or at least currently quite difficult, to allow multiple versions inside a single container, hence my request.

**Comment by minrk** [comment]
We should have most of what's needed for this with the named servers feature new in 0.8. The missing piece is the UI allowing you to show an options form to users that spawns named servers (and the UI for listing/shutting down named servers once they have started).

We could potentially bless a field in the options form that, if present, set the server name. That might not be the best option, though, because it confuses things a bit. UI for named servers is something that I want to have in place for 0.9.

If you want it to work with 0.8, though, you could do it with a Service. To create a named server with 0.8, you would:

1. set `c.JupyterHub.allow_named_servers = True`
2. create a HubOAuthenticated service that serves a form
3. on submission of the form, spawn a server with a request like:

```
POST /hub/api/:user/server/:server_name
BODY: {...}
```

where the body is the dict to be used as `user_options`, json-serialized. If you have already put together an implementation with `options_form`, this would be the value you are already returning from `options_from_form`.

**Comment by Analect** [comment]
The reference to the API call above should read: `POST /hub/api/:user/servers/:server_name`  i.e. it was missing the plural form of server.  This tripped me up for a while.

**Comment by cedric05** [comment]
i want to work on it.

**Comment by d4n1elchen** [comment]
Any update for this?

**Comment by manics** [comment]
Closing, this is the documentation for named servers: https://jupyterhub.readthedocs.io/en/1.1.0/reference/config-user-env.html#named-servers
