### ISSUE TITLE
how do you 'Enable HTTPS for JupyterHub'?

### ISSUE THREAD

**Issue by batchku** [jupyterhub/jupyterhub#1391]
Hello
I have setup JupyterHub on a Ubuntu 16.04 server, and I'm not able to login remotely, due to this warning:

```
Warning: JupyterHub seems to be served over an unsecured HTTP connection. We strongly recommend enabling HTTPS for JupyterHub.
```

How do I go about enabling HTTPS?

![image](https://user-images.githubusercontent.com/518356/30006707-962ad7bc-90cc-11e7-9c00-aaab03dfa6a1.png)

**Comment by minrk** [comment]
The warning should not affect your ability to login. It is just a text recommendation to use HTTPS, because without HTTPS username and password are sent across the network unencrypted. You can enable HTTPS by creating an SSL key and certificate and passing them to jupyterhub [in configuration](http://jupyterhub.readthedocs.io/en/latest/getting-started/security-basics.html#using-an-ssl-certificate).

**Comment by tanglade22** [comment]
Hello, i have been creating a JupyerHub on a public cloud project on OVH using this tutorial : https://tljh.jupyter.org/en/latest/install/ovh.html
I would also like to enable a secure https connection on this website. Anyone has a clue ?

**Comment by Sireeshabotta** [comment]
did anyone how to enable HTTPS for the Jupyterhub?
