### ISSUE TITLE
Logout w/ github ID not working

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/jupyterhub#1394]
We're here at neurohackweek with @arokem and it was reported that the "logout" button doesn't "do" anything on our setup. We're using github authentication. Here's a general recap:

## Expected behavior
On this page:
![image](https://user-images.githubusercontent.com/1839645/30033992-7593501a-9153-11e7-9297-e15030a78286.png)

Clicking "log out" would send you to a page to log back in with github

## Actual behavior

Clicking "log out" refreshes the page but doesn't actually log you out (it just dumps you back the same page as the screenshot above)

**Comment by arokem** [comment]
I've noticed this, but chalked it up to the fact that I am still logged
into Github.

It does shut down the pod that is running that instance.

**Comment by Carreau** [comment]
Actually I believe it does log you out, just as soon as you come to the page, you are immediately logged-in again, because you are still connected to your GitHub account. The initial "blocking" step is GitHub actually requesting "do you allow Hub to access your identity".  It will probably be the same with any OAuth provider.

What would be the use case for staying logged out ?

**Comment by minrk** [comment]
I think this is #967, fixed by #969. In 0.7, logging out sent you to the login URL, which would start the OAuth login process and log you right back in again via a series of redirects. 0.8 fixes this by sending you to a page with a link instead.

**Comment by choldgraf** [comment]
cool - I am gonna close this issue and will re-open if we run into the problem again in the future
