### ISSUE TITLE
Option to disable user

### ISSUE THREAD

**Issue by sven-mayer** [jupyterhub/jupyterhub#1432]
Hi,

as far as I know, there is no way to disable a user without deleting them. Is that correct?

If so, is it just me or would this feature make sense for other jupyterhub admins as well?

**Comment by chavellacinema160** [comment]
Im not  good at this .im having trouble.alot going on.it seems im by myself .where are the real americans.greed has tooken over peoples minds .i wasnt meaning github clients sorry.

**Comment by willingc** [comment]
@SamyStyle Sorry about the spam above.

@minrk Any objection to adding the above spam sender to the blocked user list? And/or removing the spam message?

**Comment by minrk** [comment]
@willingc not at all. Feel free to block & remove.

**Comment by minrk** [comment]
@SamyStyle the reason is largely that deleting and disabling as far as JupyterHub is concerned are approximately the same thing. Deleting a user is only removing an entry from the database, not deleting files on disk or deleting system users. So I view the add/remove functionality of the admin page to be the same as adding/removing from the whitelist. What sort of behavior would you like to have that you don't get from deleting users via this mechanism?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Thanks! 🌻

**Comment by titansmc** [comment]
If I delete a user, the next time the user logs in via LDAP it will be recreated, so ideally we would have a way of blocking those users.

**Comment by minrk** [comment]
You can block users with:

```python
c.JupyterHub.blocked_users = { "username", }
```

In JupyterHub 5, you can manage users via the API such that new auth will _not_ re-add users with:

```python
c.Authenticator.allow_all = False # don't allow login via LDAP to create new Hub users
c.Authenticator.allow_existing_users = True # adding/removing users via admin ui is sticky
```

**Comment by titansmc** [comment]
oh, thanks a lot.
