### ISSUE TITLE
Edit whitelist in web interface OR option to confirm new users first

### ISSUE THREAD

**Issue by sven-mayer** [jupyterhub/jupyterhub#1433]
Hi,

We are using jupyterhub with a number of students, and whenever the new term starts it's a big mess to put all github accounts of the students into the whitelist. 

I propose either having a web form to edit the whitelist on the fly. Or and I actually think the second option is way cooler, an option to confirm new users before pam creates new accounts on the system.

**Comment by athornton** [comment]
If your token has read:org scope it should be able to see private membership too (I haven't tested; our use case at the moment is all public).

I'm going to open an issue at some point: there is a misleading error message that happens when you've been invited to a whitelisted org but haven't yet accepted, and try to log in while you're in that state.  It's fairly far down my priority queue though.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's a suggested workaround (using groups). If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
