### ISSUE TITLE
Redirect to login url on mismatched oauth state

### ISSUE THREAD

**Issue by ryanlovett** [jupyterhub/jupyterhub#1438]
A few of our users have reported seeing the error "oauth state does not match" from auth.py#L782. One reported that the error was cleared when "erased all the caches" in her browser. Should the hub redirect to the login URL instead of displaying the error?

helm chart version v0.5.0-4f7cb71.

**Comment by minrk** [comment]
I dug through the logs, and this is caused by multiple simultaneous OAuth logins:

1. oauth 1 sets state cookie and begins redirect
2. oauth 2 sets *different* state cookie and begins redirect
3. oauth 1 completes, compares (and clears) state cookie (2) with state arg (1), **fails with 403**
4. oauth 2 completes, compares state cookie (clear) with state arg (1), **fails with 403**

I think this is in part caused by the fact that APIHandlers are triggering the login redirect (jupyter/notebook#2853), which in turn sets an oauth state cookie. An open and active page that has lost authentication will set the oauth state cookie a few times with different values due to each failed API request triggering the same event.

We can solve it on the Hub side by using a random cookie name in case of collisions (#1439)

**Comment by HelderGualberto** [comment]
This error occured for me when I used Auth0 authentication. 

It happened due to an invalid subdomain certification in Auth0. So try to do not use a not certified self signed certification. You can try validating it using letsencrypt.

**Comment by akhilputhiry** [comment]
@ryanlovett @minrk @yuvipanda I am facing this issue when i launch multiple notebooks simultaneously.

**Comment by rodriguez-facundo** [comment]
Same here. It works in Safari and fails on Chrome when launching multiple notebooks

**Comment by SonakshiGrover** [comment]
@maluhoss  were you able to solve this? I am running into the same issue.
