### ISSUE TITLE
X11 forward through JupyterHub server

### ISSUE THREAD

**Issue by nabriis** [jupyterhub/jupyterhub#1489]
Hi,

I want to enable X11 forwarding through a JupyterHub server. Is this even possible?

To goal is to be able to run 3D graphical stuff through an X11 forward in a jupyter notebook.
Right now this is used in some of the R notebooks we have. It works fine on a local install of jupyter notebooks, but we get
"
Warning message in rgl.init(initValue, onlyNULL):
“RGL: unable to open X11 display”Warning message:
“'rgl_init' failed, running with rgl.useNULL = TRUE”
"
on the server running through JupyterHub

Best regards

**Comment by mariusvniekerk** [comment]
An easier option might be to use some webgl libraries if those exist for R

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻

**Comment by raivivek** [comment]
Hi, I face the exact same issue. Would be nice to have a solution.

**Comment by slavistan** [comment]
Hi :-) Is there anything new concerning this issue? I'm looking to host a workshop using jupyterhub. The participants will work mainly in notebooks, but occasionally there'll be the need to display a browser window (the graphical application in question), as we'll be doing automated UI testing and it sure would be nice to see the moving parts move once in a while.

Does somebody have any idea or an approach, vague or concrete, hacky or sophisticated? I volunteer to try everything out.

Also, may I kindly suggest to reopen this issue since the problem hasn't been solved yet.
