### ISSUE TITLE
Username in JupyterHub header [customizing templates]

### ISSUE THREAD

**Issue by scbarton** [jupyterhub/jupyterhub#1502]
As a supervisor I log into a lot of different JupyterHub accounts, and I'd like to be able to see the username of the current login. I wrote a short iPython extension below, which adds the username to the kernel_logo_widget element. It works with the %load_ext magic, but I'm not sure how to make it work when automatically loaded.

I've tried adding the following to ipython_kernel_config.py:

    c.IPKernelApp.extensions = [ 'NameInHeader' ]

with the idea that the extension would load with the kernel. This loads the extension, but maybe too soon because the header is not changed.  Is there a better way to accomplish what I'm trying to do?

```
# NameInHeader.py

def load_ipython_extension(ipython):
    
    import re, os
    from IPython.display import display, Javascript

    uname= os.getenv('USER')

    s='''var s = document.getElementById('kernel_logo_widget').innerHTML;
         var news= '<span style=\\'color:#919191\\'>_user_ </span>' + s;
         document.getElementById('kernel_logo_widget').innerHTML=news;
    '''

    func=re.compile('_user_')
    s=func.sub(uname, s)

    display(Javascript(s))
```

**Comment by minrk** [comment]
A custom template is probably what is desired here, and while technically possible now, customizing templates needs some work to be really useful (#1481).

**Comment by Siecje** [comment]
I am trying to add the current user to the notebook list page and the notebook page itself.

I can't modify the notebook template here because {{ user }} is not available.
https://github.com/jupyter/notebook/blob/master/notebook/templates/page.html

JupyterHub could add the current user as a literal somewhere but I'm not sure where do to that.
https://github.com/jupyterhub/jupyterhub/blob/c9db504a49deb57d3494ce331fc6c904cf0a9e57/jupyterhub/singleuser.py#L141

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
