### ISSUE TITLE
A user can delete other's notebook from UI

### ISSUE THREAD

**Issue by dclong** [jupyterhub/jupyterhub#1514]
I found that a user can delete other's notebook from JupyterLab UI. 

JupyterHub Version: 0.8.0
JupyterLab Version: 0.28.11
Notebook permission: 644
Spawer: LocalProcessSpawer
Authticator: PAMAuthenticator

The whole environment is set up in Docker and a directory on the host machine is mounted to the jupyter notebook directory in Docker so that users can collaborate. However, notebooks (with permission 644) created by the admin user (has the same id and name as the user on the host that started the docker service) can be deleted by other users by right clicking and choose delete. BTW, every user in the docker are in the sudo group.

**Comment by minrk** [comment]
Can you provide more information? What Spawner and Authenticator are you using? How does the user access the other users' notebooks?

If it is a shared filesystem with real users, this is governed entirely by the filesystem permissions.

**Comment by minrk** [comment]
> BTW, every user in the docker are in the sudo group.

This means that all users have permission to read, write, and delete all files in the container, but they will need to `sudo` to do it. This includes the configuration and credentials of jupyterhub itself, as well as all other users.

Permission to delete files is not governed by the file permissions, but by the permissions of the *directory* containing the file. For instance, in this script I create a directory owned by me and a file in that directory owned by root. I cannot *edit* the file, but I can delete it because I own the directory.

```bash
$ mkdir dir
$ sudo sh -c "echo 'stuff' > dir/file"
$ echo 'xx' > dir/file
Permission denied
$ rm -vf dir/file
dir/file
```

Is the directory owned by admin, or only the file?

**Comment by dclong** [comment]
@minrk Good to know. I missunderstood permission to delete files.
