### ISSUE TITLE
SparkR and jupyterhub

### ISSUE THREAD

**Issue by hani1814** [jupyterhub/jupyterhub#1528]
Hi,

I am using jupyterhub (v 0.8.0) with python for some time and it works fine. 

I have installed Microsoft OpenR, verified that sparkR works from the command line

I configured apache_toree_sparkr to work with SparkR. All works well except that text output is visible on the screen

e.g. a=2
a

but graphics are not displayed on the screen (used a similar python lib in pyspark and it is fine

library(ggplot2)
ggplot(data=iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) + geom_point(size=3)

I have also tried which did not work
myPlot <- ggplot(data=iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) + geom_point(size=3)
print(myPlot)

If I send the output to PDF as follows then the PDF is created in my home directory

myPlot <- ggplot(data=iris, aes(x=Sepal.Length, y=Sepal.Width, color=Species)) + geom_point(size=3)
pdf("~/myPlot.pdf")
print(myPlot)
dev.off()

Any idea why graphics are not displaying in the notebook? I have no issues with python

thank you

**Comment by willingc** [comment]
@hani1814 Thanks for the question. Sorry for the delayed response.

Since this is related to notebook functionality, it would better to ask on the [Jupyter notebook repo](https://github.com/jupyter/notebook) and/or the Jupyter mailing list. If you are still seeing this issue now, please open an issue on the notebook repo and link to this issue. I'm going to close it here on the JupyterHub repo.
