### ISSUE TITLE
raise 403 when a user access a resource from another user (Question).

### ISSUE THREAD

**Issue by andrelu** [jupyterhub/jupyterhub#1535]
Hello everyone!

Let me explain my problem. In my company, users share notebooks through a NFS system and they like do share the link of the notebooks via emails and messaging, but now they are getting 403.

On jupyterhub 0.8.x when a user access another url from another user a 403 error is raised. I know this is the expected behavior but there is a way to not do this? Just redirect to login page?

Thank you all.

**Comment by minrk** [comment]
*If* the users are all running from the same root directory (e.g. `notebook_dir = '/home'`), then there is a special URL `/user-redirect/` that will redirect a user to their own server after logging in.

So instead of sharing:

    # assuming `/home/` here and thus `/user/alice/alice/` is `/home/alice/...`
    https://jupyterhub.horse/user/alice/alice/notebooks/foo.ipynb

share

    https://jupyterhub.horse/user-redirect/alice/notebooks/foo.ipynb

Then any user who opens that URL will get redirected to `/home/alice/foo.pynb` *on their own server*.

**Comment by dclong** [comment]
@minrk Is there a button somewhere to get the URL using `user-redirect`? If not, we should really considering add a "Share" button somewhere to make this easier for users.

**Comment by minrk** [comment]
Unfortunately, JupyterHub cannot know if such a link would work, because it cannot know the relationship of the file paths in one user's directory point to the same file in other user's directories. A specific deployment like this could do that, but it's not true in general that users share access to files.

So it should be a fine thing to add such a button in your deployment via an nbextension, but I don't think it's appropriate to add a link that will usually not work to the default behavior.
