### ISSUE TITLE
User specific options_form

### ISSUE THREAD

**Issue by TimKreuzer** [jupyterhub/jupyterhub#1542]
Hi,
I'm trying to build up an user-specific options_form in my Spawner. In a self-written custom OAuthenticator the OAuthenticator receives a list when a user has logged in. This list contains information, which has to be used in the Spawners options_form. 
For example:
User A logs in: 
OAuthenticator.uid_list = {'A': ['aaa', 'bbb', 'ccc'] }

User B logs in:
OAuthenticator.uid_list = {'A': ['aaa', 'bbb', 'ccc'], 'B': ['xxx', 'yyy'] }

Before starting a notebook server i want to give each user the opportunity to chose one uid in a DropDown Menu. But of course user A should only be able to chose 'aaa', 'bbb' or 'ccc'.

I found a SpawnHandler in jupyterhub/handlers/pages.py and edited the get() function:

```
if user.spawner.options_form:  
  suser = str(user)[6:-14]  
  self.log.debug("Try to find {} in authenticated users.".format(suser))  
  if suser in user.authenticator.availableUIDs:
    self.log.debug("{} found. Add {} to Dropdown Menu.".format(suser, user.authenticator.availableUIDs[suser]))
    insert = ""
    for i in range(0, len(user.authenticator.availableUIDs[suser])):  
      insert += "<option value=\""+user.authenticator.availableUIDs[suser][i]+"\">"+user.authenticator.availableUIDs[suser][i]+"</option>"
    user.spawner.options_form = user.spawner.options_form.replace("<!--   $INSERTVALUESHERE -->", insert)  
    self.finish(self._render_form())  
```

It is working right now, but is there a smoother way? 

I'm using JupyterHub 0.8.0 , a self-written [Authenticator](https://gitlab.version.fz-juelich.de/jupyterhub-unicore/unity-authenticator/) (in development, not finished) and a self-written [Spawner](https://gitlab.version.fz-juelich.de/jupyterhub-unicore/unicore-spawner/) (same, very specific for my use-case). 

I already tried the pre_spawn_hook function, but I need a function which is called before the options_form is read. 

I attached a screenshot of my options_form.

Thank you very much

![screenshot from 2017-11-16 16-41-21](https://user-images.githubusercontent.com/26455850/32900177-2582df9a-caed-11e7-80e3-5d5d9c108357.png)

**Comment by minrk** [comment]
The Spawner object has access to the user it is building the options_form for as `self.user`. If you make `options_form` a property that constructs the value based on the user, that should work.

**Comment by TimKreuzer** [comment]
Thank you very much. Works perfectly.

**Comment by emmanuel** [comment]
I've been attempting to use the `Authenticator.auth_state` interface to accomplish what is described in this issue. Given the challenges I spelled out on a related issue on the wrapspawner (here: https://github.com/jupyterhub/wrapspawner/issues/7), I believe that `auth_state` won't work for this purpose (because `User.get_auth_state` is async/returns a Future, whereas `options_form` is synchronous). 

Based on the discussion here, it sounds like I can simply add a property to my Authenticator, instead of using `auth_state`. I don't understand enough of the Authenticator lifecycle, though, so I'm confused/concerned. If I rely on a value set on the in-memory instance of the authenticator (that originates from the token returned from the OAuth provider, as in the example above), will that value always be present when a user logs in and is presented with the Spawner `options_form`?

@TimKreuzer have you seen any issues with your `OAuthenticator.uid_list` not being set when the `options_form` is rendered?

**Comment by emmanuel** [comment]
Ahh, OK. After inspecting your Authenticator and Spawner, @TimKreuzer, it appears that you've (roughly) implemented an in-memory version of the `auth_state` interface (e.g., storing state about logged in users here: https://gitlab.version.fz-juelich.de/jupyterhub-unicore/unity-authenticator/blob/master/unityoauthenticator/unity.py#L93), and prompt the user to log in again if that state is missing (here: https://gitlab.version.fz-juelich.de/jupyterhub-unicore/unicore-spawner/blob/master/unicorespawner/unicorespawner.py#L278).

**Comment by emmanuel** [comment]
FWIW, @TimKreuzer #1684 (not yet merged or released) adds support for `Spawner.options_form` returning a callable which can return a future and therefore can utilize state from `User.get_auth_state` which would enable using durable authentication state from your Authenticator in your spawner, in lieu of the current in-memory based approach visible in your linked code.

**Comment by TimKreuzer** [comment]
Thank you for the information. I will add it to my code in the future. Right now it's working fine for me and we're working on other features to improve. 
I really appreciate that you tagged me in this and that you sent me your solution for this problem.
Best regards

**Comment by emmanuel** [comment]
@TimKreuzer – my pleasure. Thank you for publishing your code (esp. the Authenticator and Spawner) and linking to it here; I learned a good deal from inspecting it. 

Best, Emmanuel.
