### ISSUE TITLE
Prometheus metrics to add to JupyterHub

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#1585]
We started adding prometheus metrics to JupyterHub in #1581.

More metrics to add:

1. Server poll times (Histogram)
2. Currently active servers (Gauge)
3. Proxy route poll times (Histogram)
4. Hub startup time (Histogram)
5. Server stop times (Histogram)
6. Proxy route deletion times (Histogram)
7. Server aliveness latency (Histogram) (time from server starting to being reachable)
8. Total users count (Gauge)

This should be a great start, and I think we can / should make a quick release after this.

**Comment by yuvipanda** [comment]
Clearly did not work on these that week :) Would be great if someone can pick this one up!

**Comment by yuvipanda** [comment]
I want to get some of this into 0.9, will set aside some time for it!

**Comment by vpavlin** [comment]
Hi, this is super interesting issue:). We are running JupyterHub on OpenShift and we'd love to get some metrics from it - as we already use Prometheus to scrape OpenShift, Spark and other services, this would be an awesome addition.

Is there any update on this?

**Comment by rkdarst** [comment]
More suggestions:
- Server age (histogram)
- Server time since last activity (histogram)
- proxy time since last activity (histogram) (likely not that important since the interesting data is in the services)
- services active (gauge)
- servers active (gauge) (maybe already done?)

For KubeSpawner, my own script provides some count of pods by profile, which is computed based on pod name.  This may be hard to do in a general way, but ideally could be adapted to other spawners, too (profilespawner).

The histograms are a bit difficult since they are instantaneous counts, while prometheus histograms are usually envisioned as a bunch of accumulating gauges over time as far as I can tell.  Would be good for someone to study what the proper technique here is.

**Comment by dtaniwaki** [comment]
I decided to use [statsd-exporter](https://github.com/prometheus/statsd_exporter) because those values are not implemented for Prometheus although I know it's not ideal. I'm happy to implement this feature if no one is handling it.

**Comment by clkao** [comment]
@dtaniwaki did you manage to start adding metrics?

**Comment by dtaniwaki** [comment]
@clkao I haven’t started it yet because I didn’t have much time and statsd-exporter works fine.

**Comment by clkao** [comment]
perhaps we should start with identifying desired stats, as some of them are already implemented with statsd, and some are implemented as prometheus in binderhub. Then we can see how best to unify them.

**Comment by rajat404** [comment]
Hi!
I wanted to pick this issue. It seems that many of the metrics mentioned above have been picked since the creation of this issue:
```
- Server poll times (Histogram)
- Total users count (Gauge)
- Currently active servers (Gauge)
- Server stop times (Histogram)
```

Are the remaining metrics needed?
```
- Proxy route poll times (Histogram)
- Hub startup time (Histogram)
- Proxy route deletion times (Histogram)
- Server aliveness latency (Histogram) (time from server starting to being reachable)
```
Are any other metrics needed? (Please mention which ones)

I've recently started working with Prometheus itself, so would like to work on this issue.
Please let me know, if I can help 🙏 

cc: @yuvipanda @willingc

**Comment by GeorgianaElena** [comment]
Hi @rajat404! The metrics remaining in @yuvipanda's original list would be great additions :tulip:. Feel free to reach out if there are any questions :rocket: .

**Comment by rajat404** [comment]
Thanks! 😄 
Should I make a single PR with all the metrics, or would you prefer separate PR for each one?

**Comment by GeorgianaElena** [comment]
I believe it would make sense to have each metric in its own PR. Smaller PRs usually make the review process easier.

**Comment by rajat404** [comment]
Are any other metrics mentioned in this issue need to be added?
If not, may I suggest closing this issue, and track request for new metrics in separate/new issues

**Comment by BobCashStory** [comment]
@rajat404 not sure that in it, does we have the runtime of kernels ?
exemple usage will be with jupyter Entreprise gateway, i would like to see by user how much they use they kernels sine they are detached from they single user.

**Comment by agp8x** [comment]
A common prefix for all Jupyterhub metrics would be awesome. Most exporters for Prometheus follow a scheme like `node_cpu_seconds_total`. This breaks existing solutions, but improves usability greatly.

**Comment by simpleprogrammer2** [comment]
[yuvipanda](https://github.com/yuvipanda) this issue can be closeed

**Comment by consideRatio** [comment]
@simpleprogrammer2 thank you! Note that you have now made a contribution to this project by helping us triage the issues! :heart: :tada:

Thank you @simpleprogrammer2 for being an active member of this community!
