### ISSUE TITLE
Hi, i find the jupyterhub is slow to start while there are many users。

### ISSUE THREAD

**Issue by forbxy** [jupyterhub/jupyterhub#1614]
Hi, we find the jupyterhub is slow to start while there are many users。
it slow in app.init_spawner()。this func make User() instances for every user，so I change the code , only make one User() instance,copy it to other user and replace copy's  attr orm_user。I wander if it is safe?
thanks
code like this
`      def init_spawners(self):
          db = self.db
           
          user_summaries = ['']
          def _user_summary(user):
              parts = ['{0: >8}'.format(user.name)]
              if user.admin:
                  parts.append('admin')
              if user.server:
                  parts.append('running at %s' % user.server)
              return ' '.join(parts)
           
          @gen.coroutine
          def user_stopped(user):
              status = yield user.spawner.poll()
              self.log.warning("User %s server stopped with exit code: %s",
                  user.name, status,
              )
              yield self.proxy.delete_user(user)
              yield user.stop()                                                                                                                                                                           
          user_origin = None
          import copy 
          for orm_user in db.query(orm.User):
              if user_origin == None:
                  user_origin = User(orm_user, self.tornado_settings)
              user_copy = copy.copy(user_origin)
              user_copy.orm_user = orm_user
             self.users[orm_user.id] = user = user_copy
`

**Comment by willingc** [comment]
Hi @forbxy.

If you are finding JupyterHub slow to start, it is likely due to the capacity and load on the underlying system. It's very possible that your system does not have enough memory for the peak load for the number of users that you are serving.

You may find the [Zero to JupyterHub Guide](http://zero-to-jupyterhub.readthedocs.io/en/latest/)'s section on autoscaling as well as [JupyterHub documentation on memory limits](http://jupyterhub.readthedocs.io/en/latest/reference/spawners.html#spawners-resource-limits-and-guarantees-optional) (note: the spawner you are using needs to support the limits) helpful.
