### ISSUE TITLE
Spawner.options_form is not shown when servers are started from the admin panel

### ISSUE THREAD

**Issue by BerserkerTroll** [jupyterhub/jupyterhub#1629]
which prevents servers from spawning, because the `user_options` is empty and throws `KeyError` when the spawner tries to get values from it.

**How to reproduce the issue**

1. Enable `admin_access` and add (an) admin user(s)
2. Add an `options_form` to spawner and use some field value from the form in the spawner by accessing `user_options`.
3. Log in as admin and go to admin panel
4. Push the `start server` button.

**What you expected to happen**

The form is shown.

**What actually happens**

An `API request failed (500): error` error raised, because an attempt to use the `user_options` in the Spawner ended with the `KeyError` exception.

**Share what version of JupyterHub you are using**

From the `jupyterhub/jupyterhub:latest` docker image.

**Comment by GrahamDumpleton** [comment]
I suspect I am seeing the same issue but in different scenario.

I am using ``ProfileSpawner`` with JupyterHub. So:

```
c.JupyterHub.spawner_class = 'wrapspawner.ProfilesSpawner'
```

Then something like:

```
c.ProfilesSpawner.profiles = [
    (
        "Jupyter Project - Minimal Notebook",
        'minimal-notebook',
        'kubespawner.KubeSpawner',
        dict(singleuser_image_spec='minimal-notebook:latest',
             singleuser_supplemental_gids=[100])
    ),
    (
        "Jupyter Project - SciPy Notebook",
        'scipy-notebook',
        'kubespawner.KubeSpawner',
        dict(singleuser_image_spec='scipy-notebook:latest',
             singleuser_supplemental_gids=[100])
    ),
    ...
]
```

When you are on the Admin dashboard and select start server for a different user, it results in an error:

```
Traceback (most recent call last):
--
  | File "/opt/app-root/lib/python3.5/site-packages/tornado/web.py", line 1512, in _execute
  | result = yield result
  | File "/opt/app-root/lib64/python3.5/types.py", line 179, in throw
  | return self.__wrapped.throw(tp, *rest)
  | File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/apihandlers/users.py", line 209, in post
  | yield self.spawn_single_user(user, server_name, options=options)
  | File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 475, in spawn_single_user
  | yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
  | File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
  | yield spawn_future
  | File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/user.py", line 439, in spawn
  | raise e
  | File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/user.py", line 378, in spawn
  | ip_port = yield gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
  | File "/opt/app-root/lib64/python3.5/types.py", line 243, in wrapped
  | coro = func(*args, **kwargs)
  | File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/spawner.py", line 968, in start
  | env = self.get_env()
  | File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/spawner.py", line 960, in get_env
  | env = self.user_env(env)
  | File "/opt/app-root/lib/python3.5/site-packages/jupyterhub/spawner.py", line 947, in user_env
  | home = pwd.getpwnam(self.user.name).pw_dir
  | KeyError: 'getpwnam(): name not found: ncoghlan'
```

My guess is that is caused by same issue as here. The form is never presented to provide the option of selecting from profiles defined by ``ProfileSpawner`` configuration. The result is that it goes into ``ProfileSpawner`` and triggers the code:

```
    def select_profile(self, profile):
        # Select matching profile, or do nothing (leaving previous or default config in place)
        for p in self.profiles:
            if p[1] == profile:
                self.child_class = p[2]
                self.child_config = p[3]
                break

    def construct_child(self):
        self.child_profile = self.user_options.get('profile', "")
        self.select_profile(self.child_profile)
        super().construct_child()
```

The ``self.user_options.get('profile', "")`` can't find a ``profile`` option and so results in empty string. When this is used to ``select_profile`` it doesn't find a match and thus doesn't overrwrite ``self.child_class`` with anything from the profile list. The default ``child_class`` from ``WrapSpawner`` base class is:

```
    child_class = Type(LocalProcessSpawner, Spawner,
        config=True,
        help="""The class to wrap for spawning single-user servers.
                Should be a subclass of Spawner.
                """
        )
```

So rather than creating a ``KubeSpawner`` as ultimately wanted, it creates instance of ``LocalProcessSpawner`` which then fires off the code:

```
    def user_env(self, env):
        """Augment environment of spawned process with user specific env variables."""
        import pwd
        env['USER'] = self.user.name
        home = pwd.getpwnam(self.user.name).pw_dir
        shell = pwd.getpwnam(self.user.name).pw_shell
        # These will be empty if undefined,
        # in which case don't set the env:
        if home:
            env['HOME'] = home
        if shell:
            env['SHELL'] = shell
        return env
```

which fails, because ``self.user.name`` in my case is going to a GitHub username as I am using OAuth against GitHub.

I don't know what code to start looking at as to why it doesn't flow into display form for user options. So if you can point me to the correct spot I can dig further.

**Comment by GrahamDumpleton** [comment]
FWIW, I am using:

```
jupyterhub==0.8.1
#jupyterhub-kubespawner==0.8.1
git+https://github.com/jupyter-on-openshift/kubespawner#egg=jupyterhub-kubespawner
git+https://github.com/jupyterhub/wrapspawner
jupyterhub-tmpauthenticator
oauthenticator
psycopg2
```

The ``KubeSpawner`` fork is because of pending PR:

* https://github.com/jupyterhub/kubespawner/pull/134

So using from Git repo rather than ``jupyterhub-kubespawner==0.8.1``.

**Comment by minrk** [comment]
There are two things here. First, I agree that launching from the admin panel ought to show the options form. That's going to be a *little* tricky, as we need to make sure that we serve a page that's launching for one user while authenticating as another, which the current spawn page doesn't handle.

Second, though, is that is should be a best practice for any Spawner that supports options_form to accept sensible defaults for missing fields in user_options. Launching Spawners can be done via the API (as is done with the admin panel), and it should generally be possible to omit user_options unless there really are no defaults that make sense, which should be rare.

**Comment by GrahamDumpleton** [comment]
I can possibly solve the default option by adding configuration:

```
c.WrapSpawner.child_class = 'kubespawner.KubeSpawner'
c.KubeSpawner.singleuser_image_spec = 'something'
```

so it doesn't at least crash, but doesn't really get the desired result, because in the case you are using ``ProfilesSpawner`` to select the image to deploy, as well as possibly other per image settings relates to persistent volumes, working directories for image etc.

Anyway, it seems you answer the question at least to say that right now one can't expect to get the form as the code isn't there to do that.

**Comment by GrahamDumpleton** [comment]
Okay. I used:

```
c.WrapSpawner.child_class = 'kubespawner.KubeSpawner'
```

and did not set ``singleuser_image_spec``.

It didn't error this time and started up the default image of ``jupyterhub/singleuser:latest``.

When you click on access server it brings up a new tab which gives error:

```
403 : Forbidden
The error was:

user grahamdumpleton is not allowed.
```

So this probably also relates to what you said about launching for one user while authenticating as another.

One other strange thing did happen. The first time I tried, because that image will not run in this environment without the:

```
c.KubeSpawner.singleuser_supplemental_gids = [100]
```

the image was failing to start. I didn't realise it was failing. In that case when I clicked on access server, it showed the user options for selection based on profiles in ``ProfilesSpawner``.

So definitely so weird flow happening in all this.

**Comment by minrk** [comment]
Getting a 403 suggests to me that admin-access isn't properly implemented, and that the container was launched without admin-access enabled. Do you see JUPYTERHUB_ADMIN_ACCESS=1 in the pod environment?

**Comment by minrk** [comment]
As for the strange failure, here's my guess of the sequence of events:

1. request spawn from API
2. request succeeds, but spawn ultimately fails (can happen if failure occurs after slow_spawn_timeout)
3. access server link sends you to `/user/:name` URL, but that server isn't running, so it serves the page `/hub/user/:name`. This is the page that normally serves the spawn form.
4. This is probably where it's not doing what you expect/desire. When visiting `/hub/user/:name`, if you are not authenticated as that user, you are redirected to `/hub/user/:yourname`.
5. At this point, you are actually served the options form, but it is *for your own server*, not the server for which you requested access.


I think the fixes are mostly in step 4, which is:

1. when requesting `/hub/user/:name`, rather than checking if you *are* `:name`, check if you should have access to their server (i.e. same_user or (is_admin and admin_access)). Only redirect away if you don't have access to the given server.
2. allow serving the spawn form if you are admin (same as above, minus the requirement for admin_access)
