### ISSUE TITLE
Not passing full environment to service scripts can result in scripts failing.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jupyterhub/jupyterhub#1654]
**How to reproduce the issue**

Use Python from Software Collections Library (SCL.

* https://www.softwarecollections.org/en/

Define a JupyterHub service for culling idle servers.

```
c.JupyterHub.services = [
    {
        'name': 'cull-idle',
        'admin': True,
        'command': 'python cull_idle_servers.py --timeout=3600'.split(),
    }
]
```

**What you expected to happen**

It should run fine.

**What actually happens**

It fails to run with the error:

```
python: error while loading shared libraries: libpython3.5m.so.rh-python35-1.0: cannot open shared object file: No such file or directory
```

The reason it fails is that JupyterHub strips all the environment and only sets or passes through a subset. This doesn't include special system environment variables such as ``LD_LIBRARY_PATH`` which the SCL Python relies on to know where its shared libraries are located.

There is the ability in the definition of a service to specify additional environment variables, but that becomes a pain as you need to work out all the environment variables you might need to be inherited from the original environment in which JupyterHub was was run.

For example, in this environment, it was actually necessary to have:

```
        'environment': {
            'LD_LIBRARY_PATH': os.environ['LD_LIBRARY_PATH'],
            'NSS_WRAPPER_PASSWD': os.environ['NSS_WRAPPER_PASSWD'],
            'NSS_WRAPPER_GROUP': os.environ['NSS_WRAPPER_GROUP'],
            'LD_PRELOAD': os.environ['LD_PRELOAD'],
        }
```

for the cull idle servers script to work. So not totally obvious. If you were working in Kubernetes/Docker and relying on being able to see environment variables they set, then you have to go enumerate all those as well.

It may be better to pass through all environment variables, but strip just JupyterHub environment variables which are undesirable to have be available in a service script, but only if that is necessary.

If concerned that you might pass other environments variables you might not want to, then rather than switch to passing all as default, provide an option to the service definition which allows a user to elect to pass full environment through to service script if necessary. You may still want to strip JupyterHub environment variables in that case.

**Share what version of JupyterHub you are using**

```
0.8.1
```

**Comment by minrk** [comment]
This is mostly inherited from the existing Spawner behavior, where inherited environment variables are a whitelist that is very short (this deliberately excludes things like LD_LIBRARY_PATH and PYTHONPATH, which are at least as likely to be incorrect as correct if passed to user environments). I think it's the right thing to do to require deliberate whitelisting for Hub->user environments.

Services are a bit different, since they are necessarily subprocesses of the Hub, but all of the same concerns about passing credentials by default apply.

> It may be better to pass through all environment variables, but strip just JupyterHub environment variables which are undesirable to have be available in a service script, but only if that is necessary.

This isn't feasible, because those environment variables may not be defined by jupyterhub (e.g. OAuth credentials, kubernetes info, etc.).

> If concerned that you might pass other environments variables you might not want to, then rather than switch to passing all as default, provide an option to the service definition which allows a user to elect to pass full environment through to service script if necessary. You may still want to strip JupyterHub environment variables in that case.

I think this is the right thing to do. Add an opt-in env-blacklist approach, so that all environment variables may be passed, minus a blacklist (default to those that JupyterHub knows about). This is especially true since I think cases like this where non-obvious environment variables are required for subprocesses to run is going to be mostly restricted to advanced users like yourself. At the same time, this:

```python
'inherit_environment': True
```

isn't a lot simpler than

```python
'environment': os.environ
```

Yet another option is that there is really no protection when the subprocess is run as the same user as the hub, since the process has sufficient privileges to interrogate the env of the hub already. We *could* default to inheriting the env in the case where the subprocess is run as the same user as the hub, but that might be one too many conditional behaviors.


As a side note, I do think that almost anything that relies on LD_LIBRARY_PATH to run has probably been compiled incorrectly, omitting the correct runtime path. I was able to verify that scl-rh-python36 on CentOS 7 doesn't require LD_LIBRARY_PATH (at least following their [instructions](https://www.softwarecollections.org/en/scls/rhscl/rh-python36/) in a `centos:7` docker image). Maybe this has been fixed since their python35 build?

**Comment by GrahamDumpleton** [comment]
Unless I am missing it if it is there, see no mention in the docs, maybe like there is ``c.Spawner.env_keep`` add a ``c.JupyterHub.services_env_keep``. That way can at least specify it once across the whole JupyterHub instance. This helps me because I bundle up default settings in an image, and then let users customise further. That way I can set list to keep once and users don't need to do it for each service they might add.

As to SCL variables and whether need ``LD_LIBRARY_PATH``, it may depend on what sort of initial shell session type is used and how you activate SCL packages. In the way that SCL is enabled in base images I use, you must have ``LD_LIBRARY_PATH`` passed through or simply doesn't work.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
