### ISSUE TITLE
changing all cookies to Session

### ISSUE THREAD

**Issue by javin-gn** [jupyterhub/jupyterhub#1672]
Hi, 

We have this requirement of  changing all cookies to Session, is it possible?

**Comment by minrk** [comment]
If I understand you correctly, this means you need cookies to set no expiry in order to use the default of session-expiry?

I be

You can set global cookie_options in:

```python
c.JupyterHub.tornado_settings = {'cookie_options': {'expires_days': None}}
```

This should affect most cookies, but not the cookie used with the single-user server. We will need to expose some configuration for that.

**Comment by javin-gn** [comment]
Does this mean expires tag will be remove?

**Comment by javin-gn** [comment]
Actually i am referring to  automatically expire JupyterHub and single-user server cookie

**Comment by minrk** [comment]
Yes, that's how a Session cookie is set; by excluding the expiry date the default expiry is the duration of the Session. If you want to expire after a shorter period of time, you would set expires_days to a shorter duration, e.g. 1.

**Comment by javin-gn** [comment]
We have try the setting but it is still set to the default expiry of 14 days. How do we go about exposing the single server configuration?

**Comment by minrk** [comment]
#1748 passed cookie_options down to single-user servers so this should affect all cookies, excluding the `_xsrf` token itself, which tornado hardcodes to 30 day expiry.
