### ISSUE TITLE
Rejecting some inputs from users for security

### ISSUE THREAD

**Issue by llancellotti** [jupyterhub/jupyterhub#1712]
Hello everybody,

I’m currently working on a project which involves creating a Jupyter notebook server. As it’s supposed to be multi-user, first thing I thought about was Jupyterhub.

The thing is that I need to control some input/output commands, for security reasons. For example, I can’t let someone run a “read” command on source code of mine.

I confess I’ve been searching for some time... I finally found something useful at
https://mail.scipy.org/pipermail/ipython-dev/2014-September/014846.html

However, I still need some help with this.
Could anyone please help me? How could I have this kind of access control?

Thanks in advance!

**Comment by takluyver** [comment]
I think what you're describing would be very hard to achieve by checking and rejecting user code, unless you're willing to restrict the user to running a very limited set of actions; there are a lot of possible ways to read a file, and lots more ways to disguise what code is doing from automated checkers.

Can you describe more about the background of what you're doing and why you need to prevent users from doing certain things? We might be able to suggest a different approach which is more viable.

**Comment by llancellotti** [comment]
Sure!

In my project, I want to use docker in order to launch a container for each user that logs on his notebook library.

I don’t want the user to have i/o capabilities, so my system may remain secure (specially from invasions). Therefore, I want to create this docker in a very limited way: with just a few python modules, excluding some built-in functions, as well as excluding i/o capabilities.
This way, the user can use his notebook normally but with no risk to my system.

I was thinking of using AST to block functions like those, and then protecting my system and source codes.

**Comment by takluyver** [comment]
That's probably tricky; reading and writing files are fundamental operations, and there are a lot of ways to do them from Python. If you do manage to block them all off, you'll probably break a lot of things that users should be able to do.

The usual approach to this is to let the user access files inside their own docker container, but not let them access anything on the underlying system. That's the aim of a container: things inside it are safely contained, separated from the system outside. There are options you can set which limit the memory and CPU used by an individual container, so one user can't use up all the resources. E.g. this is how [Binder](https://mybinder.org/) works - each user can do whatever they want inside their own container, but they can't do anything outside the container.

**Comment by llancellotti** [comment]
I see...

In my case, I have a private library that users should be able to use in their notebooks.

However, this library has access to a (also private) database. Another reason I’d like to control user access is that no one should make SQL queries to this database.

That’s why it’s being tricky to get this access control to work. 
In this case, what do you recommend?

**Comment by takluyver** [comment]
Presumably the library needs to make some queries which are allowed?

I might run a separate HTTP server which can make the allowed queries and return the results as JSON. Then it's easy to wrap access to that in Python code which makes an HTTP request (e.g. using `requests`) and returns the results. There's no need for that Python code to be secret, because it's just a more convenient way to talk to the server.

In that scheme, the HTTP server is a kind of proxy for the database, which controls what is allowed. The key is to ensure that the requests it handles are in a simple format, so that either there's no way to specify a forbidden query, or it's easy to decide what queries are allowed. HTTP query parameters are a simple format, whereas Python and SQL are both complex formats, which means it's hard to judge when they should be allowed.

**Comment by llancellotti** [comment]
Ok. I'll take a look at your suggestions.

Thank you very much for the quick help!
