### ISSUE TITLE
Users with some special characters can't connect to their servers with Chrome

### ISSUE THREAD

**Issue by chicocvenancio** [jupyterhub/jupyterhub#1717]
Chrome is substituting a few url encoded characters for the literal characters in URLs. The tilde is such a character, so it will substitute `%7E` for `~` in the request. This will make the notebook respond with a 404 to the request. Using another browser (eg Firefox), does not run into the same issue.

**How to reproduce the issue**
Create an user with a tilde in it and attempt to access your server in a jupyterhub deployment with Google Chrome.

**What you expected to happen**
Get a 200 response with the notebook server interface.
**What actually happens**
Get a 404 response.
**Share what version of JupyterHub you are using**
z2jh@0.6 so `jupyterhub==0.8.1`

See https://phabricator.wikimedia.org/T189525

**Comment by willingc** [comment]
I'm going to label this as a bug so we recheck Chrome for 0.9

**Comment by chicocvenancio** [comment]
Still present in 0.9b3

**Comment by minrk** [comment]
@chicocvenancio thanks for testing! I think this is fixed by #1926. Can you test?

I thought it was an issue in the proxy (https://github.com/jupyterhub/configurable-http-proxy/pull/163) but it appears that the simplest fix is to just whitelist those characters whose encoding is optional and ensure we never encode them. We've done this for a few versions with `@` (common in usernames due to emails), so it should work fine to add tilde, too. 

Making every piece robust to the supposed equivalence of `~` and `%7E` seems harder than I'm prepared to deal with right now.
