### ISSUE TITLE
two flags  on start up

### ISSUE THREAD

**Issue by blonc** [jupyterhub/jupyterhub#1730]
here is the output from terminal:

```
[I 2018-03-16 10:39:28.004 JupyterHub app:834] Loading cookie_secret from /srv/jupyterhub/jupyterhub_cookie_secret
[I 2018-03-16 10:39:28.124 JupyterHub app:1528] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-03-16 10:39:28.125 JupyterHub proxy:415] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2018-03-16 10:39:28.126 JupyterHub proxy:458] Starting proxy @ https://*:8000/
10:39:28.338 - info: [ConfigProxy] Proxying https://*:8000 to (no default)
10:39:28.341 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
10:39:28.679 - info: [ConfigProxy] 200 GET /api/routes 
[W 2018-03-16 10:39:28.680 JupyterHub proxy:304] Adding missing default route
[I 2018-03-16 10:39:28.680 JupyterHub proxy:370] Adding default route for Hub: / => http://127.0.0.1:8081
10:39:28.728 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
10:39:28.729 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2018-03-16 10:39:28.730 JupyterHub app:1581] JupyterHub is now running at https://:8000/
```

everything starts up fine and is totally useable but the two flags im getting: 
Generating CONFIGPROXY_AUTH_TOKEN.
Adding missing default route

how can i generate a proxy auth token? I have googled to the end but only seem to find deprecated info 

second how can i get a default route set?

**Comment by betatim** [comment]
To generate the `CONFIGPROXY_AUTH_TOKEN` take a look at the [security section](http://jupyterhub.readthedocs.io/en/latest/getting-started/security-basics.html#proxy-authentication-token) of the documentation.

I don't think the default route message is anything to worry about. When the proxy starts up there are no routes set and it automatically configures itself.

**Comment by blonc** [comment]
I have looked into the security part and the first part of the docs : c.JupyterHub.proxy_auth_token is deprecated.  the second option export CONFIGPROXY_AUTH_TOKEN='openssl rand -hex 32' . but im not sure where to put this?  if I put it into the .config as is, it throws all sorts of errors.

**Comment by minrk** [comment]
`export CONFIGPROXY_AUTH_TOKEN=$(openssl rand -hex 32)` is a shell command that sets an environment variable. You would run it before you start jupyterhub, e.g.

```bash
export CONFIGPROXY_AUTH_TOKEN=$(openssl rand -hex 32)
jupyterhub
```

If you want this to be stable across multiple runs of JupyterHub, then you need to store the value somewhere and re-use it. If you don't plan to restart the Hub while the proxy is still running, then it's AOK to leave it generating a new token on each launch.

#1750 should rearrange the message so that there is no warning when the proxy is being started by the Hub.

The missing default route is a totally normal part of the startup process. The proxy starts with no routes, and the Hub adds itself as the default route.
