### ISSUE TITLE
New columns in admin panel: user name and useremail

### ISSUE THREAD

**Issue by gsemet** [jupyterhub/jupyterhub#1737]
Hi

I am using jupyterhub against a Gitlab instance connected to our internal LDAP, and the username are a bit obscure for everyone (such as "ab12345"). Our Gitlab does returns other information such as the user name ("Gaetan Semet") and our corporate email address.
Is it possible to show these information in the admin panel, as new columns for instance?

thankx

**Comment by minrk** [comment]
It's not at the moment. Since these aren't JupyterHub concepts, it would need to be a completely generic passthrough for any/all auth state. Adding arbitrary columns to the table seems like it might be tricky to do robustly. We could do *one* column (or click-through) for all auth state, though. Additionally, we could allow Authenticators to provide a single string to add for a single new column, and then it would be up to the Authenticator to decide.

**Comment by gsemet** [comment]
yes, an optional column that is oauthenticator owned would be great :)

**Comment by manics** [comment]
Is this something people think can/should be implemented in JupyterHub?

**Comment by manics** [comment]
No response, closing. This sounds useful though, so probably best built as an add-on to JupyterHub
