### ISSUE TITLE
Expire user generated tokens at /hub/token

### ISSUE THREAD

**Issue by elgalu** [jupyterhub/jupyterhub#1772]
Similar to `config.JupyterHub.cookie_max_age_days` could be `config.JupyterHub.user_tokens_max_age_days` with default to the current state `0` == no expiration.

**Comment by minrk** [comment]
0.9 adds timestamps (created and last_activity) to API tokens, so this should now be possible. I'm reticent to do it by default without adding refresh tokens, because it would mean that single-user servers would have a max uptime of token_max_age_days.

**Comment by elgalu** [comment]
Thanks. So far I'm not sure how to handle an employee living the company for instance. i.e. even though they can't login anymore the generated tokens would still be valid.

**Comment by marto1** [comment]
Hi all,
I'm a little new to jupyterhub inner workings so please forgive my ignorance in advance.

Would this change affect the `jupyter-hub-token` cookie as well as `user-*` cookies? Also to my knowledge the `set_login_cookie` mehtod does not expose passing all kwargs to tornado's `set_secure_cookie` method. Can we also fit this in in a nice way?

My use case involves only setting the expiry date to a lot shorter than the 30 days standard one. I got it to work with some local modifications, but it's obviously not something anyone would like to manage over time and it's mandatory to have it for my organization's single-sign-on. 

We're using jupyterhub 0.8.1 if that helps.

**Comment by elgalu** [comment]
Hi, how are other JupyterHub installations dealing with this in this enterprise?
does someone has any feedback?

**Comment by brunocous** [comment]
Any news on how to do this?

**Comment by marto1** [comment]
This method is still patched on our installation and it's pretty ugly.

**Comment by minrk** [comment]
Adding a config option described in OP for default token max age with a default preserving the current behavior makes sense to me in the short term. Doing so at the moment does mean that you are setting a max age of user servers before they must be forced to restart in order to get a fresh token, but for many deployments that's likely not an issue, so I think it's okay to add the option with this caveat.

Then we can turn it on by default perhaps when someone gets a chance to implement refresh token support.

**Comment by lobanov** [comment]
It's amazing to see this getting addressed, thank you. I noticed that this fix narrowly missed 5.0 release, so it's not available for those running the latest version. Is there any chance this could become part of the 5.0.1 release?

Otherwise options are not very pleasant: build from sources, patch the code on deployment, or create a script expiring tokens (e.g., via the API). The latter should be the most straightforward option if this fix wasn't available, but now it seems redundant effort.

**Comment by minrk** [comment]
It wouldn't go in 5.0.1, but I think we will do 5.1.0 soon with the small improvements we've had already since 5.0.0.
