### ISSUE TITLE
Jupyterhub prespawn hook to modify spawner args

### ISSUE THREAD

**Issue by shantanusingh16** [jupyterhub/jupyterhub#1776]
Hi,

I'm trying to use the prespawn hook function modify the spawner notebook directory but it seems that its not getting picked up. 

I'm using Jupyterhub 0.8.1 and LocalProcessSpawner. I've modified the jupyterhub_config.py and added the following:

```
def notebook_dir_hook(spawner):
    import sqlite3
    conn = sqlite3.connect("/src/jupyterhub-service/jupyterdata.db")
    cur = conn.cursor()
    cur.execute("SELECT * FROM notebook_dir WHERE name=?", (spawner.user.name,))
    row = cur.fetchone()
    cur.close()
    if row:
        spawner.notebook_dir = row[1]
        spawner.log.info("Spawner notebook_dir  %s", spawner.notebook_dir)
    #spawner.log.info("Spawner args  %s", spawner.get_args())

c.Spawner.pre_spawn_hook = notebook_dir_hook
```

The last line of the pre_spawn_hook function which is commented out, gives an error if run.

```
Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/types.py", line 179, in throw
        return self.__wrapped.throw(tp, *rest)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/apihandlers/users.py", line 209, in post
        yield self.spawn_single_user(user, server_name, options=options)
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 475, in spawn_single_user
        yield gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 445, in finish_user_spawn
        yield spawn_future
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 439, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 374, in spawn
        yield gen.maybe_future(self.spawner.run_pre_spawn_hook())
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/spawner.py", line 649, in run_pre_spawn_hook
        return self.pre_spawn_hook(self)
      File "/src/jupyterhub-service/jupyterhub_config.py", line 584, in notebook_dir_hook
        spawner.log.info("username_solution  %s", spawner.get_args())
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/spawner.py", line 628, in get_args
        elif self.server.port:
    AttributeError: 'NoneType' object has no attribute 'port'
```

Any ideas how to do this?

**Comment by minrk** [comment]
Thanks for the report! Should be fixed by #1793

**Comment by shantanusingh16** [comment]
This shouldn't be closed as the main issue here is if the prespawn hook unable to modify attributes of the spawner like notebook_dir

**Comment by consideRatio** [comment]
@shantanusingh16 ah yes! You would like a way to modify the notebook_dir!

Can you try if the following does the trick?

```python
def notebook_dir_hook(spawner):
    spawner.notebook_dir = "/user/home/{username}"

c.Spawner.pre_spawn_hook = notebook_dir_hook
```

For some more details, you can look in [kubespawners documentation](http://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#module-kubespawner.spawner).

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request that we reopen this issue. Thanks! 🌻

**Comment by thelfensdrfer** [comment]
> Please feel free to request that we reopen this issue.
Please reopen this issue.

I am trying to mount different docker volumes based on the LDAP groups the user has access to:

```python
def dynamic_group_mount_hook(spawner):
    userdn = f'cn={spawner.user.name},ou=users,dc=equaition,dc=com'
    conn = get_connection(spawner.user.settings['config']['LDAPAuthenticator'], userdn)
    groups = get_groups(conn, userdn)

    for group in groups:
        spawner.user.settings['config']['DockerSpawner']['volumes'][f'jupyterhub-ldap-{group}'] = f'/home/jovyan/work/{group}'
```

**Comment by thelfensdrfer** [comment]
My issue is the same @shantanusingh16 had: You cannot update `spawner` in the function. I don't think this is how python works with scoped variables and all...

To be clear:
* I have no error message, there is no error
* I have no question, how it works is perfectly understandable
* This is a matter of: should this be implemented in a different way or not?

**Comment by consideRatio** [comment]
I have practically updated `spawner` in the pre_spawn_hook function to influence for example what environment variables are used. If you note that you can't update DockerSpawner specifically from the pre_spawn_hook, perhaps its overriding your updates after pre_spawn_hook is executed, and it is a problem of DockerSpawner rather than JupyterHub behavior?

The examples I write about in https://discourse.jupyter.org/t/tailoring-spawn-options-and-server-configuration-to-certain-users/8449 are practical examples updating the individual spawner object created for a user just before spawn, but I also know that I can't modify everything just before spawn because of the nature of KubeSpawner.

Due to this, I see it as crucial for you and contributors to DockerSpawner, JupyterHub etc, that there is a very clear description on what is failing and what is expected to work. I would guess your issue could be with DockerSpawner if you don't note it respond to a simple change of its configuration.

In practice, I note that you are not configuring the spawner, but the referenced user, after the spawner object has been created. I'm not aware of the `user` having properties like settings etc, but if it did, wouldn't those act as default values on a spawner object on initialization? If that is the case, you have your reasons for an issue there, you are updating the default values rather than the relevant values on the instance that is already initiated with the previous default values.

I suggest opening a discourse post about this, and if you can pinpoint it to be an issue with dockerspawner etc, open an issue there. I would suspect you should instead configure your spawner instance in another way than `spawner.user.settings['config']['DockerSpawner']['volumes'][f'jupyterhub-ldap-{group}'] = f'/home/jovyan/work/{group}'`.

**Comment by thelfensdrfer** [comment]
Ok, I will leave it at that. Just for future reference for the next user with the problem:

I am using DockerSpawner and LdapAuthenticator with their default config. Everything works, the ldap authentication and the docker spawner. The only thing which doesn't work is to add additional volumes in the pre_spawn_hook. I was wondering how the discourse example can ever work because arguments cannot be updated, until I realized that the `spawner` argument was an object (not totally clear from https://jupyterhub.readthedocs.io/en/stable/api/spawner.html#jupyterhub.spawner.Spawner.pre_spawn_hook). 

I was more or less guessing what was in that spawner object, that was the reason for my complicated dictionary access. The values were in the right position but of course, could not be updated. This was my latest try and I guess that the volumes have to be defined earlier, but like @consideRatio said, this issue should be raised in the dockerspawner repository:

```python
def dynamic_group_mount_hook(spawner):
    userdn = f'cn={spawner.user.name},ou=users,dc=equaition,dc=com'
    conn = get_connection(spawner.user.settings['config']['LDAPAuthenticator'], userdn)
    groups = get_groups(conn, userdn)

    for group in groups:
        spawner.volumes.update({
            f'jupyterhub-ldap-{group}': f'/home/jovyan/work/{group}'
        })
```
