### ISSUE TITLE
Websocket connection should be unavailable after logout.

### ISSUE THREAD

**Issue by 8rV1n** [jupyterhub/jupyterhub#1780]
The websocket connection for the terminal should be unavailable after logout operation but it is still working like normally logged in.

**How to reproduce the issue**
1.  Normally open a terminal 
2.  Logout
3. Test the terminal

**What you expected to happen**
It shouldn't happen that I can still use the terminal since I have already logged out.

**What actually happens**
It works like I have just signed in.

**Share what version of JupyterHub you are using**
Server Information:
You are using Jupyter notebook.

The version of the notebook server is: 5.4.0
The server is running on this version of Python:
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]
```
Current Kernel Information:
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by betatim** [comment]
What spawner are you using?

My guess would be that you are using the local process spawner (I can reproduce the bug with that) and the shell process isn't cleaned up when the single user notebook process is stopped. My guess would be that the shell process is not a child of the notebook server and hence doesn't get stopped. The easiest thing to do  (in terms of clean up) would be to make it a child process. I suspect though that is tricky due to it being a login shell or something?

**Comment by ArvinSiChuan** [comment]
@betatim I'm using a docker spawner. We deployed the jupyterhub and the users' singleuser notebook in the containers separately.

**Comment by minrk** [comment]
Logging out doesn't shutdown the server (multiple browsers may be logged in to the same server, clearing cookies in one shouldn't shutdown the server in use by the other) and authentication of websockets only occurs at connection time, not on every message. So an already-open, authenticated connection to a websocket for a server that's left running will continue to be active until the connection is lost or the server is shutdown.

This is a duplicate of #735

**Comment by ArvinSiChuan** [comment]
@minrk I've read the related issues and I aslo think like said in the issue #735 that the connection after logout is some kind of defect because with the terminal over the connection we can do a lot of things such as downloading a remote virus.  Imagine that if I'm using a public computer with a virtual desktop in a library or some place, and I opened several browsers windows in each of the desktop, later logged out and then someone come to the computer.    
In the view of the end users, most cases will be that the user using the jupyter by himself only and no sharing. If there some of the situation that I don't know for multi-user using the same jupyter notebook instance at the same time, I think there should be an option to choose stop server or not. For what I know, stop server at logout will be not a problem for you to implement.

**Comment by minrk** [comment]
I don't think a hypothetical scenario where one leaves tabs open and active with access to sensitive info on a public machine and departs is very compelling. Cross-window logout is very complicated. If you logged out of your session on the computer or closed the browser, tab, or window this would all be a non-issue because new connections would be rejected.

Providing an option to stop a server at logout would be one option to address this issue, but it can't address the issue in general as it wouldn't be the default behavior, and thus shouldn't and couldn't ever be the expected behavior from the user perspective. If a *deployment* wants to implement this, it can, but users cannot ever expect it.

In the same way that the notebook has both "close" and "close and halt" behaviors for closing a notebook and the more destructive action of closing a notebook and terminating its kernel, perhaps there should be a "logout and shutdown" dedicated action that clearly does the destructive additional operation of shutting down your server. Notebook 5.5 adds a 'Quit' action, and we could hook this up to a 'shutdown and logout'.

**Comment by ArvinSiChuan** [comment]
The case I said there might be a little bit of extreme but there is a chance that the same condition may happen. In another words, it is a potential security risk there especially the terminal connection compared with the notebook connection.

To provide an option for stopping server or/and to add a 'shutdown and logout' both reasonable and friendly to all kinds of users. Looking forward to the upgrading.

**Comment by willingc** [comment]
To recap:

> Logging out doesn't shutdown the server (multiple browsers may be logged in to the same server, clearing cookies in one shouldn't shutdown the server in use by the other) and authentication of websockets only occurs at connection time, not on every message

Designed behavior.

> Providing an option to stop a server at logout would be one option to address this issue, but it can't address the issue in general as it wouldn't be the default behavior, and thus shouldn't and couldn't ever be the expected behavior from the user perspective. If a deployment wants to implement this, it can, but users cannot ever expect it.

Default behavior will remain.

> In the same way that the notebook has both "close" and "close and halt" behaviors for closing a notebook and the more destructive action of closing a notebook and terminating its kernel, perhaps there should be a "logout and shutdown" dedicated action that clearly does the destructive additional operation of shutting down your server. Notebook 5.5 adds a 'Quit' action, and we could hook this up to a 'shutdown and logout'.

Enhancement which would need to be scheduled relative to other release priorities.

**Comment by manics** [comment]
Closing based on the above comments
