### ISSUE TITLE
How do I track IP Address from where a user logged in to their account from into JupyterHub?

### ISSUE THREAD

**Issue by nikolayvoronchikhin** [jupyterhub/jupyterhub#1822]
JupyterHub version:
jupyterhub --version
0.8.1

OS: 
Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by minrk** [comment]
JupyterHub logs ip addresses for requests. For instance, with the default handler you will see log statements like this:

    [I 2018-05-04 15:21:47.962 JupyterHub log:158] 302 POST /hub/login?next= -> /user/benjaminrk/ (benjaminrk@::1) 112.66ms

That's me (benjaminrk) logging in from ipv6 localhost (`::1`).

If you are using an OAuth handler, the login request will be something like `GET /hub/oauth_callback`.

**Comment by nikolayvoronchikhin** [comment]
Thank you @minrk , the solution you provided helped with tracking the user's IP Address logged into the account.  

How about for this case: If the user spoofs the IP Address or uses a Proxy Server to login to JH, is there a way to reverse proxy or get the original IP Address?

**Comment by minrk** [comment]
Proxies, e.g. nginx, have configuration to control whether they trust such information. Since JupyterHub is always behind at least one proxy, it is configured to trust proxy headers. I would configure it at that level, such that your frontmost proxy discards incoming proxy headers like `X-Forwarded-For` and `X-Real-IP`, so that it is in control of the proxy headers.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!
