### ISSUE TITLE
JupyterHub with the IDL kernel is unable to plot anything and gives error

### ISSUE THREAD

**Issue by sunipkmukherjee** [jupyterhub/jupyterhub#1900]
I will attach a screenshot:

<img width="1299" alt="untitled" src="https://user-images.githubusercontent.com/13347009/40254945-62f05384-5ab3-11e8-84c0-904a5545008c.png">

It does work in Jupyter Notebook, though.

**Comment by betatim** [comment]
It tries to access the `DISPLAY` environment variable which suggests it is trying to talk to a X server to open an extra window/GUI. Is that what happens when you run it locally? If yes then I think you are out of luck/need to do a lot of configuring to have the `DISPLAY` variable set so that it forwards to your local X server.

**Comment by sunipkmukherjee** [comment]
Even when I do set the display variable manually, it is unable to access it and show the plots. On the other hand, in jupyter notebook, it shows the plot in the notebook like normal. It never tries to access an external xserver window. I think it is similar to the problem some people using R faced at some point.

Regards,

Sunip K. Mukherjee,
PhD Candidate, Physics,
Treasurer and Web Administrator,
Graduate Physics Association,

University of Massachusetts,
Lowell.

E-Mail: Sunip_Mukherjee@student.uml.edu || sunipkmukherjee@gmail.com

**Comment by willingc** [comment]
@sunipkmukherjee Would you mind filing this issue with the IDL kernel as it looks like their implementation of IDL magic is not working properly? Thanks. I'm going to close here since this is outside of JupyterHub's scope.
