### ISSUE TITLE
Question: Why are there two different classes with the name `Spawner`?

### ISSUE THREAD

**Issue by krinsman** [jupyterhub/jupyterhub#1906]
While trying to understand the source code for what seems to be JupyterHub's "main" `Spawner` class which inherits from `LoggingConfigurable` and is found in [`spawner.py`](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L38), I recently stumbled upon the existence of another class called `Spawner` in [`orm.py`](https://github.com/jupyterhub/jupyterhub/blob/f2941e36312a2a1134f04e06f39bd9ca248cc046/jupyterhub/orm.py#L196) which inherits from `Base`.

What is the purpose of the second class? Its docstring just says "State about a Spawner". This confuses me further since the class name is `Spawner`, and not `SpawnerState` or something like that, which would seem to agree more with the docstring. 

Is an instance of the `Spawner(Base)` class supposed to be the object-to-relational mapping applied to an instance of the `Spawner(LoggingConfigurable` class? Why do they have the same name?

How are the two classes distinguished from each other elsewhere in the code base? Is the convention for using an instance of the `Spawner(Base)` class to write `from jupyterhub import orm` in the preamble and then use `orm.Spawner` in the body? (E.g. as is done [here](https://github.com/jupyterhub/jupyterhub/blob/3f90697e189ae7d7b2d61ce08ef68553b28c28ec/jupyterhub/tests/populate_db.py#L48)?)

Sorry in advance for the stupid question.

**Comment by minrk** [comment]
The classes in `orm.py` describe the ORM data and relationships for each object. For more complex objects (User, Spawner), there is a higher-level class that *wraps* the orm object (rather than subclassing the ORM types). The ORM objects use Entity names rather than 'EntityState' because that seems to be the convention of ORMs. You can think of orm.Spawner as the subset of Spawner that lives in the database.

> How are the two classes distinguished from each other elsewhere in the code base? 

Typically, orm objects are referred to as `orm_spawner`, etc. in context to distinguish them from the higher-level objects.

**Comment by krinsman** [comment]
Thank you for the feedback! This makes more sense to me now; I really appreciate it!
