### ISSUE TITLE
Error loading package in notebook

### ISSUE THREAD

**Issue by alealv** [jupyterhub/jupyterhub#1931]
I've posted the issue and solution in jupyter's notebook repo https://github.com/jupyter/notebook/issues/3649

### Problem
Hi, I'm having a problem trying to load opencv package inside jupyter notebook. I run jupyter-hub as a service and I log in with my user and set the proper kernel.

The thing is that outside jupyter (python or ipython) the package loads correctly.
![screenshot from 2018-05-29 11-48-51](https://user-images.githubusercontent.com/9395091/40681614-00d82f22-6360-11e8-9dd0-dcc2e89a948d.png)

But when loading from the jupyter notebook a link error is raised telling a dependent library is not found.
![screenshot from 2018-05-29 11-42-58](https://user-images.githubusercontent.com/9395091/40681622-097c1f08-6360-11e8-95c0-eab3da252975.png)

### Solution
The problem was, as we thought, the env-variables. We just hardcode this env-variables to the Spawner in the config and now it works.

**Comment by willingc** [comment]
Thanks for passing along. If folks are running into this issue, please reference the discussion at jupyter/notebook#3649.

**Comment by rkdarst** [comment]
I've noticed that environment handling will soon become an important point in batchspawner, and in general I think will become something important but doesn't have much documentation or support (e.g. extend `Spawner.env_keep` instead of replace it).  Does anyone else get this feeling?

I don't have time to do more right now, but will there may be some PRs in the future...
