### ISSUE TITLE
Named servers via UI

### ISSUE THREAD

**Issue by rcthomas** [jupyterhub/jupyterhub#1935]
There are a few issues posted about named servers already, but I'm really interested in seeing about what we can contribute on named servers through the UI (not via the API).

I imagine if a `server_name` value came in from the options form it could be picked off and set as the `server_name` parameter in the call to `spawn_single_user` done [here.](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/handlers/pages.py#L141-L142)

Or maybe it's better to add a `default_server_name` method to `Spawner` that is just the empty string and let various `Spawner`s determine `default_server_name` however they want.  This could involve form options or be independent of them altogether.  We would just need to call that method, get the answer and pass it to `spawn_single_user`.

But both above seem obvious so I must be missing something.  There are maybe other things missing like an admin page for all the servers for each user that should be done, or other logic I'm not thinking about?

**Comment by willingc** [comment]
Thanks @rcthomas for the suggestion. Can you clarify a bit what you would like added to the options form?

**Comment by rcthomas** [comment]
Well I am not sure that's the right approach.  :)  I could see how it could be used though.

More open-ended, is there a "to do" list outlining what things need to be done to get named servers working compatibly with the UI?  We have some personnel over the summer and we might be able to make some progress contributing to that effort.

**Comment by minrk** [comment]
I don't think named servers UI is necessarily hard, we just haven't had the time or priorities to do it yet, so if you are volunteering to work on it, that would be great!

I think doing it via the options form is definitely one valid option. We should short-circuit it a little, because the server name shouldn't get passed through the overrideable options_from_form. Something along the lines of adding the server name input to the configurable options form if named servers are enabled, and always showing the spawn form if named servers are enabled, rather than just when options_form is defined.

e.g.

```python
form  = """
    <label for="jupyterhub-servername">Server Name</label>
    <input type="text" name="jupyterhub-servername" class="form-control">
""" + spawner.options_form
```

and pop `jupyterhub-servername` out of the formdata before calling `.options_from_form` on the rest.

The other main UI feature we need is a page for listing/managing/linking to existing servers (running and not). The admin UI will also need to gain support for named servers.

There's another option, and that's to make the "new named server" a specifically different action from the "spawn my (default) server" button we have now. Then the server name is picked earlier, rather than in the spawn form. This may be the best option. We would need to mock up the new "start/stop/delete/new" servers UI that works both for the default only-one server and the named servers case. This would probably replace the current 'home' page.

There may possibly be some backend features we want, e.g. for creating a named server with a collection of options, persisting those options, then relaunching the server *without* prompting again with a form, but that can be a stretch goal.

So here's a rough todo list:

- [ ] list/start/stop/open UI for named servers, likely on the current home page
- [ ] allow creating new named servers, either from server-list UI (my current preference) or via existing spawn form
- [ ] UI for named servers on admin page
- [ ] persist form options and *optionally* skip form (stretch goal, possibly after we determine that people are really using this and want it)

**Comment by rcthomas** [comment]
@minrk thanks for taking the time to elaborate on this.  We'll update the thread when we make reportable progress.

**Comment by krinsman** [comment]
Really dumb question, but where in the source code is the option to view the admin control panel for admin users enabled? The most possibly relevant section of code I could find was this chunk in the class definition for `JupyterHub`: https://github.com/jupyterhub/jupyterhub/blob/14c8d7dc46017100abd1ac9455d90a27b4b27367/jupyterhub/app.py#L1146

But it mentions a lot how that attribute of the `JupyterHub` class is deprecated, and that the corresponding attribute for the `Authenticator` class should be used instead. But looking at [the relevant section in `auth.py`](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/auth.py#L62) it doesn't seem like anything is done with that attribute, much less the creation of an admin panel for them to view.

I presume that [this line](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/user.py#L371) in the `User` class definition isn't relevant to this issue, since all it does (maybe?) is say whether or not admin users can edit and modify the notebooks of other users, if I remember the documentation correctly. On the other hand, it seems to be the only point in `user.py` where the string "admin" occurs. So it doesn't seem like the `User` class has anything to do with whether or not an admin user can view the extra admin control panel.

Is [this line](https://github.com/jupyterhub/jupyterhub/blob/cb9ce4d3af9f3b2a7e4fdb94786b91e99cd954b0/jupyterhub/handlers/base.py#L173) from the definition of one of the handlers relevant? I doubt it, but I'm just throwing it out there since it has the string `admin` in it.

**Comment by krinsman** [comment]
Oh never mind, that really was a stupid question of me, it's found here isn't it?

https://github.com/jupyterhub/jupyterhub/blob/e48bae77aa29786c50c86d8c38fd0f80752ee2dc/jupyterhub/handlers/pages.py#L161

**Comment by krinsman** [comment]
@minrk Another dumb question: if/when named servers are implemented, what should be done with the `redirect_to_server` config option? Should it be made impossible for both `allow_named_servers` and `redirect_to_server` to be true simultaneously?

My point simply being that `redirect_to_server` being `True` assumes in the first place that the user has a unique single-user notebook server (correct me if I am wrong), but if that assumption is violated, then there isn't really any good default protocol for which of their notebook servers they should be forwarded to instead.

Whereas if the user has multiple notebook servers, the home page (where you quite sensibly the notebook server management UI be located) would always be a sensible place for the user to be redirected upon login, IMO.

My gut feeling is that it should be made impossible for both `allow_named_servers` and `redirect_to_server` to be true simultaneously, but I would like to avoid messing around with the internals too much to achieve that effect only to later find out from you that that was the wrong approach in the first place.

**Comment by krinsman** [comment]
@minrk To implement what you're suggesting, at the very least the code around this line:

https://github.com/jupyterhub/jupyterhub/blob/e48bae77aa29786c50c86d8c38fd0f80752ee2dc/jupyterhub/handlers/pages.py#L142

and this line:

https://github.com/jupyterhub/jupyterhub/blob/cb9ce4d3af9f3b2a7e4fdb94786b91e99cd954b0/jupyterhub/handlers/base.py#L999

needs to be modified, right?

As far as I can tell, the following is basically the place where named servers are implemented via the API

https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/apihandlers/users.py#L344

and the main method involved in accomplishing that seems to be `spawn_single_user`, so it seems to be the case that, at a very minimum, for implementing named servers the UI, it would be necessary to modify all of the calls to `spawn_single_user` which occur via the UI. Is that correct?

**Comment by minrk** [comment]
> if/when named servers are implemented, what should be done with the redirect_to_server config option? Should it be made impossible for both allow_named_servers and redirect_to_server to be true simultaneously?

Good question. There are two options here:

1. named servers are an "advanced" feature for only some users, and for most the default behavior should be preserved
2. when named servers are in use, require that all servers have a name (essentially, do away with the 'default' server notion)

In order to allow case 1, I suspect this means that we shouldn't *force* redirect_to_server to be False, but perhaps change the *default* if named_servers are in use. That would make the 'default server' behavior opt-in for deployments with named servers.

**Comment by krinsman** [comment]
As far as I can tell, currently spawning of a named server via the API occurs via a POST request ([here](https://github.com/jupyterhub/jupyterhub/blob/f2941e36312a2a1134f04e06f39bd9ca248cc046/jupyterhub/apihandlers/users.py#L373)).

@minrk  **Question:** Does spawning of a(n unnamed) server via the UI currently occur via a GET request ([here](https://github.com/jupyterhub/jupyterhub/blob/5f97487184bb8e308ed68d024a02ae0ef1bc4fe1/jupyterhub/handlers/base.py#L1012)) or via a POST request ([here](https://github.com/jupyterhub/jupyterhub/blob/5f97487184bb8e308ed68d024a02ae0ef1bc4fe1/jupyterhub/handlers/pages.py#L142))?

(It's not clear to me based on the routes for either [`UserSpawnHandler`](https://github.com/jupyterhub/jupyterhub/blob/5f97487184bb8e308ed68d024a02ae0ef1bc4fe1/jupyterhub/handlers/base.py#L1136) or for [`SpawnHandler`](https://github.com/jupyterhub/jupyterhub/blob/5f97487184bb8e308ed68d024a02ae0ef1bc4fe1/jupyterhub/handlers/pages.py#L342).)

If it occurs via a GET request, it might be a little more annoying to implement named servers via UI, because then new proxy routes/a whole new syntax would have to be created for instantiating named servers via GET request. Whereas if it occurs via POST request, it seems that one would be able to re-use much more of the logic of the API implementation, and that the only refactoring required would involve changing the call to `spawn_single_user` [here](https://github.com/jupyterhub/jupyterhub/blob/5f97487184bb8e308ed68d024a02ae0ef1bc4fe1/jupyterhub/handlers/pages.py#L142) to have a parameter value for the keyword argument `name` (or perhaps `server_name` in the future) passed to it, and changing all preceding function calls required to ensure that the value of the parameter reaches that point in the code.

**Comment by krinsman** [comment]
@rcthomas You will probably find this interesting: https://github.com/jupyterhub/jupyterhub/pull/2089

All that remains to implement a full UI named servers set up seems to be HTML/Jinja/CSS/Javascript programming to have the right buttons in the right places.

If the admins want to choose the name of the servers in advance, they can just abstract the relevant GET requests behind buttons which automatically form GET requests that create servers with the right names. On the other hand, if the admin wants to allow users to choose the name of the servers, then they can have the GET requests formulated in part depending on the input to a form.

**Comment by krinsman** [comment]
This issue should be closed -- it is made obsolete by: https://github.com/jupyterhub/jupyterhub/pull/2089

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!

**Comment by gabber12** [comment]
> > if/when named servers are implemented, what should be done with the redirect_to_server config option? Should it be made impossible for both allow_named_servers and redirect_to_server to be true simultaneously?
> 
> Good question. There are two options here:
> 
> 1. named servers are an "advanced" feature for only some users, and for most the default behavior should be preserved
> 2. when named servers are in use, require that all servers have a name (essentially, do away with the 'default' server notion)
> 
> In order to allow case 1, I suspect this means that we shouldn't _force_ redirect_to_server to be False, but perhaps change the _default_ if named_servers are in use. That would make the 'default server' behavior opt-in for deployments with named servers.

Maybe We should document this behaviour somewhere, i fell into this issue and struggled for around 6 hours before discovering this thread. 
I would more than happy to do this. What would be the right place to put this down?

**Comment by krinsman** [comment]
Another possibility is that maybe we could allow the default server to remain `''` even if named servers are enabled, but if `c.JupyterHub.default_server_name` is set to something else, then have `redirect_to_server` redirect to that named server instead?

That would go along well with https://github.com/jupyterhub/jupyterhub/pull/2735
(which I need to update/fix, I think along the lines of the fork https://github.com/krinsman/jupyterhub , although ideally I want to test that fork on Cori at NERSC before making a PR for it).

**Comment by gabber12** [comment]
Also is it a good idea to add a non-named server to the named-server table on the UI? Its kind of confusing to have both modes of launching notebooks. 
On the control panel both places have to be checked to know what all things are running.

<img width="1296" alt="Screenshot 2019-12-12 at 10 51 51 PM" src="https://user-images.githubusercontent.com/1253456/70734329-13718b00-1d32-11ea-8888-3182098aead9.png">

**Comment by krinsman** [comment]
I agree it's kind of confusing, even having helped write the UI myself. 

The idea is that "My Server" is the "nameless" server `""`, since that's what the user's server always was before named servers were implemented, but I'm not sure whether that's actually documented anywhere in the code or such.

It also kind of unclear how that should be changed if the JupyterHub setup has "profiles" or a default (non-empty) server name.

@gabber12 Maybe you might also find this issue interesting? https://github.com/jupyterhub/jupyterhub/issues/2724 It's sort of related, what sort of assumptions should be in place regarding named servers and whatnot.

**Comment by gabber12** [comment]
@krinsman 
I have modified the jupyter hub in the following way.
**When Named servers are enabled.**
<img width="1306" alt="Screenshot 2019-12-13 at 1 48 18 PM" src="https://user-images.githubusercontent.com/1253456/70818516-eee0e600-1df9-11ea-9b8a-87576b9770c2.png">
 Note a user launches a default server by leaving the name input empty.

**When Named Servers are disabled**
<img width="772" alt="Screenshot 2019-12-13 at 10 40 13 PM" src="https://user-images.githubusercontent.com/1253456/70818537-fb653e80-1df9-11ea-8c1a-f167b7ee2910.png">

IMHO this way is more clearer UX wise.

**Comment by krinsman** [comment]
This UX makes sense to me -- I'm not a maintainer and don't have write access, but it looks like it might make sense to make a new PR based on this.

The only feedback I could think of would be to add a button around "Add New Server" so that it's clearer that that's what needs to be pressed to launch the default server.

Also make sure that the admin page looks similar! Since admins can see all users' servers.

**Comment by gabber12** [comment]
@minrk Would love to know your thoughts on this.
