### ISSUE TITLE
Jupyterhubb only able to spawn a single user Error: 500 (Github user mapped to UNIX user) 

### ISSUE THREAD

**Issue by Akmoore7** [jupyterhub/jupyterhub#1957]
My team and I are building a JupyterHub on Ubuntu 16.04 on amazon-ec2. When setting up the hub, we followed this tutorial (https://www.youtube.com/watch?v=alaGteCPZU8) and added github authentication. However, I downloaded all of the files while signed in to "daniel" on the server and now I am only able to spawn a server when I am signed in to that account (and it is not even possible to sign in to it since I switched to github authentication). I am able to sign in with my github account but I get a 500 Internal Server Error when I try to start a server. Here is the error log when I attempt to spawn a server: 
![](https://i.stack.imgur.com/0FbSX.png)

I was able to get around this issue by mapping a github account to the UNIX user, but I can only get this to work with one github account and this is not a good solution because I need multiple users to be on the server simultaneously. Here is my jupyterhub_config.py file:
![](https://i.stack.imgur.com/ybG4U.png)

Jupyterhub Version: 0.8.1

To reproduce simply go onto jupyter2.uiuc-bdeep.org as a whitelisted user that is not mapped to the unix user 'daniel' and you shall be met with a 500 error. The intended response would be a server starting under that user.

**Comment by minrk** [comment]
username_map maps upstream (GitHub in this case) usernames to JupyterHub usernames, not just system names. That means that the GitHub user `akmoore7` once logged in should be the JupyterHub user `daniel` and `danielrychel` will be logging in to the *same JupyterHub account*. The effective result should be that you have a JupyterHub with only one account: daniel and you have given multiple GitHub accounts access to this one JupyterHub user and server (i.e. only one notebook server will be running, not one per GitHub account).

So here are a few questions:

1. do you want each person to have their own JupyterHub account?
2. do you want all the users to be running as the same user (same home directory, etc.) as each other and as the Hub itself?

Typically, with local users one runs JupyterHub itself as root with `create_system_users=True` so that each GitHub user gets an account on the system, without any `username_map`, or rather only with `username_map` for the few accounts that might have names that cause problems on the system.

You will also have to make sure that all the packages you install are installed in a location readable and executable by all users (typically /usr/local for a shared system).

**Comment by willingc** [comment]
Closing this issue as it's been inactive for over a month. Please feel free to request that we reopen this issue. Thanks! 🌻
