### ISSUE TITLE
docker error 

### ISSUE THREAD

**Issue by reddyvenu** [jupyterhub/jupyterhub#1959]
![docker error](https://user-images.githubusercontent.com/38197992/41144022-0a36f678-6b19-11e8-9246-121459d5b61c.PNG)

**Comment by betatim** [comment]
This looks like a problem you are having with docker not with JupyterHub. Could you explain a bit more of the context otherwise we should close this issue.

---

What docker is telling you is that you can not push the ubuntu image to the docker hub. This is expected as you aren't one of the maintainers of Ubuntu.

**Comment by reddyvenu** [comment]
![docker error](https://user-images.githubusercontent.com/38197992/41145916-3cb9f1ee-6b1f-11e8-8f40-ec505c2882fb.PNG)

**Comment by reddyvenu** [comment]
docker working 5n but error is occurring

**Comment by willingc** [comment]
I'm closing this issue, but feel free to continue asking questions here.
