### ISSUE TITLE
Excluding Login page form Google Search

### ISSUE THREAD

**Issue by maryamdev** [jupyterhub/jupyterhub#1979]
Hello! Could you please tell me how to exclude Jupyterhub homepage / Login page from indexing by Google Search by either adding robots.txt or adding an http header, X-Robots-Tag: noindex

I have a standalone installation as per the first section of your YouTube video tutorial. I do **not** have Apache.

I am using Github Authentication, that is why I want to be able to send the login link to my students only and not to let it found on Google by anyone.

Many thanks!

**Comment by minrk** [comment]
This is tricky, but we should be able to do it. 0.9.0 supports registering custom handlers, and you should be able to do so for robots.txt.

If you put apache or nginx in front, you could add a handler for robots.txt at that level, too.

We should support defining a robots.txt directly without having to define a custom handler, though.

**Comment by maryamdev** [comment]
Many thanks! Great! I have just upgraded to JupyterHub 0.9.0. Any hint / doc about how to define a custom handler for robots.txt?

Of course, in the future, this would be great if this can be without a custom handler.

**Comment by minrk** [comment]
It turns out it's easier than I thought. Tornado has its own support for serving robots.txt from the static folder, so if you create `{prefix}/share/jupyterhub/static/robots.txt` with the desired contents, it should work, where `{prefix}` is the installation prefix for JupyterHub, e.g. `/usr/local` or `/opt/conda` etc.

We can still work on making it easier to specify this, but that should be the easiest way to do it right now.

**Comment by maryamdev** [comment]
This is just perfect. Many thanks!
