### ISSUE TITLE
Putting the security recommendations into practice

### ISSUE THREAD

**Issue by EtienneDesticourt** [jupyterhub/jupyterhub#1995]
Hi,

I'm in the process of installing and configuring JupyterHub and I'm finding the "Security Overview" (http://jupyterhub.readthedocs.io/en/latest/reference/websecurity.html) section a bit hard to implement. I'm sorry if it's a bit out of scope and relying on a lot of linux knowledge but as a lot of things in security, ease of use/implementation goes a long way towards adoption so I think a more thorough guide would be very helpful.

Apologies if this gets a bit long there are quite a lot of steps I'm unsure about.

## Protect users from each other

**_A user does not have permission to modify their single-user notebook server, including:_**

**_A user may not install new packages in the Python environment that runs their single-user server._**

To do so you'd remove write permissions from the virtualenv folder, is that correct/enough?
What command would you use to do so?

**_If the PATH is used to resolve the single-user executable (instead of using an absolute path), a user may not create new files in any PATH directory that precedes the directory containing jupyterhub-singleuser._**

Alright, so I'll just use the absolute path found using `which jupyterhub-singleuser` in the future.

_**A user may not modify environment variables (e.g. PATH, PYTHONPATH) for their single-user server.**_

How would a user go about doing that? I'd think he could only do that when starting the single-user server so can I just put the single-user server startup script in read and execute only?
What command would you use to do so?

### Disable user config

_**If subdomains are not available or not desirable, JupyterHub provides a a configuration option Spawner.disable_user_config, which can be set to prevent the user-owned configuration files from being loaded. After implementing this option, PATHs and package installation and PATHs are the other things that the admin must enforce.**_

I set `c.Spawner.disable_user_config = False` in the `jupyterhub_config.py` file in the folder in which I start JupyterHub. How can I check whether it's worked?
Additionally I need to set an environment variable for each user so I have a jupyter_notebook_config.py in each of their homes script that does the following:
```
import os
os.environ["MY_ENV_VAR"] = "MY_VALUE_FOR_THIS_USER"
```
Will this script be rendered useless by this option? If so is there a workaround for such a use-case (setting the jupyter_notebook_config.py file in read only mode)?
If not what will be the consequences of enabling user configurations?

### Prevent spawners from evaluating shell configuration files

_**For most Spawners, PATH is not something users can influence, but care should be taken to ensure that the Spawner does not evaluate shell configuration files prior to launching the server.**_

It's very vague to me. Concretely what should I be looking for in my spawner to avoid this issue?

### Isolate packages using virtualenv

_**Package isolation is most easily handled by running the single-user server in a virtualenv with disabled system-site-packages. The user should not have permission to install packages into this environment.**_

First I created a virtualenv in my user's home directory:
`python -m virtualenv venv`
Then I wrote the following script: (based on #564)
```
#!/usr/bin/env bash
source ~/venv/bin/activate
exec python /usr/local/bin/jupyterhub-singleuser $@
```
When run I get an ImportError: "No module named 'jupyterhub'". It seems counter-intuitive that I'd need to install jupyterhub for every single user but I'll do it if it's what is recommended or am I misunderstanding something here?

_**It is important to note that the control over the environment only affects the single-user server, and not the environment(s) in which the user’s kernel(s) may run. Installing additional packages in the kernel environment does not pose additional risk to the web application’s security.**_

Shouldn't I forbid installations in the kernel packages as well? Couldn't the user install a malicious package that could then be run by other users using this kernel?
Why does disabling package installations for the single-user server environment in particular improve security?

Are there other things I should be doing to secure my Jupyter Hub installation?

## That's about it.

I also wanted to tell you how grateful I am for all the work you have put into this project, I think it's a great product and I'm excited at the prospect of deploying it.

Thank you

**Comment by minrk** [comment]
> To do so you'd remove write permissions from the virtualenv folder, is that correct/enough?
What command would you use to do so?

You want the installation to be owned and writable by an admin user and/or an admin group (simplest is root:root, but I'll go with the more general case, assuming `jupyterhub` is the admin user and `jupyterhub-admin` is the group). This command will ensure the following:

- All files are owned by the user jupyterhub
- All files are writable by members of the jupyterhub-admin group
- All files are readable and executable by all users, but NOT writable

```bash
PREFIX=/opt/conda # the shared env location
# set ownership
chown -R jupyterhub:jupyterhub-admin "$PREFIX"
# ensure all files are group-writable, all-user-readable, and *not* other-user writable
chmod -R g+w,a+rX,o-w "$PREFIX"
```

> How would a user go about doing that? I'd think he could only do that when starting the single-user server so can I just put the single-user server startup script in read and execute only?
What command would you use to do so?

Unlike some of the other issues here, this one isn't usually possible by default. It can be, though, if you specify the launch script to instantiate the user's full shell (e.g. `c.Spawner.shell_cmd = ['bash', '-l', '-c']`) then it can source their .bashrc files which may contain user-specified variables. You just have to make sure that you aren't launching any script initialization that will load user config files.


> I set c.Spawner.disable_user_config = False in the jupyterhub_config.py file in the folder in which I start JupyterHub. How can I check whether it's worked?

If you create `~/.jupyter/jupyter_notebook_config.py` and put configuration in there, it should be ignored. If you start notebook servers with `--debug`, it will log each path it searches and each config file it loads.

> Additionally I need to set an environment variable for each user so I have a jupyter_notebook_config.py in each of their homes...Will this script be rendered useless by this option?

Yes, this config should be ignored. If you want to create configuration that will affect all of your users, you can put it in `/etc/jupyter/jupyter_notebook_config.py` instead of a separate copy in everybody's home directory. `disable_user_config` disable's config files *in the user's home*, not all config files in general.

> Concretely what should I be looking for in my spawner to avoid this issue?

I think this one is mostly answered with the permissions bit above. You will need to inspect the Spawner to see what command it uses to launch the notebook server and ensure that it doesn't instantiate a shell in a way that will load config files from $HOME. This is not generally the default behavior of Spawners, so it is generally safe by default.

>  It seems counter-intuitive that I'd need to install jupyterhub for every single user

It should be *one* env, used (readable but not writable) by all users, not a separate one for each. See the first point at the top for how to set permissions on this shared env.

> Shouldn't I forbid installations in the kernel packages as well? Couldn't the user install a malicious package that could then be run by other users using this kernel?

You can if you want to, but installing kernel packages specifically does not affect *web* security of the notebook server, since it's running in a separate process, not the web server. Jupyter is already all about arbitrary code execution, so installing packages *for the kernel* is not generally more of a problem than having a kernel in the first place.

> Why does disabling package installations for the single-user server environment in particular improve security?

Package installation allows arbitrary code execution at import time. For instance, if you allowed package installation in an env that the server would load, they could install a package called `jupyterhub`  that changes what the jupyterhub-singleuser entrypoint launches when it does `import jupyterhub`.

> Are there other things I should be doing to secure my Jupyter Hub installation?

The main other things are general security concepts like:

- Use SSL
- Ensure your jupyterhub config files and secrets are secure (not world-readable)


> I also wanted to tell you how grateful I am for all the work you have put into this project

Thanks! :heart:

**Comment by rkdarst** [comment]
There was something I wanted to ask about this security model: I understand why a user should never be able to show arbitrary raw HTML to another user.  But if the user can modify their single-user server, shouldn't the only be able to show raw HTML to themselves?  Where does the security problem come from (feel free to give me a technical name and I can check myself).

Of course, this breaks down if the single-user servers are shared by some means... which isn't normal, right?  Actually, I guess it is possible... e.g. public sites with link-based security only.  Is this related?

**Comment by EtienneDesticourt** [comment]
Thank you, this cleared up quite a few things. I'm still unsure about a few points though.


### Configuration

> Yes, this config should be ignored. If you want to create configuration that will affect all of your users, you can put it in /etc/jupyter/jupyter_notebook_config.py instead of a separate copy in everybody's home directory. disable_user_config disable's config files in the user's home, not all config files in general.

I need a different config for each user so it seems I can't set the `disable_user_config` flag. Can I make it so the single-user server only loads `jupyter_notebook_config.py` from the user's home and disable write permissions on that file to achieve the same effect?


> Ensure your jupyterhub config files and secrets are secure (not world-readable)

It seems the jupyterhub server loads configuration files from a few location (.ipython, .jupyter, the directory from which it was launched, others?). Is there a way I can whitelist the configuration files I want to load so that I'm sure I have set the right permission on those and a malicious user can't add a config file in a directory I haven't anticipated?


### Arbitrary code execution

Concerning arbitrary code execution, I'm confused about the different processes involved and what you include in the scope of web-security. 
The way I understand it there are 3 processes: The jupyterhub server, the single-user server (one per user), and the kernel (one per notebook per user).
1) The jupyterhub server is owned by the jupyterhub user so disabling package installation in that one would prevent privilege escalation, that makes sense to me.
2) The single-user server is shared, and owned by the user **(<- am I mistaken in thinking this?)** for which it is launched at a given time, so disabling package installation prevents a malicious user from executing arbitrary code on import for other users. The process is owned by the user so it shouldn't impact the jupyterhub server.
3) The kernels are also shared, and owned by the user by which they're launched, but disabling package installation is not important for them? Why is that, how do they differ in term of web security from the single-user server?
Couldn't a user modify the `math` library of the kernel environment, for example, so that it displays HTML code on import thereby making all other users execute arbitrary code in their browser?

**Comment by minrk** [comment]
> But if the user can modify their single-user server, shouldn't the only be able to show raw HTML to themselves?

They can already show arbitrary HTML to themselves. But since authentication is implemented *in the server*, if they can modify it, they can allow other users access and thus attempt to issue cross-site requests for users who visit their compromised server.

> I need a different config for each user so it seems I can't set the disable_user_config flag. 

Different config per user *doesn't* mean you need different config *files* per user. This is one of the reasons jupyterhub_config.py is a Python script. You can have configuration that's a function of the user in `/etc/jupyter/jupyter_notebook_config.py`:

```python
import os
user = os.getenv('JUPYTERHUB_USER')
c.SingleUserNotebookApp.notebook_dir = os.path.expanduser('~')
...
```

> It seems the jupyterhub server loads configuration files from a few location (.ipython, .jupyter, the directory from which it was launched, others?)

No, Jupyter*Hub* only loads configuration from the current directory or passed explicitly via command-line flags. Only the notebook servers that JupyterHub starts load config from ~/.jupyter *unless* disable_user_config is set. Only *IPython kernels* load config from ~/.ipython.

> The single-user server is shared, and owned by the user (<- am I mistaken in thinking this?)

The single-user server *env* is shared and should not be owned by any regular user. It should be owned by either an admin uesr or root.

> The kernels are also shared, and owned by the user by which they're launched, but disabling package installation is not important for them?

Package installation for kernels *if they are not shared* is not a web security vulnerability because code in the kernel cannot modify the notebook server.

> Couldn't a user modify the math library of the kernel environment, for example, so that it displays HTML code on import thereby making all other users execute arbitrary code in their browser?

Only if other users already have access to run kernel code on the user's server, which requires the notebook server env itself to be compromised first.

**Comment by EtienneDesticourt** [comment]
Oooh great, don't know why I didn't think to do that conditional jupyterhub config.
It's all very clear now, thank you!

Did that clear up things for you as well @rkdarst ? If so I'll close.

**Comment by rkdarst** [comment]
Yes, this cleared up my question.   thanks!

@minrk, thanks for that info.  That precisely answers the question.  To repharase, "a user could modify their server and trick someone else to go to /user/attacker and all expected CSRF can happen".

**Comment by minrk** [comment]
Thanks for the useful discussion! If any of this suggests that there should be added / re-worded info in the web security doc, a PR would be very welcome.

**Comment by EtienneDesticourt** [comment]
I'll open a PR this weekend.

**Comment by rkdarst** [comment]
So, some extra info:   From what I can tell, most batchspawners *do* read user shell files in their current form.

Fixing this is probably possible, but will probably be inconvenient.  On HPC systems, user environment can matter and playing a whitelist/blacklist game gets hard.  One option would be to have kernels source environment before running.  Obviously, you can explicitly change kernel.json to use ['sh', '-c', '...'].

Abstractly, what would you think of a notebook config option to run kernels through a shell?  It's a hack and I'm not saying I like it, but it could be effective.

**Comment by minrk** [comment]
> Abstractly, what would you think of a notebook config option to run kernels through a shell?

I'm not sure. This would be to avoid launching the *notebook* via shell, but letting user kernels get a full shell environment? It makes sense in principle.

**Comment by rkdarst** [comment]
> > Abstractly, what would you think of a notebook config option to run kernels through a shell?

> I'm not sure. This would be to avoid launching the *notebook* via shell, but letting user kernels get a full shell environment? It makes sense in principle.

Yes, exactly.

It seems that subprocess.py uses:
```
if shell:
    args = ["/bin/sh", "-c"] + args
```
... but from what I can tell and experiment with, this doesn't work
with argument list (?!).


I did some experimentation and it seems this should work to run any
argv list through a shell, properly preserving separate arguments and
all:
```
args = ['bash', '-c', '"$0" "$@"' ] + args
```
... I would have already made a PR, but haven't been able to figure
out where this is done.  If you can point me to it, I will play with
it some.

-- 
| Richard Darst   -   http://rkd.zgib.net/   -   pgp 0xBD356740
| "Ye shall know the truth and -- the truth shall make you free"

**Comment by rkdarst** [comment]
> ... I would have already made a PR, but haven't been able to figure out where this is done. If you can point me to it, I will play with it some.

jupyter/jupyter_client.  I'll stop talking here and make another issue about it if I continue.
