### ISSUE TITLE
[Feature Request] Allow authenticators to control group membership

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/jupyterhub#2022]
It would be useful to allow the authenticator to determine group membership as this could allow AD groups to be used in an enterprise setting.

I haven't had time to look into this but I wanted to get this out there for consideration in light of the recent PR #1564.

I'm imagining the default base-class implementation would use the existing database backend but that e.g. the `LDAPAuthenticator` could instead override that to check AD group membership.

**Comment by minrk** [comment]
Makes sense. I think there are a couple of issues with how we get data from the Authenticator into the hub database when it comes to things like admin or groups. The simple way to do it is to implement this is to import the info to the Hub database on login. The downside is that this doesn't stay in sync, so changes to the user's group membership according to the Authenticator (e.g. GitHub team membership, LDAP changes, etc.) will not get reflected until the next login at best.

It's logical to allow Authenticators to entirely take over the administration of admin and group membership (i.e. flags on the Authenticator cause admin and group data in the Hub database to be completely ignored). One challenge is that these would have to be async to accommodate slow/remote sources of this info, but authentication checks are currently a bit difficult to make async. It's not impossible, but it's the main technical hurdle. There's an extra hurdle for oauth things like GitHub because the application can't always make the necessary API requests without tokens *for each user*, which means storing the tokens in the Hub in a retrievable form (e.g. auth_state) for re-use, and if this info for a given user goes stale / is revoked, the information cannot be retrieved again until the user logs in again.

**Comment by dhirschfeld** [comment]
I'd had similar thoughts about stale cached auth data in the database and was also leaning towards the solution of being able to opt-in to ignoring the database entirely for auth purposes. You would want a flag to control that as using the database is simpler than managing access via AD groups.


> *authentication checks are currently a bit difficult to make async*

Just curious (my async-foo is terrible) but doesn't [`run_in_executor`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.run_in_executor) work to asyncify ~everything?

**Comment by minrk** [comment]
> Just curious (my async-foo is terrible) but doesn't run_in_executor work to asyncify ~everything?

It's not that they checks themselves are hard to make async. It's that the current *use* of things like `get_current_user` or the `user.admin` attribute, assume that it isn't, and many of the places where they are called would be hard to asyncify (e.g. `user.admin` in template rendering, etc.). The challenge is that changing a call from sync to async means that every possible caller of that method must also be changed from sync to async, and that's not always easy. It's not insurmountable, just a bit of a tedious refactor.

**Comment by yuvipanda** [comment]
I believe this was fixed by https://github.com/jupyterhub/jupyterhub/pull/3548
