### ISSUE TITLE
anyone who can help start jupyterhub by docker contianer ?

### ISSUE THREAD

**Issue by XIAHUALOU** [jupyterhub/jupyterhub#2033]
I am a data analysis engineer,but now,i have to build jupyterhub environment with docker.I have no idea  
on it,anybody who can help me,please,I met some trouble in using dockerspawner to spawn a docker container with a hub server.

**Comment by XIAHUALOU** [comment]
you can contact me  by wechat
 my account number: 13347706476,

**Comment by willingc** [comment]
Hello @XIAHUALOU, 

I would recommend trying the [Zero to JupyterHub Guide](https://z2jh.readthedocs.io) or asking more specific questions on the JupyterHub Gitter channel.

Thanks!

P.S. I'm closing this issue as we encourage public communication so that all can benefit and learn from open discussion.
