### ISSUE TITLE
Spawner get ip address of notebook server only at start phase, but this address can changed in k8s

### ISSUE THREAD

**Issue by tantra35** [jupyterhub/jupyterhub#2037]
**Describe the bug**
If jupyterhub launched in cluster environment(for example k8s, nomad, mesos), this is quite expected, that notebooks servers can run on different hosts, but they also doesn't stay on host persistently(for example if hardware failure occur, or cluster simply shrinks its size due autoscale) and cluster software can move this notebooks servers to another host, and is expectantly that ip address is changed, but if i understand code of `Spawner` class doesn't exist any way to say about this fact to hub(spawner say to hub about ip address of notebook only at start, and doesn;t update this info), so it can updates it routes

**Comment by yuvipanda** [comment]
On kubernetes at least, the IP of a given spawned pod never changes until the Pod is destroyed. So KubeSpawner doesn't run into issues with this. Unsure about other places, however.

**Comment by tantra35** [comment]
@yuvipanda i not so familiar with k8s but this sounds strange because doesn't satisfy failsafe scenario is aws where overlaynetworks(network build on top of they network stack) not so performant as underlayed. In our case we use nomad(https://www.nomadproject.io/) as cluster manager where migration of notebookserver container is possible with ip address chnage

**Comment by consideRatio** [comment]
KubeSpawner creates a single pod without any controller responsible for it such as a `Deployment` or `StatefulSet`. It is these controllers (and the `ReplicaSet`) they control that ensures a Pod to always be available.

So currently, ensuring that a specific user-pod is available at all times would require the kubespawner to create controllers rather than free pods as it currently does, by that time we would run into the complexity you are describing.

**Comment by yuvipanda** [comment]
See discussion in https://github.com/jupyterhub/kubespawner/issues/138 on why we'll probably always only use Pods directly in KubeSpawner.

**Comment by yuvipanda** [comment]
Going to close this, feel free to reopen if you still have concerns, @tantra35.

**Comment by feriat** [comment]
@yuvipanda, I have a very similar question, so would reopen this question.

Instead of k8s, we use our own cloud setup with modified DockerSpawner. We sometimes want to switch user from one server to another. That is to say, change it's IP and expect Proxy to forward to new route immediately. Is that possible somehow? Is there a better solution in case of needed redeployment or change of host?

**Comment by feriat** [comment]
Min, I guess I do something wrong:
I took one users's IP, and then `psql update servers SET ip = '{other_persons_users}' WHERE base_url = '/user/{user}/';`  for other user. Then I tried to access this user's Jupyter, expecting to see other user's files, but instead I saw old files.

I guess that old route was caches in proxy somewhere?

**Comment by feriat** [comment]
Dear Min @minrk and Yuvi @yuvipanda , could you please help here with correct procedures to change users's server on-the-fly in JupyterHub? I tried the naiive method that didn't work, probably due to caching.

**Comment by minrk** [comment]
Updating the db directly probably won't have an effect without restarting the Hub process. JupyterHub makes several assumptions including caching that the Hub process is the only source of database changes.

If IP addresses aren't stable in your deployment, I'd recommend using something that can be stable, e.g. cluster DNS, so that such updates are not needed.

**Comment by feriat** [comment]
So if I see it correctly the idea is to make all the migrations outside the JupyterHub environment, providing JH stable DNS, and switching servers/backends on the DNS side. Thanks alot for the answer!

**Comment by minrk** [comment]
That's exactly right. I wouldn't expect any changes to URLs made directly to the database to work, and now that I think of it, I'm not sure even restarting the Hub will be enough to recover. It may not be DNS *per se*, but the gist is that the Spawner should return a URL that's stable as long as the service is 'up'. For Kubernetes, for instance, cluster IP addresses are stable, even if things migrate from one node to another. It could be DNS or cluster virtual network or a .local entry name in your hosts file. Anything that's stable. And I would suggest any change in this URL to be treated by JupyterHub as the server being down, such that it needs to be started again by the Hub.

**Comment by serlina** [comment]
Spawner get ip address of notebook server only at start phase, but this address can changed in k8s----we met the issue recently,   jupyterhub+ kubespawner(k8s) + singleuser notebook servers(pod),  for unknow reason, the user's notebook pod restarted in k8s, and the pod IP address changed, but jupyterhub don't know the change, it saved the old IP address to connnet to the pod, and failed to connnet, raise 503 error

**Comment by yuvipanda** [comment]
@serlina What network plugin are you using for kubernetes? AFAIK pod IP only changes if pod is deleted and started again - pod restarts keep the same IP...

**Comment by tantra35** [comment]
Our solution for solve this is - switch to using dns names instead IPs. In nomad enviroment this is very simple throw consul(https://www.consul.io/), but for k8s this is also possible

**Comment by serlina** [comment]
@tantra35 ,  as you said above, you use hostname instead of IP address, could you please provide more detail information how to do this, thanks

**Comment by serlina** [comment]
c.KubeSpawner.poll_interval   will update the singleuser instance routes automatically? does it work ?

**Comment by sstarcher** [comment]
@tantra35 I'm also interested in how to configure it to use a DNS name instead of an IP address.  I see the configuration on the spawner side, but I'm not seeing how the hub understands what address to use.
