### ISSUE TITLE
Move to python>=3.6

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/jupyterhub#2048]
Now that 3.7 is out it might be time to start thinking about moving to `python>=3.6` - i.e. only support N-1 python versions.

This would allow the use of f-strings and inline types amongst others.

**Comment by willingc** [comment]
@dhirschfeld Thanks for the suggestion.

In the long term, I agree that we likely should drop 3.5 support. In the short tem, I believe the last time @minrk and I discussed this that the feeling was to continue support for 3.5 to give users (and Linux distributions) a bit of time to move beyond 3.5 themselves.

**Comment by minrk** [comment]
I feel like we were a little bit aggressive dropping 3.4 before it's EOL later this year, so I think maybe N-2 is a little safer. Let's keep an eye on it, though. Being able to use native async generators would be really nice.

**Comment by dhirschfeld** [comment]
My point of view is that it's so easy to create environments these days that requiring new dependencies isn't a problem - you just create an environment with whatever is required. If jupyterhub suddenly required `python>=3.7` it wouldn't be a problem (*modulo dependencies):
```
conda create --name jupyterhub python=3.7 jupyterhub
```
IIUC `pipenv` works similarly.

For different projects where there are other libraries which depend on you it's poor form to force everyone to keep up and used only the latest version but it seems to me jupyterhub is exactly the project where you can do that as it's not a dependency of a vast ecosystem of libraries. In fact for those libraries which do depend on jupyterhub (spawners/authenticators/?) having a very conservative backward compatibility policy also prevents them from using any modern features of the language.

In any case, I'm just putting this PoV out there. I couldn't say if it would be supported by the majority of users or if I'm the only crazy one who loves developing on the bleeding edge 😜

**Comment by jhermann** [comment]
If you run things in a more regulated environment (e.g. a data center), adding "custom" stuff like non-system Python versions can be a challenge. So IMHO the baseline should be "Python version supported by the *stable* version of major distros" (e.g. Debian stable or Ubuntu LTS).

**Comment by dhirschfeld** [comment]
> *So IMHO the baseline should be or include "Python version supported by the stable version of major distro*

Isn't it considered bad practice to use the system python version for anything? Isn't good practice to use your own python install/environment so you don't break the system python?

**Comment by jhermann** [comment]
The classic tool (virtualenv / venv) for this still has ties into the system Python and only contains a *partial* copy of it.

**Comment by willingc** [comment]
Let's keep this discussion focused on the issue which is when to drop support for Python 3.5.  There are technical reasons related to asyncio that 3.5 is the minimal version of Python officially supported by JupyterHub.

**Comment by willingc** [comment]
@minrk I'm going to tentatively mark this as an issue for the 1.0 milestone. If that's too optimistic, let's create a 1.1 milestone 👍

**Comment by yuvipanda** [comment]
@willingc I'd love for us to drop 3.5 support in 1.1 rather than 1.0 :)

**Comment by willingc** [comment]
@yuvipanda I just modified to 1.1. What was the reason to stick with 3.5 longer?

**Comment by yuvipanda** [comment]
@willingc I think 1.0 has some important security features (OAuth scopes) that people in high compliance environments would want. I have felt the pain that @jhermann describes write a bit, so would love for us to keep 3.5 support for a bit more. Debian Stretch ships with 3.5

**Comment by minrk** [comment]
Using [Ubuntu LTS](https://wiki.ubuntu.com/Releases) for reference:

| Release | EOL (April) | default python3 | latest packaged python | 3.6 via [deadsnakes](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) ppa? |
| -- | -- | -- | -- | -- |
| 14.04 | 2019 | 3.4.3 | 3.5.2 | ✓ |
| 16.04 | 2021 | 3.5.1 | 3.5.2  | ✓ |
| 18.04 | 2023 | 3.6.5 | 3.7.0 | N/A |

So it depends a bit on what we mean by LTS as a baseline. If we mean we always support Python 3 packaged by all LTS releases still supported by Canonical, that means we can't drop Python 3.5 support for at least 3.5 more years. If we mean at least two LTS releases must package our base Python, that puts 20.04 as the earliest date. If we just need one LTS, then we could rely on Python 3.7 today, but that mostly ignores the 'L' in LTS.

I would love to have a better real-world measure for "how much of a pain is it to get Python 3.6" for users, since in a lot of cases, getting the Python runtime from conda / docker / ppa makes the system Python version irrelevant. But there are of course cases where that doesn't fly for policy or technical reasons. I would like to understand, for instance, what is the intersection of cases where recent Python is hard, but recent JupyterHub is desired.

As much as I love Python 3.6 features (async generators and f-strings being probably the two keys among them), I suspect for maintenance purposes, the benefits to us as developers do not yet outweigh the costs to users to dropping 3.5 just yet.

**Comment by manics** [comment]
https://github.com/jupyterhub/jupyterhub/blob/c3ca924ba896bf2da40cab29e2a08784850a945b/setup.py#L97
