### ISSUE TITLE
jupyterhub_config.py in .dockerignore. Why?

### ISSUE THREAD

**Issue by epoch1970** [jupyterhub/jupyterhub#2064]
I see it makes docker build print funny messages but overall I've found the addition of jupyterhub_config.py to .dockerignore rather unhelpful.
Esp. when the Dockerfile comments invite you to add that file to the image.

**Comment by minrk** [comment]
The reason is the `ADD . /src/jupyterhub`, which adds the full contents of the repo directory to the image. If folks are testing jupyterhub and might have generated a config file in the repo, these files shouldn't be included in the image.

> when the Dockerfile comments invite you to add that file to the image.

Yes, *descendant* images built with `FROM jupyterhub/jupyterhub` should add a jupyterhub_config.py. Not the base jupyterhub/jupyterhub image built from this repo, which shouldn't ever contain a jupyterhub_config.py.
