### ISSUE TITLE
How can I install jupyterhub==1.0.0.dev

### ISSUE THREAD

**Issue by yfc845** [jupyterhub/jupyterhub#2085]
Hi guys,

We have deployed jupyterhub:1.0 docker image to our environment, then we need to deploy our notebook image which should match the same version of jupyterhub. But when I was trying to:

pip install jupyterhub==1.0.0.dev

in my notebook image, it says the latest version of jupyterhub is 0.9.2

How should I install jupyterhub 1.0.0.dev? How is this version installed in image jupyterhub:1.0 ?

**Comment by minrk** [comment]
You can install jupyterhub master (currently 1.0.0.dev) with:

    pip install https://github.com/jupyterhub/jupyterhub/archive/master.tar.gz

So far, jupyterhub 1.0.dev is fully compatible with 0.9.2 (it has ~no changes yet since that release). But I wouldn't recommend using that tag.

I've fixed the docker builds in #2094 to not publish the "1.0" tag prior to 1.0 release, so that tag has been removed. Now there should be a "1.0.0.dev" tag, instead, and 1.0 shouldn't exist until 1.0 begins its release process.
