### ISSUE TITLE
Access database from spawner.

### ISSUE THREAD

**Issue by h4gen** [jupyterhub/jupyterhub#2106]
Hey! I am currently working with the repo https://github.com/harvard/cloudJHub which provides a spawner for Ec2 instances on AWS. I want to further customize it and make block storages re-attachable. For this, I would like to access the jupyterhub db from the spawner to create a new table with storage informations for the users. Is this possible? I could not find any infos on this. Thanks!

**Comment by minrk** [comment]
If you need a database, I might recommend creating an additional database connection and controlling that yourself, rather than piggybacking on the existing database, which I don't consider an API that will be maintained as stable for Spawner authors.

Do the [spawner state](https://jupyterhub.readthedocs.io/en/stable/reference/spawners.html?highlight=state#spawner-state) and [authenticator state](https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html?highlight=auth_state#authentication-state) mechanisms offer enough to store the additional state you need to persist?

**Comment by h4gen** [comment]
Hey! Thank you for your answer. Thats exactly how I do now. I use the same database (to use the same server) and create an additional table with my own information. Thanks!
