### ISSUE TITLE
Add an option in the Admin page, which let user set their default notebook home dir.

### ISSUE THREAD

**Issue by tongda** [jupyterhub/jupyterhub#212]
My problem may be a duplication of [this issue](https://github.com/jupyter/jupyterhub/issues/203), but the solution to it is not user-friendly. So I hope we could add an option in the Admin Page. User can set their own notebook home directory easily. How do you think?

**Comment by minrk** [comment]
It doesn't make sense to put this on the admin page because only admins can see the admin page. This wouldn't allow users to set their own home directory.

If users want to set their own notebook directory, that's actually part of the single-user server, and not part of JupyterHub at all. Setting `NotebookApp.notebook_dir` in `~/.ipython/ipython_notebook_config.py` should do it.

**Comment by tongda** [comment]
Thanks for your reply.

Actually, when I was saying that put an option on the admin page, I was going to say, maybe, user's config page. 

The scenario of needing an option on the page is that, when I was doing python training at client's, I hope to use Jupyter to start an central server, the students could connect to it to do some exercises without installing anything of configuring anything, because they may not have experience of IPython. So making some customisation on the page, instead of modifying some file on remote server, should help them focus on there exercise.

**Comment by obust** [comment]
I totally agree with tongda here. This is not the sort of config task you want to go through when you are a starting Python programmer (or any other language). And Jupyter is a great tool for this kind of audience, so it should be considered. Plus, it is a basic must-have configuration that is to be expected of such a tool. Otherwise great work on the project.

**Comment by willingc** [comment]
Closing this issue since it is resolved through user configuration. Please feel free to leave a new issue at [jupyter/help](https://github.com/jupyter/help) or leave additional questions here. Thanks to all!
