### ISSUE TITLE
Do not expose S3/Postgres credentials to JupyterHub users

### ISSUE THREAD

**Issue by martinzugnoni** [jupyterhub/jupyterhub#2140]
I'm using the `dockerspawner`, with the official `jupyterhub/singleuser` image, and [s3contents](https://github.com/danielfrg/s3contents) as contents backend (same issue applies to `pgcontents` as well).

While configuring `s3contents`, we need to provide credentials to connect to S3 service. We can do it by directly writing into `~/.jupyter/jupyter_notebook_config.py` config file, or reading from env variables.

In any of those cases, any logged in user can read the config file o review the exposed env variables using a terminal session.

I can't find a way to securely connect to S3/Postgres from within the running docker container without exposing the credentials to the JupyterHub authenticated user.

Any suggestions?

Thanks.

Note: I initially wrote a [ticket in s3content's repo](https://github.com/danielfrg/s3contents/issues/47), but we couldn't find a solution for it.

**Comment by minrk** [comment]
I think the only way to protect info available to the notebook server from kernels is to run those kernels in a different container from the notebook server. Even if you isolate the kernel env by using environment variables and, the user can trivially inspect the env/cmd of the notebook server by looking at `/proc/`.

Alternately, you could implement the s3/postgres via a proxy service, where the ContentsManager talks to the proxy with jupyterhub credentials and the proxy talks directly to s3/postgres.

A third option that's probably not robust, is to pass the credentials via a file and *consume* this file (remove it after reading) when the notebook starts. That would at least make it harder, but you should probably assume that users can read arbitrary memory from the notebook server process, even if it's hard, because it's in the same container running as the same user. You might be able to further isolate this by modifying KernelManager to setuid the kernels to a different user than the notebook server.

**Comment by martinzugnoni** [comment]
thanks @minrk! 

I thought about the proxy option, and it seems the most robust and flexible to me. Mainly because I can use the proxy to further validate that a user is performing valid action in the correct namespace inside the S3 bucket, and reject the operation otherwise. I thought about creating unique per-user tokens to authenticate against the proxy, and in that way it doesn't matter if the user has access to the token, because he/she won't be able to perform any actions in behalf of another user with it.

I will give it a try and come back with news.

Thanks!

**Comment by jreadey** [comment]
@martinzugnoni - another approach would be to define an IAM role for the AWS instance(s) the container is running on.  That way you don't need to store credentials.  See: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html.

**Comment by willingc** [comment]
Closing this issue since it appears to be addressed. Please let us know how it goes @martinzugnoni. If needed (hopefully the suggested approaches will resolve), we can reopen the issue. Thanks to all!

**Comment by martinzugnoni** [comment]
I finally took a completely different approach by using https://github.com/s3fs-fuse/s3fs-fuse.
Thanks for supporting anyway.

**Comment by willingc** [comment]
Hi @martinzugnoni, Thanks for passing along what worked for you. I'll label this reference since it may benefit others or future documentation. 👍
