### ISSUE TITLE
API handlers are returning text/html responses

### ISSUE THREAD

**Issue by cristofercri** [jupyterhub/jupyterhub#2146]
I've recently upgrade to v0.9.3 from v0.8.0. When I try to make a request to any of the API endpoints (`/hub/api/info` - for instance) I'm getting back the header Content-Type set to text/html instead of application/json as it used to be prior the upgrade.

Should I use some configuration parameter, maybe related to tornado?

Thanks!

**Comment by betatim** [comment]
Happens for me as well with `curl -v https://hub.mybinder.org/hub/api`. Not sure if something changed that by default you get `text/html` and have to send a header with your request to ask for JSON. Otherwise this seems like a regression.

**Comment by cristofercri** [comment]
@betatim We tried to overcome this issue by forking the repo and setting the header on every API handler - though it'd be cleaner to use some kind of interceptor method.

We'll keep watching for new updates.

**Comment by betatim** [comment]
Do you want to make a PR to upstream your changes?

**Comment by cristofercri** [comment]
Yes, I'll make it ASAP.

**Comment by minrk** [comment]
The issue is that a `.get_content_type` method was [removed by accident](https://github.com/jupyterhub/jupyterhub/commit/a3ed3874559cfa551a2f0a1f915496210ed22f4f#diff-25c1b30b13352428653b89995c9ab459L21-L23) from `jupyterhub/apihandlers/base.py`. Adding back:

```python
def get_content_type(self):
    return 'application/json'
```

to `jupyterhub.apihandlers.base.APIHandler` should fix this. @cristofercri are you planning to make that PR? If so, I will be happy to merge it and release 0.9.4 with the fix.

**Comment by minrk** [comment]
@cristofercri do you have time for the PR in the next couple of days? If not, I'm happy to make it. Thanks for the report!

**Comment by cristofercri** [comment]
@minrk since your fix seems simpler than mine, please go for it and make the PR. Thanks for your work!
