### ISSUE TITLE
GSS initiate failed 

### ISSUE THREAD

**Issue by mdivk** [jupyterhub/jupyterhub#2186]
I have successfully integrated JupyterHub with LDAP, here is how I use it:

1. kinit
2. sudo jupyterhub
3. log in

I am able to interact with data on HDFS, JupyterHub seems working fine for me;

My colleague can also log in, however, if he starts a new notebook, he receives GSS initiate failed error:
18/09/24 11:07:48 WARN security.UserGroupInformation: PriviledgedActionException as: user_abc (auth:KERBEROS) cause:javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]

What is the account I should use to start JupyterHub? do I must use sudo? this is exposing risk and violating our usual security policy. 

Thank you very much.

**Comment by minrk** [comment]
@parente do you have any insights on setting up Kerberos with LDAP, permissions etc.?

**Comment by parente** [comment]
https://github.com/jupyterhub/jupyterhub-example-kerberos is the sandbox we used when we first toyed around with Kerberos. It probably needs some updating, but the gist of the setup is still there.

Roughly speaking:

1. Configure PAM to auth against an LDAP server
2. Configure the Kerberos credential cache to point to a unique location per user (https://web.mit.edu/kerberos/krb5-1.12/doc/basic/ccache_def.html)
3. Authenticate user logins to Jupyter Hub using the standard local auth mechanism (so that it goes through PAM to LDAP)
4. Have users create a Kerberos keytab file after first login (or do it for them using the Jupyter Hub auth hooks)
5. Have users `kinit -kt ~/my-keytab` once in a while (e.g., after they start a notebook kernel) to refresh the Kerberos ticket granting ticket (TGT) in their credential cache

The hardest part is configuring Kerberos itself. Once you can successfully `kinit` on a host in an ssh session, fetch a TGT, and use that ticket to fetch other tickets to talk to other services, there should be nothing stopping your users from doing the same thing from within a notebook instead.

**Comment by mdivk** [comment]
Thank you @parente , this looks like a pre-spawn phase should/could include the kinit part to get the needed ticket for the post-login activitities.

**Comment by manics** [comment]
I'm closing this as it's quite old and it's a support issue. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/). Thanks!
