### ISSUE TITLE
General system specifications per user

### ISSUE THREAD

**Issue by AcademicAdmin** [jupyterhub/jupyterhub#2246]
Hello,

I am managing Jupyterhub in an educational environment. The system is a virtual Ubuntu server with external storage attached for the user directories. The system is onsite, it is not running in a cloud service.

At the moment, we have 2 classes using the system. While not everyone is accessing the Jupyterhub system at the same time, there is the potential for 40 active connections at once (assuming both classes access the system at the same time for any reason).

Are there any general guidelines for resources the server should have per potential connection? While the system has been mostly stable up to this point, I did experience an outage that looked to be related to load on the system. I increased the available resources, but if the class expands further I would like to be able to anticipate further resources that may be required.

Thank you

**Comment by betatim** [comment]
It is quite tricky to say without knowing more about what your users are running in terms of code.

The guidance here https://the-littlest-jupyterhub.readthedocs.io/en/latest/howto/admin/resource-estimation.html is pretty good.

One experience from running several JupyterHubs for workshops and classes is that CPU tends to not be a limiting factor because people spend a lot of time reading, typing and thinking in a typical workshop where code tends to run i na few seconds or minutes. Compared to full on scientific computing where you have jobs that run for hours and hours.

**Comment by AcademicAdmin** [comment]
Thank you, that was helpful. Our system is still running without issues and I have a better idea of what I should expect should further resources be required.

**Comment by Yensan** [comment]
@AcademicAdmin @betatim 
I face with a same situation. I must deploy a jupyterHub server for many user, and they want environment be isolated(shell ENV, python virtual env, jupyter kernel process). What should I do?
