### ISSUE TITLE
using api tokens without logging in via web interface

### ISSUE THREAD

**Issue by benzipperer** [jupyterhub/jupyterhub#2266]
How do use generated API tokens to start a notebook server without first using PAM credentials to login via the web interface?

I successfully followed the instructions [here](https://github.com/jupyterhub/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges) to run jupyterhub through a new user rhea without root privileges. Users can log in an start notebooks successfully via the website at myserver:8000.

I am using Atom+Hydrogen to access notebooks via an API token. This API token was generated from the Control Panel -> Token -> "request new API token" pages after the user logs in at myserver:8000.

Using Atom+Hydrogen I can access notebooks fine this way.

However, after a restart of the server, the API tokens don't seem to work unless the user has already logged in using myserver:8000. [Here](https://jupyterhub.readthedocs.io/en/stable/reference/rest.html)it suggests that I add the API tokens to the config file in c.JupyterHub.api_tokens={}, but after doing that and running 
```
jupyterhub -f /etc/jupyterhub/jupyterhub_config.py --JupyterHub.spawner_class=sudospawner.SudoSpawner
```
I am still unable to use the API tokens unless a user has already logged in and spawned a server.

Do you have any suggestions?

**Comment by minrk** [comment]
An auth token created during startup can be used at any point

If API tokens stop working, that suggests that perhaps the jupyterhub database is getting cleared, so that auth tokens are deleted. Is there a chance that this is happening?

What happens when you create an auth token in the config file and then try to use it? Do you have logs of the failed requests and what the URLs are that are attempted?
