### ISSUE TITLE
Single use auth token

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterhub/jupyterhub#2280]
I have a requirement to generate a single use auth token for a user to log in on another device. I would like to be able to generate a url in a notebook which can be opened on a different device and will log me into Jupyter Hub on that device.

Is this something that could be possible?

**Comment by minrk** [comment]
Definitely possible. Authenticators can register additional tornado handlers via `def get_handlers(self, app)`. I would add an additional handler for creating and consuming one-time tokens, then you'll be able to request tokens via the API, and login with the resulting URL.

Here's how I'd do it today, without any support from JupyterHub:

- Authenticator stores hashes of one-time tokens and the users they correspond to
- POST request allows creating one-time tokens for the current user
- GET request implements the one-time login

[this gist](https://gist.github.com/minrk/fd80a2a1fb226d1af9b9e77669815a59) includes the implementation of the Authenticator and Handler, and a notebook that can be run in a Hub user's environment to request and share a link. The same approach can be used to implement the url request and link in a notebook server extension, or to provide the one-time links on a human-readable page instead of via an API.

My implementation stores the tokens in memory, which assumes the one-time links are short-lived and it's okay that they are reset on hub launches. If you want them to last, you'll need to put them in a database or some other storage.

**Comment by jacobtomlinson** [comment]
@minrk this is awesome! Many thanks for this!
