### ISSUE TITLE
More hooks

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#2288]
We currently have a mixture of overrideable methods (`Authenticator.pre_spawn_start`) and hooks which can be set via config (`c.Spawner.pre_spawn_hook`). Subclassing in config is intimidating for lots of folks, so I think we should try to take a systematic approach to adding hooks in at least the common places for deployment customization.

Current potential for hooks:

- normalize_username (currently a method)
- validate_username (currently a method)
- pre_spawn (have this)
- post_stop
- post_auth

others? pre/post counterparts like `pre_stop`, `post_spawn`? I can't necessarily think of a use for them, but maybe they should be defined for completeness?

Question about hooks:

1. should they be transforms (i.e. post_spawn takes the return of spawn and can transform it), or pure event listeners (cannot modify return value)? I can see the utility in transforms, but I can also see the potential complexity of allowing hooks to modify things like that
2. I had another one, but I forgot.

**Comment by katsar0v** [comment]
My ideas for hooks:
- pre / post login
- pre / post logout
- different hooks in services, e. g. service added / runned. Would help with implentation, just need one hook for example and code styling

**Comment by vpavlin** [comment]
@minrk I have a use case for `post_spawn` hook:) We run JupyterHub on OpenShift/Kubernetes and we run nbviewer as a second container in the singleuser pod to provide notebook sharing feature.

The problem is that for that we need a new (unauthenticated) route, so current solution is to poll proxy for routes and for each user create a second route. I would much prefer to drop polling and the `add_route` on `post_spawn` - as that is when I can get an IP of the pod to construct the route target.

Same for `post_stop` - removing the newly created route.

**Comment by manics** [comment]
We have `pre_spawn_hook` `auth_state_hook` `post_stop_hook`.
If there's a need for a new hook I think it makes sense to describe the requirements in a new dedicated issue.
