### ISSUE TITLE
Please Add Installation USER and DIRECTORY to docs

### ISSUE THREAD

**Issue by SeaDude** [jupyterhub/jupyterhub#2300]
Hello,
Will you add the recommended **user** (root, other) and **directory** (/root?, /opt/anaconda/bin?, other?)  to the [docs](https://jupyterhub.readthedocs.io/en/latest/quickstart.html#installation). The current docs skips these two CRITICAL items and results on the internet vary widely.

Please enhance the _Installation_, _Getting Started_ and/or _Quick Start_ docs to answer such questions as:
- Should JH be installed as root user or another user?
- Which directory should JH be installed in a multi-user environment?

I'm working through an installation right now. If you can provide answers to these questions, I will write the docs and PR.
Thank you

**Comment by SeaDude** [comment]
Hello @willingc. Thank you for the prompt and thorough response. 

**RE: New users:**
- I’m forced to use Azure for this first deployment. 

**RE: The File Location in “.../installation-basics.html”:**
- If installing JH via Anaconda, I don’t think the install locations in this link are followed. 

**RE: Root user install:**
- Is there a difference between _installing_ JH as root and _running_ it as root?

**Comment by minrk** [comment]
There are several answers to these questions, and they depend on the deployment context and most importantly which Spawners are being used.

I'll answer, assuming that you are using the default PAMAuthenticator and LocalProcessSpawner:

> Should JH be installed as root user or another user?

Generally, JupyterHub must be installed *for all users*. This may mean root, or it may mean an administrator account with write privileges to a shared environment. This is because the JupyterHub package is used both by the server process and all user processes. Root may be the simplest (e.g. `sudo python3 -m pip install jupyterhub` for the default system-wide Python 3 on most systems), but not the only answer.

> Which directory should JH be installed in a multi-user environment?

This is entirely up to you. The requirement with the default Spawner is that all users can run code in this environment (they do not need to have write access to the env, only read+execute). This could be `/usr/local` or `/opt/conda` or `/sys/jupyterhub-env`. JupyterHub is completely insensitive to this, the only thing it cares about is that the user running the Hub (may be root, or someone else, see the link @willingc shared above) and the users who will launch servers can run code in this env.

If I were to pick, I would use:

- `/opt/conda` for a shared system-wide conda install, or
- `/usr/local` to install jupyterhub in the default Python install of the system


These answers are different for different authenticator+spawner combinations. For instance, in the common OAuthenticator+DockerSpawner combination, the *only* requirement is that it is installed for a single user with permission to use docker, so this can be any single user in any path.

**Comment by SeaDude** [comment]
Ok. This information helps me and validates the choices I've made thus far:

- Install JupyterHub as `root`
- Install JupyterHub in `opt/anaconda`

The remaining steps are to actually get this installation working!. I keep hitting the same wall after installing JupyterHub using `conda`. I'm presented with the default nginx landing page and I can't find clear instructions for proceeding. 

[I've looked at and tried the instructions here](https://jupyterhub.readthedocs.io/en/stable/reference/config-proxy.html#nginx), but they don't seem to apply to[ my install ](https://github.com/SeaDude/Azure-JupyterHub)(SSL, Azure, etc.).
