### ISSUE TITLE
Integration: Getting an .ipynb (or other data) into JupyterLab/Jupyter Notebook tree

### ISSUE THREAD

**Issue by eode** [jupyterhub/jupyterhub#2350]
Hi!  I'm interested in integrating with JupyterLab.  We host various kinds of data -- one is `.ipynb` files.

We'd like a user to be able to click on a link which takes them to a pre-set Jupyter notebook tree/Jupyter lab instance.  Example of a reasonable workflow (though I imagine there may be better ways):

The core idea is nearly identical to `nbgitpuller`, but doesn't use git:
* A JupyterLab URL receives a remote URL from which JupyterLab downloads content
* Jupyterlab checks that the URL is from a permitted URL prefix, and if so, downloads the content.

**Comment by consideRatio** [comment]
@eode nbgitpuller can do this, but there is some struggle to open the actual notebook with jupyterlab after they introduced workspaces. https://github.com/jupyterhub/nbgitpuller

**Comment by eode** [comment]
Ah!  That is, indeed, quite similar to what I'm looking for.  However, the data we have is stored in S3, and we were more looking for something that wasn't limited to git, specifically.

..but, it's a general idea of where to go with it.  Good enough for me.  You can close this if it's not something that's considered a useful feature.

**Comment by consideRatio** [comment]
Ah, hmmm, depending on how JupyterHub is deployed, you may have various options because the file needs to be pulled to some storage, but this can be very different in between JupyterHubs

If you would use https://github.com/jupyterhub/zero-to-jupyterhub-k8s and hosting it on the cloud, you may want to utilize a post-startup hook configurable through the specific spawner for this deployment called KubeSpawner. For other spawners, perhaps another option would be suitable. There are hooks to run code after you have logged in for example.

**Comment by ryanlovett** [comment]
Perhaps [duplicati](/duplicati/duplicati)+[nbserverproxy](/jupyterhub/nbserverproxy) could get you part way there?

**Comment by eode** [comment]
Our main interest involves running on SageMaker.  I think (if sagemaker supports extensions) that we may need to write our own extension, or perhaps just handle the S3 download some other way, and then use the known location to create a URL referencing the notebook.

I'm leaving this open in case the core idea is useful (which it seems to me it would be).  If it doesn't seem useful to you, this can be closed.

Description updated.
