### ISSUE TITLE
Hub + Docker Volume causes users to swap home directories

### ISSUE THREAD

**Issue by rgerkin** [jupyterhub/jupyterhub#2378]
This is a weird one...

I have JupyterHub set up with GitHub OAuth, plus a whitelist of people in my research group.  It is running inside a Docker container, with all of the container's /home mounted from a Docker volume on my server.  

When I launch the container, the volume gets mounted so each user can keep their content of their home directory through container restarts.  However, the users don't exist yet, until Jupyter adds them by checking the whitelist and doing a bunch of adduser commands, e.g. `[I 2019-01-09 22:56:53.911 JupyterHub auth:547] Creating user: adduser -q --gecos '""' --disabled-password rgerkin`.  

Since the users don't exist yet, the system inside the container gives ownership of orphaned files to random UIDs (1001, 1002,  etc.), possibly in the order that it finds them, maybe alphabetical.  But that has no relation to the order of the usernames in the whitelist, who then get assigned UIDs in the order that they are encountered in the whitelist.  This means that ownership of /home/rgerkin ends up with some other user when the container is relaunched.  

This should be reproducible by launching a JupyterHub docker container with a docker volume mounted to /home, and using a whitelist so that users are created when JupyterHub is launched from inside the container.  

The obvious solution is for me not to use a volume to persist data in the container's /home directory, or adding other volumes, too (e.g. for /etc to persist /etc/passwd) but I'm not sure where this ends.  All I really want to do is let users keep their data through restarts.  Is there a way to allow UIDs to be specified in the whitelist, so that JupyterHub would run something like "adduser -u 1003 rgerkin" instead of each user getting a random UID?

**Comment by GeorgianaElena** [comment]
Hi @rgerkin! Thanks for reporting this and apologies for the very late response. Are you still experiencing this issue?

I don't believe this can be achieved using the whitelist. You mentioned that JupyterHub creates the system users, so I guess you're using [``LocalGitHubOAuthenticator``](https://github.com/jupyterhub/oauthenticator/blob/009ba47bf4e3e258cb8cb85c7146d04881abe067/oauthenticator/github.py#L198) with ``create_system_users = True``? If so, it's possible to configure the command used for creating users, i.e.  [``add_user_cmd``](https://jupyterhub.readthedocs.io/en/stable/api/auth.html#localauthenticator). However, since the command it's used on all the users, I'm not very sure this would help either.
If the whitelist isn't very large, maybe a possible solution would be to add the system users with the desired uid "by hand" before launching JupyterHub?

Hope this helps and sorry again for the late reply. 
(If you already have a working setup it would be really nice if could share it as it might help people with similar problems/questions.)

**Comment by rgerkin** [comment]
Thank for looking into this.  What I ended up doing is creating a script that iterates through all directories in `/home` and running `chown -R` on all those directories to the corresponding username.  This sort of works, since all users have all of their stuff at `/home/USERNAME`.  Of course, this can take some time if there are a lot of files.  

I like your idea of adding the users by hand before JupyterHub launches.  What is the best practice for running an arbitrary script before launch?  I can't just insert it in the Dockerfile since I am not rebuilding the container, just restarting it.  Is there a way to insert this into the actual jupyterhub startup command, maybe to put it into one of the .sh files that gets executed on startup (before users are created)?  I think I used to know what/where these where, but haven't had to tinker with setup in quite a while (which is a major success!)

**Comment by GeorgianaElena** [comment]
@rgerkin, I'm afraid I don't have enough experience to determine which is the best practice.
Maybe the discussion [here](https://github.com/jupyterhub/jupyterhub/issues/1219) which resulted in the creation of the [pre-spawn-hook](https://github.com/jupyterhub/jupyterhub/tree/master/examples/bootstrap-script) can provide some answers.
Also,  @minrk might know better if adding the users by hand is the best approach. What do you think, @minrk ?

**Comment by rgerkin** [comment]
`pre-spawn-hook` looks very useful, thank you!

**Comment by minrk** [comment]
If you are using containers (the Hub is in a container if I understand correctly) and the system users don't otherwise exist, then I suspect that you *don't* want to use the `Local*` variant and should just use `GitHubOAuthenticator`. In this event, the users will never exist on the system and all the users can have the same, default uid (or if you want to keep separate uids, you can customize the Authenticator and Spawner to pass a uid around that persists per-user).

So if you make sure that `/home/<username>` exists and is owned by e.g. uid 1000 (whatever the uid is in the user container) then mount the home directory as a volume, you should be set. This *won't* work if you want to mount `/home` as a volume instead, where you'd have to use.

[Here's an old example](https://github.com/minrk/jupyterhub-demo/blob/339208ec17a0169d3caa9289ecf05997018f00d0/jupyterhub_config.py#L18-L31) I used that does something similar (it mounts a `work` directory and overrides `start`, but the same approach should work with a pre-spawn-hook and home now).

The gist is to ensure the directory exists and has the right ownership on start.

**Comment by rgerkin** [comment]
@minrk How secure it that setup?  What prevents users (who are all on the same uid) from exploring everything else created by other users (who have the same uid).  Would I need to "customize the Authenticator and Spawner to pass a uid around that persists per-user)" to prevent this?

**Comment by chicocvenancio** [comment]
> @minrk How secure it that setup? What prevents users (who are all on the same uid) from exploring everything else created by other users (who have the same uid).
Docker should enforce the mountpoint chosen and only allow users to see their own folder. This is only as secure as Docker is, depending on your application it may be "secure enough".

>  Would I need to "customize the Authenticator and Spawner to pass a uid around that persists per-user)" to prevent this?
Only if you need additional layers of security.

**Comment by chicocvenancio** [comment]
> @minrk How secure it that setup? What prevents users (who are all on the same uid) from exploring everything else created by other users (who have the same uid).
Docker should enforce the mountpoint chosen and only allow users to see their own folder. This is only as secure as Docker is, depending on your application it may be "secure enough".

>  Would I need to "customize the Authenticator and Spawner to pass a uid around that persists per-user)" to prevent this?
Only if you need additional layers of security.

**Comment by rgerkin** [comment]
I think the solutions proposed above only apply to single-server conditions.  My deployment requires a multi-server hub inside a Docker container with mounted volumes.  I've proposed a solution in #2687, which is now working in my deployment.  From the perspective of the maintainer, it only requires that I periodically update the `uids` dictionary in the configuration file, which I can do programatically by parsing `/etc/passwd` (but that is beyond the scope of the PR).  

Longer-term I think a more correct solution would be to add a UID field to the User table of the DB.  Many authenticators may never use it, but it seems fundamental to the idea of a LocalAuthenticator because on a local system a UID and username are tied together.  The UID field should be filled if a user is added for the first time, and should be retrieved when the LocalAuthenticator adds users from the db, and used as part of the `adduser` command that the LocalAuthenticator calls.  I didn't take this route because I don't know how to setup a migration for your DB, and that seems like something that would require more review anyway.

**Comment by minrk** [comment]
closed by #2687
