### ISSUE TITLE
Logic for docker latest image?

### ISSUE THREAD

**Issue by 1kastner** [jupyterhub/jupyterhub#2412]
Hello there,

at https://hub.docker.com/r/jupyterhub/jupyterhub/tags I checked the jupyterhub versions.
The image `latest` was lastly updated 7 months ago but, the image `master` 6 days ago, the version `0.9.4` 5 months ago. So what exactly does `latest` mean in this context?

Thanks a lot in advance!

**Comment by williamstein** [comment]
Also, the latest Docker image is broken (notebook servers don't launch).  You have to get a bash prompt then do this to fix it:
```
umask 022
pip3 install notebook
```

It will then start working.

**Comment by 1kastner** [comment]
I used to use `0.9.4` and `0.9.1` and they do start fine (except both of them struggle with #2411).

**Comment by minrk** [comment]
`latest` should track latest stable, since latest is what folks will get if they don't specify a version. So `latest` will be updated again when 1.0 is released. I just checked and `latest` was only 0.9.1 instead of 0.9.4, so that's been fixed. I'll look into why it's not tracking properly.

If you are using docker, then the Hub image shouldn't have a whole lot to do with notebook servers not launching, since those should launch in a different image. Which image are you referring to @williamstein? #2411 also doesn't seem to have anything to do with the jupyterhub image.
