### ISSUE TITLE
 Can you implement user button level permissions?

### ISSUE THREAD

**Issue by zhengdayday** [jupyterhub/jupyterhub#2417]
Can you implement user button level permissions?

**Comment by consideRatio** [comment]
Hi @zhengdayday! I don't understand the question, can you add context or elaborate?

**Comment by zhengdayday** [comment]
@consideRatio  
For example, the user can only run the code but does not have permission to click the save button.

**Comment by zhengdayday** [comment]
@consideRatio 
The permissions of jupyterhub can only have different directory spaces for different users?
Does the user have permission for all click buttons?

**Comment by minrk** [comment]
It is not currently possible to limit permissions to specific parts of the single-user REST API as part of JupyterHub. If you want to prevent saving notebooks, you can do so with filesystem permissions and/or a custom ContentsManager that is read-only. filesystem permissions are much more likely to be robust, because it would also prevent the kernel from making the same changes that the REST API allows.

**Comment by zhengdayday** [comment]
Thanks
