### ISSUE TITLE
User privilege levels / admin access restrictions

### ISSUE THREAD

**Issue by vilhelmen** [jupyterhub/jupyterhub#2436]
Hi everyone, I've got my admin bugging me about basically a giant restructure of `admin_access` and I wanted to being it up and see what everyone thinks. The short version is either bolting on user permission levels or some sort of server access blacklist. The drive behind it is to create a firewall to prevent lower-privileged TA-like users who need access to student servers from system administrator accounts.

Off the top of my head, I was thinking either every user could have an `access_level` integer associated with the account, defaulting at zero, and users with a higher number get access to those with lower numbers (and maybe those in the same level?) which can give some fine-grained craziness, or just a group/user flag that completely disables admin access to that account.

Thoughts? Opinions? I can probably whip up a POC for whichever method we think is best.

**Comment by ellisonbg** [comment]
I think the right way of doing this is through OAuth scopes. I know @minrk had looked at that type of thing, but not sure of the status.

**Comment by vilhelmen** [comment]
That sounds like an interesting way to go about it, though OAuth is well outside my area of expertise. I'm all for jamming arbitrary `User` configuration in the authenticator, that I can do :)

Further discussion with our admin is starting to make it sound like a request for arbitrary group mappings for admin access (student set A can be accessed by faculty set B, etc).

We went from self-hosted to hosted in our uni's research computing group and, shocker, they're not a fan of the potential for basically unlogged privilege escalation from random TAs to system administrators.

It's mostly growing pains. I couldn't even hazard a guess at how large our staff has gotten over the last two years.

**Comment by minrk** [comment]
I believe scopes (#1057) and possibly roles (#2245) are the way to do this for us and I've done some prototyping, but haven't managed to put together something useful yet.

I think this is pretty well sketched out in those two Issues, but the gist is:

1. every action has an associated scope
2. a given token is associated with one or more scopes for taking actions on behalf of the associated  user or service, up to the maximum scopes for that user
3. roles are basically aliases for scope collections making it easier to separately say "Jamila is a TA" and "TAs can access user servers", etc. What's unclear a bit right now is if there's a need for role that's distinct from the existing concept of groups, or if group management is already enough to handle the "collection of users with certain permissions" idea, and we just need to add the permissions concept to groups.

But all of this means that the first step is assigning a scope to every action. If you'd like to continue #1057 to keep sketching out the possible scopes (perhaps going so far as to assign it to every URL), that would be a big help. I'd just start with not going too fine with the granularity, since that's hard to pull back from.

**Comment by minrk** [comment]
Is it okay if I close this in favor of the existing issues to keep the discussion from spreading out too much?

**Comment by vilhelmen** [comment]
That's fair. I'll start looking through the other issues!

**Comment by minrk** [comment]
Thanks!
