### ISSUE TITLE
Clearing spawn failure inside spawner 

### ISSUE THREAD

**Issue by robnagler** [jupyterhub/jupyterhub#2492]
**Describe the bug**

rsdockerspawner is a customer spawner that does automatic resource management. The only way I could figure out to return "no resources" was to [throw a 429](https://github.com/radiasoft/rsdockerspawner/blob/9fb308bddc255216aaa896b753b8d98dd2df670e/rsdockerspawner/rsdockerspawner.py#L464), but this is seen [as an error in user.py](https://github.com/jupyterhub/jupyterhub/blob/689a312756483db77b874115d829f93a9d6fb96b/jupyterhub/user.py#L616). 

There's no way to clear that error, which [ends up getting stored in base.py](https://github.com/jupyterhub/jupyterhub/blob/689a312756483db77b874115d829f93a9d6fb96b/jupyterhub/handlers/base.py#L835).

Also, the error message that is passed to `tornado.web.HTTPError` is not shown to the user, just the generic 429 Too Many Requests error.

While there is a link to the home page, it would be better to have a (big :) button that says "Try Again". People don't see the link.

**To Reproduce**

Login twice with different GitHub user names to http://alpha-jupyter.radiasoft.org. The garbage collector is set to a very short interval so it should produce the error.

**Expected behavior**

The spawner should be able to manage the resources in the spirit of [EAFP](https://en.wikipedia.org/wiki/EAFP). A 429 is a known exception for too few resources.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by minrk** [comment]
Big "Try again" link should definitely be there.

The protections against implicit spawn are there because requests to `/user/:name` used to do too many things:

- redirect to running server if running
- trigger spawn if not
- render progress if pending

The result was a problem if spawn failed because you could have:

- first visit triggers spawn
- refresh, second visit renders progress
- <spawn fails>
- refresh, spawn not pending, trigger spawn again (infinite respawn loop, user never sees an error)

1.0 changes this to be clearer, because there is no request that triggers an implicit spawn. The "try again" link should be to `/hub/spawn`, and this already exists if the server isn't running at all. In fact, this re-raise logic doesn't make sense in 1.0, but it's still there. We can remove it (#2494)

**Comment by robnagler** [comment]
Thanks @minrk! I see the big button in #2494.
