### ISSUE TITLE
Seem to be able to bypass auth to get to a running named server

### ISSUE THREAD

**Issue by rcthomas** [jupyterhub/jupyterhub#2529]
I have a custom UI with named servers selectable as buttons, running off master.  I've noticed that 

1. I can start up a named notebook server from the home page/console
2. Then go back to the hub (via the JupyterLab JupyterHub extension)
3. Close the JupyterLab tab
4. Click logout from the hub homepage

At this point, my server is still running, and I'm logged out.  If I then type in the URL to my server in my web browser, I get to it without stopping off to authenticate.  That's odd.  Further, If I use the Hub LabExtension to go to the console, then at _that_ point I am redirected to authenticate.

However, I can also do the following:

1. Start up a named notebook server from the home page
2. Open the JupyterLab JupyterHub window, and click "Logout" there
3. I'm redirected to the hub login page and appear to be logged out.

If I do that and try to type in the URL direct to my server, I am directed to authenticate.  That seems like what I expect to happen.

**Comment by minrk** [comment]
what browser are you using and how are you testing? I find that when I test with Safari Private Browsing, I can reproduce similar behavior because clearing cookies in one private tab doesn't clear session cookies in another private tab in the same window, so subsequent requests in the original tab are still sending the original cookies (effectively clicking logout in one tab doesn't logout the other tab). But when I use a normal window, no requests after logout are successful.

As for still being able to talk to the single-user server, the authentication can be *cached* there for a period of time before it asks jupyterhub again. latest jupyterhub adds a jupyterhub-session-id cookie, used to ensure that logout invalidates that cache immediately. If your single-user environment is not the same as the Hub environment, make sure that you are using latest jupyterhub in both environments.

**Comment by rcthomas** [comment]
This is Version 73.0.3683.103 (Official Build) (64-bit), and it's with a custom named servers UI.  I tried again with latest master, non-incognito, and had the same behavior as I reported originally.  I'll look into the environment mismatch as that is a potential source of the issue and update the ticket.  Time is catch as catch can right now...

**Comment by minrk** [comment]
I've followed the steps in Chrome as well, and get prompted for login each time. Since the ability to access a running server for a short time after logout is exactly what jupyterhub-session-id fixes (auth is cached for a few minutes before re-authorizing with the Hub), my suspicion is that the single-user server version is perhaps older.

Since you have custom named-server UI, does it use an API token to make the requests to spawn? If so, logout would not prevent spawns, since the requests would be authorized with a token instead of a cookie. Again, with the standard named-server UI in 1.0, I am prompted for login when I attempt to launch a new one.

**Comment by rcthomas** [comment]
We don't use an API token to make spawn requests from our UI, and I tested with matching JupyterHub versions on both the hub and the remote side and it still happened to me.  I am going to do a sanity check with a vanilla (non-custom home page) set up and compare what's going on. I'll update after that.

**Comment by mgresko** [comment]
I see something similar running 0.9.6.  Confirmed singleuser and hub are same version.  I can logout in the hub, singleuser notebook continues to run in container and I can replay a request to edit the contents of a txt file.

/user/testuser/api/contents/test.txt

I have confirmed that when I logout in hub the session is removed from database and cookie is removed from browser.  However, if I repeat my request with the same cookie (mitmweb) I am able to continue making requests for several minutes.  @minrk when did the jupyterhub-session-id fixes you mention get added?

**Comment by minrk** [comment]
I believe this turned out to be https://github.com/jupyterhub/jupyterhub/security/advisories/GHSA-cw7p-q79f-m2v7 where jupyterlab could set a token that would not get revoked on logout, causing singleuser cookies to persist after logout from the hub, fixed in 1.5.
