### ISSUE TITLE
subdomain_host and /hub path

### ISSUE THREAD

**Issue by rkdarst** [jupyterhub/jupyterhub#2530]
Hi,

This is a general question I've had for a while, and now seems like a good time to ask.

I have a hub I tried to set subdomain_host on.  This is the general flow:
a) jupyter.tld/hub/
b) jupyter.tld/hub/login/
c) $user.jupyter.tld/user/$user/
d) $user.jupyter.tld/hub/home   (happens if the user tries to go back to hub home.

The problem is once we get into state (d) here.  /hub/login will *only* work on the jupyter.tld (shibboleth at web server level, it's completely bound to only one domain).  And there's another thing: I want every path under /hub to be protected also at the web server level (passing some auth before the user can touch jupyter code, so it has to only use jupyter.tld because that's the way our auth works), but /user/ to be served on per-user domains.

Is this still the way things currently work?  Is there some way to:  normalize every path on "/hub" to use only jupyter.tld, and every path using /user/ to user.jupyter.tld ?  Will authentication cookies, etc. work this way?

**Comment by minrk** [comment]
d) *shouldn't* happen. If it does, that means we are putting the wrong URL in the link `/hub/home` instead of `jupyter.tld/hub/home`, or perhaps in a redirect somewhere. That would be a bug in the singleuser template rendering, I think, if it's in the link.

There is a reason that `$user.jupyter.tld` is served by the Hub, though, and that's to handle visitors to their own server when it's not running. Otherwise, it would be a less helpful 404 or 50X served by the proxy.
