### ISSUE TITLE
Pre 1.0 - /health, /healthz, or both?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#2532]
It seems to be very common that /healthz is used.

Currently, as seen by [a search](https://github.com/jupyterhub/jupyterhub/search?q=health&unscoped_q=health), JupyterHub is about to introduce a health-check in JupyterHub 1.0 at /health. __Should we make it at /healthz instead or perhaps support both?__

This is a description of the origin of /healthz: https://stackoverflow.com/questions/43380939/where-does-the-convention-of-using-healthz-for-application-health-checks-come-f

Related PR to CHP introducing /health proxy to the hub: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1004

**Comment by consideRatio** [comment]
Here is a screenshot from google cloud platform's youtube channel:

![image](https://user-images.githubusercontent.com/3837114/56434455-f08ef400-62d4-11e9-8852-1ada276424b3.png)

**Comment by consideRatio** [comment]
Here is a screenshot from the official kubernetes documentation:

![image](https://user-images.githubusercontent.com/3837114/56434598-875bb080-62d5-11e9-8797-c74902e27c85.png)

**Comment by consideRatio** [comment]
If we choose to support only one, I'd vote for that to be /healthz which seem to be more common at least in the k8s world and would solve some issues for using the GCE ingress controller with z2jh.

**Comment by minrk** [comment]
Following the links provided, I don't believe following Google's internal practices of 'z-pages' is necessary or beneficial. Since it needs to be explicit (nothing automatically discovers `/healthz` as far as I'm aware, so there's no benefit to `healthz` vs `health` vs `check` etc.), so we might as well use a descriptive name without a corporation's internal suffix, since we are in a url namespace over which we have complete control.

**Comment by minrk** [comment]
I realize no there's probably no reason to have a `/health` endpoint, since `/hub/api` works to serve the same purpose (a lightweight, non-authenticated handler). Maybe we should not have added `/health`.

**Comment by consideRatio** [comment]
@minrk GCE ingress controller discovers /healthz automatically, and require one for itself and not only for access by kubernetes kubelet. There is also another load balancer named ALB that im clueless about also does it apparently.

Since this convention is now part of k8s practices im thinking it is now more than a google practice even though it originated as such. K8s is the key player for container orchestration, and health checks etc are central to container orchestration, so deviating from their practice makes my mind crige a bit.

With that said, having a clear direction is often simply whats important, so whatever we settle for thats fine.

**Comment by consideRatio** [comment]
Background of my interest in this: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1136

**Comment by dhirschfeld** [comment]
The [k8s docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-http-request) do use `/healthz` as the liveness endpoint, but that's a configurable value which you could set to *anything* so I think that merely reflects a google bias inthe docs rather than an official k8s recommendation on what to name the endpoint.

In comparison the [AWS docs](https://eksworkshop.com/healthchecks/livenessprobe/) use `/health`and the an [openshift blog](https://developers.redhat.com/blog/2018/12/21/asp_dotnet_core_kubernetes_health_check_openshift/) uses `/health/live` and `/health/ready` respectively for liveness and readiness probes - I actually like that one the best.

The fact the GCE automatically discovers `/healthz` seems (unsurprisingly) to reflect the same google bias as the docs. If no other cloud providers automatically discover `/healthz` I'm not sure we should change our application to support the quirks of one particular implementation.

Obviously there's some benefit to having jupyterhub Just Work without additional configuration (even if only on GCE) so ` ¯\_(ツ)_/¯ `

**Comment by consideRatio** [comment]
Thank @dhirschfeld I'm feeling a lot more at ease not adhering to /healthz knowing it was not adopted wider than this.

**Comment by consideRatio** [comment]
Closing - Conclusion:
- The things that looks for a /health endpoint should read docs on what makes sense to probe and configure themselves to do so.

**Comment by manics** [comment]
> I realize no there's probably no reason to have a /health endpoint, since /hub/api works to serve the same purpose (a lightweight, non-authenticated handler). Maybe we should not have added /health.

@minrk I think it's still worth having an explicit endpoint like `/heath` for clarity, and also to support additional information in future. For example, as well as returning a http status you could return a JSON response on why the health check failed, e.g. Jupyter or k8s has run out of X resource, which would speed up problem solving.
