### ISSUE TITLE
Forward failed when user name in url is encoded.

### ISSUE THREAD

**Issue by Seanspt** [jupyterhub/jupyterhub#2547]
Recently, we are trying to use google [whatif tool](https://pair-code.github.io/what-if-tool/).
Users with escape characters in there user name are facing a 404 ERROR.

Whatif tool is requesting a url with escape characters in user names encoded. However, jupyterhub failed to decode it and forward the request.

Is there a way to configure jupyterhub to decode url? Or do we have to wait for the feature added?

**Comment by minrk** [comment]
Hm. JupyterHub has tests where usernames are escaped and they are working fine. Can you give an example that doesn't work and maybe a test environment?

**Comment by Seanspt** [comment]
The url got 404 is `http://172.0.32.227:8000/user/username%40oa.xx.xx/nbextensions/wit-widget/wit_jupyter.html`, which is the whatif tool by google. I'm trying out it's demo.

**Comment by minrk** [comment]
The equivalent routing of `username@oa.xx.xx` vs `username%40oa.xx.xx` is a tricky issue in CHP (https://github.com/jupyterhub/configurable-http-proxy/pull/163). We do have JupyterHub tests with `@` in the URL and normally this would not be escaped, so there is a bug in whatever is producing that URL, since it should have `@` not `%40`. Can you tell what produced this URL?

**Comment by Seanspt** [comment]
[whatif tool](https://github.com/tensorflow/tensorboard/tree/master/tensorboard/plugins/interactive_inference) produces the URL.
