### ISSUE TITLE
Kernel accountability 

### ISSUE THREAD

**Issue by rd5802** [jupyterhub/jupyterhub#2562]
For security, audit, and accountability, I want to have a functionality of storing code log executed by kernels spawned by JupyterHub (through notebook or script).

The log shoud contain at least:
user,
notebook/script path,
kernel path,
time
executed code
JupyterHub should also log commands executed in Jupyter terminal in a similar manner.

Can I alredy achieve this or JupyterHub needs new functionality?

I hope JupyterHub is the right place to ask this, if not please advise.

**Comment by ryogesh** [comment]
Here is an approach that may help you. Make changes as required e.g. adding debug levels...

1. redirect JupyterHub and the spawned notebooks to a common log.
e.g. Launch Hub 

nohup jupyterhub -f /etc/jupyterhub/jupyterhub_config.py 1>/etc/jupyterhub/jupyterhub.log 2>&1 &

2. the log file /etc/jupyterhub/jupyterhub.log  should be rw to all users.

3. Edit the kernel.json and add the logappenders for notebooks
e.g. "/opt/anaconda3/share/jupyter/kernels/python3/kernel.json" will look like 

{
 "argv": [
  "/opt/anaconda3/bin/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}",
  "--ZMQInteractiveShell.logappend=/etc/jupyterhub/jupyterhub.log",
  "--logappend=/etc/jupyterhub/jupyterhub.log"
 ],
 "display_name": "Python 3",
 "language": "python"
}

You can capture all users activities, script executed, timestamp.... Edit kernel.json to your need.

**Comment by vilhelmen** [comment]
That's a very interesting solution @ryogesh, I'll have to test that out on our servers. I went a different route and hijacked the kernel message handler and added the stream to the regular JH logs that then get sucked up into our logging framework. Here's the patch for the curious, I usually exclude it from [my general deployment stuff (which I need to resync sometime)](https://github.com/vilhelmen/jh-k8-etc) because it makes me a little uncomfortable:

```
diff --git a/notebook/services/kernels/handlers.py b/notebook/services/kernels/handlers.py
index cfef2a4a0..611fab048 100644
--- a/notebook/services/kernels/handlers.py
+++ b/notebook/services/kernels/handlers.py
@@ -329,6 +329,9 @@ class ZMQChannelsHandler(AuthenticatedZMQStreamHandler):
         channel = getattr(stream, 'channel', None)
         msg_type = msg['header']['msg_type']
 
+        if msg_type == 'execute_input':
+            self.log.critical("TRAK: %s", json.dumps({'who': msg['header']['username'], 'what': msg['content']['code'], 'where': self.session_manager.get_session(kernel_id=self.kernel_id)['path'], 'when': str(msg['header']['date'])}))
+
         if channel == 'iopub' and msg_type == 'status' and msg['content'].get('execution_state') == 'idle':
             # reset rate limit counter on status=idle,
             # to avoid 'Run All' hitting limits prematurely.
```

Though it seems to have issues reporting the user properly, in testing it always works fine but in prod it tends to return `unknown`


The terminal doesn't get logged, however. I tried a similar approach to the terminal handler and all I got was a **very** good keylogger which I very quickly trashed. [There are solutions for bash logging](https://askubuntu.com/a/93570), but I haven't dabbled with it since it's still so easy to escape. There probably isn't any good solution for the terminal, though, so that may be good enough. In fact, it's probably rather easy to escape kernel logging as well by just calling subprocess. But this should get the average user, at least.

**Comment by elgalu** [comment]
Has someone found a clean (maintained library) solution to be able to audit (using logs) all the commands run in Jupyter Notebook by users?

**Comment by manics** [comment]
I'm closing this since it's mostly related to the singleuser server, and we'd like to keep GitHub issues for relevant technical discussions. Please feel free to continue this discussion on the Community forum!
https://discourse.jupyter.org/
