### ISSUE TITLE
loop redirect

### ISSUE THREAD

**Issue by wqh17101** [jupyterhub/jupyterhub#2638]
![image](https://user-images.githubusercontent.com/26429138/61020073-135e0f80-a3cf-11e9-93cc-cde26849a1a6.png)

i set c.JupyterHub.port = 15000 c.JupyterHub.hub_port = 16000
but i got loop redirect when i visit 16000, and i can not visit 15000

**Comment by wqh17101** [comment]
and when i use netstat -an 
i find that it only setups port 16000, 15000 is not available

**Comment by GeorgianaElena** [comment]
Hi @wqh17101! Thanks for opening this issue.

``hub_port`` is the internal port for the Hub process behind the proxy. This shouldn't be accessed directly, because when you access it like this, you are bypassing the proxy and this is why it results in a redirect loop.
 
The public port to use when accessing jupyterhub is JupyterHub.port (the port on which the proxy will listen). From the logs, it seems that you have chose to run the proxy separately from the Hub. What command do you use to start the proxy?

**Comment by wqh17101** [comment]
i  did nothing except following this https://the-littlest-jupyterhub.readthedocs.io/en/latest/contributing/dev-setup.html#contributing-dev-setup

**Comment by wqh17101** [comment]
it is really weird that no matter what c.JupyterHub.port i set, it never started.  It seems that in the TLJH , this  c.JupyterHub.port parameter is useless. I dont know why it happened @GeorgianaElena

**Comment by wqh17101** [comment]
Maybe it is the problem of traefik? which is instead of the  configurable-http-proxy in TLJH. Also i dont konw why traefik is used in TLJH

**Comment by GeorgianaElena** [comment]
@wqh17101, if you follow the [instructions](https://the-littlest-jupyterhub.readthedocs.io/en/latest/contributing/dev-setup.html#contributing-dev-setup) without changing any defaults, are you able to access JupyterHub at http://localhost:12000?

On TLJH the default http port for the proxy is 80. You can change it using [``tljh-config``](http://tljh.jupyter.org/en/latest/topic/tljh-config.html#ports):
```
sudo tljh-config set http.port 15000
```
In the [Setting up Development Environment](https://the-littlest-jupyterhub.readthedocs.io/en/latest/contributing/dev-setup.html#contributing-dev-setup) tutorial, when you run the docker container with ``--publish 12000:80```, you're "mapping" port 80 (default proxy port ~ JupyterHub.port) inside the docker container to the 12000 port on your host machine.

My question is: do you want to be able to access JupyterHub on port 15000 in this development environment scenario? (if so, you should only change the mapping: 15000:80 and leave http.port with its default value) or do you want the proxy to run on 15000 inside the docker container (if so, you should use tljh-config and change it as described above and then map the proxy port to whichever port you are able to access JupyterHub on your local machine)? 
> Maybe it is the problem of traefik? which is instead of the configurable-http-proxy in TLJH. Also i dont konw why traefik is used in TLJH

Checkout [this blog post](https://blog.jupyter.org/introducing-traefikproxy-a-new-jupyterhub-proxy-based-on-traefik-4839e972faf6) to find out more about TraefikProxy and why it is used in TLJH :).

**Comment by GeorgianaElena** [comment]
Sorry, but I forgot to mention that after changing http.port, the configuration needs to be reloaded for the change to take place (sudo tljh-config reload proxy)

**Comment by wqh17101** [comment]
i want to visit jupyterhub on 15000 which is mapping in the docker 15000:15000，so what should i do

**Comment by wqh17101** [comment]
what i have done is modifying the c.JupyterHub.port of jupyterhub_config.py in the dir of tljh and run tljh-config reload hub , it doesnt work

**Comment by wqh17101** [comment]
It seems that i should 
```
1. modify the jupyterhub_config.py to set c.JupyterHub.port = 15000 or sudo tljh-config set http.port 15000
2. sudo tljh-config reload proxy
3.sudo tljh-config reload hub
```
Is that true? @GeorgianaElena

**Comment by wqh17101** [comment]
![image](https://user-images.githubusercontent.com/26429138/61758911-350cbd00-adf9-11e9-85ed-3de8aaf1dfb8.png)
i got this when i did the steps i guessed above.
i dont why

**Comment by GeorgianaElena** [comment]
@wqh17101, you need a new container and published it with the new mapping.

The steps are:
1.
```docker build -t tljh-systemd . -f integration-tests/Dockerfile```
2. 
```
docker run \
  --privileged \
  --detach \
  --name=tljh-dev-env \
  --publish 15000:15000 \
  --mount type=bind,source=$(pwd),target=/srv/src \
  tljh-systemd
```
**Note** that a new container with a new name (*tljh-dev-env* instead of *tljh-dev* in the tutorial) will be created and the port 15000 inside the container will be mapped to the port 15000 on your local machine.
3. ``docker exec -it tljh-dev-env /bin/bash``
4. ``python3 /srv/src/bootstrap/bootstrap.py --admin admin``
5. ``sudo tljh-config set http.port 15000``
6. ``sudo tljh-config reload proxy``
7. Now the proxy listens on 15000 **inside** the docker container and is also accessible **outside** on 15000. You should now be able to access JupyterHub on http://localhost:15000

**Comment by wqh17101** [comment]
Let me try. 
Here are some advice for TLJH.
1. i find that you check conda and traefik version which is a constant why not put the install script in the repo,and install from it .

**Comment by wqh17101** [comment]
Also where can i set the config file in tljh
![image](https://user-images.githubusercontent.com/26429138/61776481-afefcb00-ae2d-11e9-9400-da5d5d55326c.png)
this time it is ` /opt/tljh/hub/lib/python3.6/site-packages/tljh/jupyterhub_config.py`
last time it was `/srv/src/tljh/jupyterhub_config.py`

**Comment by GeorgianaElena** [comment]
Closing this issue and continue the discussion in TLJH (https://github.com/jupyterhub/the-littlest-jupyterhub/issues/397)
