### ISSUE TITLE
User whitelist question

### ISSUE THREAD

**Issue by whositwhatnow** [jupyterhub/jupyterhub#2686]
We are logging into to the jupyter hub using AD, i want to only allow users in groups to be able to login.  using the whitelist is asks for user names but I have a huge list and want to see if I can do any AD filtering or even create white list based on a file.  Is this possible???

## Whitelist of usernames that are allowed to log in.
#  
#  Use this with supported authenticators to restrict which users can log in.
#  This is an additional whitelist that further restricts users, beyond whatever
#  restrictions the authenticator has in place.
#  
#  If empty, does not perform any additional restriction.
#c.Authenticator.whitelist = set()

**Comment by ryogesh** [comment]
Assume you have the AD users file
1) users.lst file like below
set(("user1", "user2"))  or {"user1", "user2"}

2) You have the jupyterhub config file called jh.py with all config parameters except the user whitelist 

Use a command like below (feel free to play around with the shell command) to launch jupyterhub

 echo "`echo -n "c.Authenticator.whitelist = "` $(cat users.lst jh.py)"  > newjh.py ; jupyterhub -f newfl.py

**Comment by evanlinde** [comment]
I do this type of thing on my systems using pam rather than through JupyterHub. This also has the benefit of restricting all AD authentication to members of my designated group.

My AD setup uses winbind. In the pam config files, I add `require_membership_of=mygroup` to the winbind auth lines. (This may get tricky if you have to qualify the group name with your domain name.)

In CentOS 7, `/etc/pam.d/system-auth` and `/etc/pam.d/password-auth`, look for the line starting with `auth    sufficient    pam_winbind.so`. 

In Ubuntu, `/etc/pam.d/common-auth`, look for `auth    [success=1 default=ignore]      pam_winbind.so`.
