### ISSUE TITLE
Securing Jupyterhub: is it protected against CSWSH or CSRF attacks and other questions?

### ISSUE THREAD

**Issue by guillaumeeb** [jupyterhub/jupyterhub#2694]
_Disclaimer: I'm totally dumb when it comes to security, so sorry if this are obvious questions._

As an HPC Center admin, I want to open an already deployed Jupyterhub service (accessible from inside my organization) on Internet. After discussion with our Security team, they ask me to ensure that Jupyterhub is protected against [Cross-Site WebSocket Hijacking (CSWSH)](https://www.christian-schneider.net/CrossSiteWebSocketHijacking.html), typically done by implementing a CSRF Token. I could not find a reliable information about this in the documentation or github project, so can someone tell me if this is the case?

I've also been looking at https://jupyterhub.readthedocs.io/en/stable/reference/websecurity.html. I believe that we are in the case of semi trusted users, as our users connect to the Jupyterhub using an indentity stored in a LDAP server. Can you confirm this?

By taking a quick look at the following paragraphs:
- enable subdomains :not possible in my organization.
- disable user config, prevent spawner from evaluating shell configuration files,  isolate packages using virtualenv: not possible, I want my users to be able to customize their Jupyter notebooks at their will, which includes using their own singleuser-notebook!
- encrypt internal connexion with SSL/TLS: I need to check that BatchSpawner and ProfileSpawner are comaptible with this.

Thanks in advance!

**Comment by ryogesh** [comment]
Few thoughts:

Additional Information on notebook security:
https://jupyter-notebook.readthedocs.io/en/stable/security.html
https://jupyter-notebook.readthedocs.io/en/latest/public_server.html#notebook-server-security
https://blog.jupyter.org/public-notebooks-and-security-3058c433c884
https://blog.jupyter.org/tagged/security

TLS is a must. 

Port restriction/firewall is recommended

LDAP/AD authentication is a good option (semi-trusted). Group based restrictions is also recommendation.
i.e. c.LDAPAuthenticator.allowed_groups = ["CN=...", "CN=..."]

For semi trusted users, docker container(dockerspawner) provides good isolation/resource mgmt. May meet your security requirements without calling for subdomains.

**Comment by guillaumeeb** [comment]
Thanks for this first answer. About the CRSF Token implementation in Jupyterhub, I can only easily find https://github.com/jupyterhub/jupyterhub/issues/1673 which seems to indicate a CRSF Token option is available, but I couldn't find it. Is it always activated?

cc @minrk who seems the most pertinent person about this.

**Comment by minrk** [comment]
Thanks for asking! Indeed, JupyterHub should be protected against CSRF/CSWSH and uses CSRF tokens where appropriate (please report any CSRF vulnerabilities found to security@ipython.org). Attacks from outside the Hub should be prevented by default.

The "semi-trusted user" concept is about the fact that auth is enforced *in single-user servers*, which means that if users have permission to modify the Python environment their own server launches in, they can attack *each other* by modifying the web server where the notebook server is expected to run, because CSRF protections do not apply within a single domain (it's not cross-site anymore). JupyterHub makes some effort to prevent even this, but I do not believe it is possible to rigorously protect against CSRF-style attacks between two services *actually in the same site*, e.g. `host.tld/user/alice` -> `host.tld/user/bob`. That's why the subdomain path exists, though it is rarely used. This internal-csrf attack requires:

1. attacker is a real user (or compromises a real user to the point of running arbitrary code as them)
2. attacker modifies their notebook server to serve unauthenticated pages with CSRF attacks instead of (or in addition to) the traditional notebook server
3. attacker creates and shares a malicious link with another user, the target
4. target receives and follows the malicious link

This is an otherwise normal CSRF attack (steps 3-4), but the "attack must come from within the building," i.e. a page served by JupyterHub itself, which bypasses *some* CSRF protections by starting from the same domain. This is where the semi-trusted user comes in - if such an attack occurs, it should be easy to identify the user (or compromised user) who is the source of the attack, and you have institutional recourses available (revoked accounts, etc.).


To clarify some of the points:

- using subdomains allows users to compromise their own servers without opening an avenue for these "internal" CSRF-style attacks against other users, since from one user's server to another's is truly "cross-site" and all the real CSRF protections take full effect.
- disabling user config makes it so that user servers cannot be compromised by conventional means, so ought to be enough to accomplish the same goal, but doesn't eliminate the kinds of attacks a single user can make against other processes run as the same user, which could be used in theory by advanced malicious users to modify their own notebook server (I don't personally know any way to do this, but I would not say that it is impossible).
- encrypting internal communication is indeed a great thing to do! It should work with BatchSpawner already, as long as you're running on a shared filesystem, which I assume you are on a traditional cluster. This isn't related to CSRF issues, but rather network sniffing to steal tokens, which ought to already require elevated permissions. But still a good thing to do now that it's available.

**Comment by guillaumeeb** [comment]
Thanks a lot for the clarifications!
