### ISSUE TITLE
Pure python configurable proxy?

### ISSUE THREAD

**Issue by mangecoeur** [jupyterhub/jupyterhub#2741]
Would it make sense to have a pure python "native" proxy built into jupyterhub as the defauly proxy implementation? Since we are anyway running an async tornado server, IMO having a (very basic) built in proxy would handle small scale installs just fine while simplifying overall development and deployment (no need to juggle two services in two languages).

Looking at this (abandoned) tornado http proxy implementation (https://github.com/senko/tornado-proxy/) it seems surprisingly simple (main implementation https://github.com/senko/tornado-proxy/blob/master/tornado_proxy/proxy.py).

Personally, I install/manage jupyterhub "the hard way" (manual source install on bare metal server), and the nodejs based proxy honestly seems like a bit of a hack.

**Comment by minrk** [comment]
Rather than implementing another proxy in Python, we are mainly switching over to using [traefik](https://jupyterhub-traefik-proxy.readthedocs.io/en/latest/). This is already being used in the-littlest-jupyterhub. It should at least solve the installation issue, since it's a single binary.

The advantages of using CHP and traefik over writing and maintaining our own http proxy from scratch - we don't have to write a proxy, we only have to make it *configurable*. Adding writing a complete proxy (properly implementing the proxy protocol, etc.) to the scope of this project is not something I think we should do.
