### ISSUE TITLE
Bootstrap should have ssl_verify=False option

### ISSUE THREAD

**Issue by icmtf** [jupyterhub/jupyterhub#2748]
I just literally can't install TLJH because of :
`requests.exceptions.SSLError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /miniconda/Miniconda3-4.5.4-Linux-x86_64.sh (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))`

Why there's no extra argument to ignore SSL errors?

**Comment by icmtf** [comment]
Hi minrk!

Thank you for your response.

I would love to set up TLJH on our Dev Team Ubuntu 18 LTS but unfortunately we're behind proxy that does the SSL handshake and it's impossible to install anything that does not allow skipping for SSL verification. 

pip.conf is bloated with 'trusted-host = xxx', git config, vagrant etc... All of them are set to ignore SSL errors else I wouldn't be able to install anything cause... You know - Company security, proxy and its SSL handshake, ***sigh***

**Comment by minrk** [comment]
Always nice when company security requires disabling major security features! Does it use a self-signed SSL cert?

It would be ideal to trust the proxy explicitly, rather than skipping verification globally. Does [this trick](https://bugs.python.org/msg242782) work?

```bash
openssl s_client -connect host:443 | openssl x509 > /path/to/selfsigned.pem
export SSL_CERT_FILE=/path/to/selfsigned.pem
export REQUESTS_CA_BUNDLE=$SSL_CERT_FILE
# ...
```

or perhaps [trusting your company CA globally](https://superuser.com/questions/437330/how-do-you-add-a-certificate-authority-ca-to-ubuntu)?
