### ISSUE TITLE
Can users without Local UNIX accounts have access to the Jupyterhub Notebooks if they reside in UINX server?

### ISSUE THREAD

**Issue by ernie6968** [jupyterhub/jupyterhub#2760]
Can users without Local UNIX accounts have access to the Jupyterhub Notebooks if they will reside in UNIX servers?

**Comment by joelion** [comment]
Speaking from experience (_not_ authoritatively), I tried to log into a Hub recently on a colleague's server, on which I didn't have an account, and it the server was not able to spawn because the Hub's config required a home directory for the user account. I could log into the Hub fine, but the hub was unable to spawn a server, showing this error. 
![image](https://user-images.githubusercontent.com/5199709/66161442-83082300-e5e9-11e9-9f9e-0fdee60925f9.png)

After he created an account for me, I was able to log in and spawn a server.

**Comment by ryogesh** [comment]
local unix account is not a must.
You can have JupyterHub authentication against SSSD or LDAP or OAUTH and then launch containers (dockerspawner)

**Comment by ernie6968** [comment]
> local unix account is not a must.
> You can have JupyterHub authentication against SSSD or LDAP or OAUTH and then launch containers (dockerspawner)

Hello ryogesh, users can login successfully but cant launch their servers to see the notebooks, do you have any documentation on how to setup the dockerspwner? 

Thanks!

**Comment by ernie6968** [comment]
Hello @willingc , could it be possible for users that do not have local UNIX accounts, but say they have Active Directory accounts, can connect to the JupyterHub UI and access the server to see the Notebooks?

**Comment by ryogesh** [comment]
@ernie6968 

LDAPAuthenticator documentation has information on configuring users against LDAP/AD.
https://github.com/jupyterhub/ldapauthenticator

Dockerspawner documentation provides information on the setup
https://github.com/jupyterhub/dockerspawner#dockerspawner 

You can work with the available docker containers (singleuser is the default) or create your own container and specify the image as a config item.
