### ISSUE TITLE
Some Docker hub image release tags point to dev builds

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyterhub#2848]
https://hub.docker.com/r/jupyterhub/jupyterhub/tags
![jupyterhub-dockerhub-tags](https://user-images.githubusercontent.com/1644105/70668517-b90df700-1c6b-11ea-8860-41cfbae8676f.png)

I'd expect Docker image tags like `latest` and `1.0` to point to a corresponding stable release, but it looks like those two are pointing to a dev build.

**Comment by bitnik** [comment]
related: https://github.com/jupyterhub/jupyterhub/issues/2852

**Comment by willingc** [comment]
Closing this issue as it's been several months. Please feel free to ask on the [discourse site](https://discourse.jupyter.org/c/jupyterhub/10) or request that we reopen this issue. Thanks! 🌻

**Comment by manics** [comment]
I'm reopening this, it's very misleading as tags do not always match a release.

In some ways it's even worse: for example we now have a 1.2 tag even though JupyterHub is only on 1.1.0!
https://hub.docker.com/layers/jupyterhub/jupyterhub/1.2/images/sha256-caeee1788998dcf8ab25ba5cd97313941075571c86445a843ec8bc9cc09f2b32?context=explore
![image](https://user-images.githubusercontent.com/1644105/77835848-ced6f780-7148-11ea-8a58-faad3391bc1a.png)

**Comment by MonksterFX** [comment]
Same problem. With the current taging it is not possible to decide what is a stable version. So if i use a 1.1 I want to see a stable 1.1 build. There are errors which where closed before. So something must be mixed up in the pipeline. It is very hard to deploy you docker containers if they get changed all the time and stop working.

**Comment by consideRatio** [comment]
I'm fairly confident this is caused by docker cloud build hooks as defined in [hooks](https://github.com/jupyterhub/jupyterhub/tree/master/hooks) and [singleuser/hooks](https://github.com/jupyterhub/jupyterhub/tree/master/singleuser/hooks).

I've worked too much with bash during my work hours to survive additional bashing! What causes the problem is our tagging and pushing of docker images in the hooks I'm almost certain of. I guess part of the issue is that they trigger on all pushes instead of only triggering on git tag pushes.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/404-error-on-notebook-startup/6514/2

**Comment by manics** [comment]
This was fixed by moving to GitHub Workflows instead of a Docker Hub automated build
