### ISSUE TITLE
auth_state hook fires too late; it should go before options form generation

### ISSUE THREAD

**Issue by athornton** [jupyterhub/jupyterhub#2860]
**Describe the bug**

The placement of the auth_state hook in Spawner is later than it should be.  The auth_state is known when the options form is generated, and you might want to generate a different options form depending on the stuff in auth_state, e.g. users in different groups might get offered different container sizes or images.

Currently I'm having to make get_options_form a coroutine so it can call `yield self.user.get_auth_state()` and that seems silly, because all the stuff I am doing there is really stuff that belongs in the auth_state hook.

**To Reproduce**

Uh, I don't know an easier way to do it than to make an options form that depends on user auth_state, and then show that if you set that in auth_state_hook it isn't present in the options form.

**Compute Information**
 - Centos 7
 - JupyterHub master (as of 20 Dec. 2019)

**Comment by rcthomas** [comment]
Hi @athornton I put the hook in (#2552 and #2555) where I needed it, but it would be great if we could figure out the right place to put it to serve everyone's needs.  We've got named servers as part of our set up, and to let users pick a server we've turned on the setting that sends them to the home/console template instead of redirecting immediately to start the spawn (e.g. options form).  So I get why you're saying it comes "too late" but it works for my set up.

Does this just need to get pushed down in to base handler stuff?  If you look at #2555 you'll see all kinds of existential thrashing about whether there were any ideas where it should actually go...

**Comment by rcthomas** [comment]
I should say the reason it's there at all is because of exactly what you're looking for too.  Some kind of role-based or group-based customization of the interface.  It just "feels like" auth state is the place for this but I think that's just because there's no such other place for it...!

**Comment by consideRatio** [comment]
Thanks @athornton for reporting this along with your insights and context! :heart:
