### ISSUE TITLE
how to use in classroom for assignments and automatic grading

### ISSUE THREAD

**Issue by arademaker** [jupyterhub/jupyterhub#2908]
Where can I find the intructions on the use of jupyterhub in classroom? How to create assignments, auto grade the submissions using test cases etc.

**Comment by manics** [comment]
Have you come across nbgrader? https://nbgrader.readthedocs.io/en/stable/

Since this is quite a general question you might get a better response on the community forum https://discourse.jupyter.org/

**Comment by willingc** [comment]
Hi there 👋!

Can we move this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

Thanks!
