### ISSUE TITLE
JupyterHub Failed to shuddown the user's notebook after the notebook being in active for some time

### ISSUE THREAD

**Issue by huyunhaode** [jupyterhub/jupyterhub#2945]
I have configured the c.NotebookApp.shutdown_no_activity_timeout = 5*60.The doc show that the time unit is second.and after 5minutes, the user's server isn't shutdown

**Comment by minrk** [comment]
This could be due to a number of factors. Is there a chance that there was a browser tab opened pointing to the server? In some cases, this can cause activity to be registered as there are active connections. The culling can be tuned to take this kind of activity into account or not, but the default is fairly conservative to avoid losing possibly active sessions.
