### ISSUE TITLE
Ease JupyterLab usage with c.Spawner.jupyterlab = True

### ISSUE THREAD

**Issue by echarles** [jupyterhub/jupyterhub#2984]
Taken from discussion on https://github.com/jupyterhub/jupyterhub/pull/2980 as defined by @minrk 

We should have a way to enable jupyterlab properly to jupyterhub code, wherever that might be, rather than the passthroughs to the underlying code that we have now. That can mean modifying the launch command / class instantiated / default url or other things, as jupyterlab evolves.

The proposed config for that is `c.Spawner.jupyterlab = True`

**Comment by blink1073** [comment]
Brain dump of thoughts:

- Today users can use `c.Spawner.default_url = '/lab'` to use JupyterLab in JupyterHub because JupyterLab is also using `NotebookApp`.
- If we were to instead switch to `ExtensionApp`, JupyterHub users would currently have no way to run JupyterHub.  
- We can't just provide an alternative in JupyterLab repos, existing documentation in JupyterHub would be out of date.

Proposal
- Update JupyterHub docs with instructions on how to use JupyterHub with JupyterLab 3.0
- Release JupyterLab 3.0 with its own `singleuser` entry point based on Jupyter Serever
- Add the `singleuser` entrypoint to `JupyterHub` and enable with `c.Spawner.jupyterlab = True`.
- After the classic notebook is fully sun-setted, make `c.Spawner.jupyterlab` true by default

**Comment by robnagler** [comment]
I don't think Spawner needs to know about JupyterLab or cascade arguments in the above scenario.

JupyterLab's `singleuser` entry point would simply pass the right configuration to whatever it calls to start Jupyter Server. The only reason for `c.Spawner.default_url` is so that Spawner passes that argument to `jupyterhub-singleuser`. This would avoid unnecessary coupling between Spawner and JupyterLab.

If you could fix the name, e.g. `jupyterlab-singleuser` in advance, then the JupyterHub Docker images (or at least RadiaSoft's) could be built with introspection to know when `jupyterlab-singleuser` is available and should be used.

**Comment by blink1073** [comment]
@choldgraf are you familiar with this space?  I'd like to have a coherent strategy in place for JupyterHub deployments with JupyterLab 3.0.

**Comment by consideRatio** [comment]
## Quick summary of my readup
I needed to catch up a bit to understand what kind of breaking change is coming up in JupyterLab 3.0, and from [this issue about the JL 3.0 release](https://github.com/jupyterlab/jupyterlab/issues/8038) I conclude that the key breaking change coming up is that JupyterLab is about to stop relying on NotebookApp part of [jupyter/notebook](https://github.com/jupyter/notebook). This transition is represented by https://github.com/jupyterlab/jupyterlab/pull/7416.

Currently, when we install JupyterHub, there is also additional scripts automatically installed [as defined in setup.py](https://github.com/jupyterhub/jupyterhub/blob/42adb441535e438001d5953f7a8c805008a95534/setup.py#L114-L118). `jupyterhub-singleuser` is typically the startup script for individual servers, but as can seen [here](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser.py#L219) it is currently coupled with NotebookApp.

I'm not able to draw clear conclusions from this though but I hope it could help to have summarized.

**Comment by manics** [comment]
Another thought (no idea how practical this is): all notebook apps implement a python entrypoint, so the JupyterHub config becomes `c.spawner.jupyterapp = appname`. This avoids having JupyterLab as a special case.

**Comment by blink1073** [comment]
Thanks @consideRatio for the summary!

I agree with @manics that we probably want a more generic way to handle this.

**Comment by jtpio** [comment]
There is also this PR to add support for Jupyter Server: https://github.com/jupyterhub/jupyterhub/pull/2601

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyterhub-docs-with-instructions-on-how-to-use-jupyterhub-with-jupyterlab-3-0/8059/1

**Comment by manics** [comment]
JupyterLab (or more technically jupyter-server) is the default in 2.0.0
