### ISSUE TITLE
Jupyterhub server setup with native

### ISSUE THREAD

**Issue by sudi007** [jupyterhub/jupyterhub#2988]
can anyboy help with the following question i am setting up jupyterhub server for the firts time and need some help am having couple of issues i am trying to setup jupyterhub server on redhat linux with NativeAuthenticator in the jupyterconfig.py file but when i run the jupyterhub it allows me to create a username and password but when i try to log in it does not log in and even when i try to log in with root user , the other thing is am not able to access the admin page to authorize the user can anybody please guide me on how would i go about fixing the issue
Thanks

**Comment by betatim** [comment]
Hi there 👋!

Can we move this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

Thanks!

**Comment by sudi007** [comment]
yes you can thanks

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/setup-jupyterhub-setup-with-nativeauthenticator/3652/2

**Comment by sudi007** [comment]
Hello meeseeksmachine

Thanks for the insight was able to get that resolved the issue but am still having an issue with when i authorize the user and login with that user name i get and error
500 : Internal Server Error

Error in Authenticator.pre_spawn_start: KeyError “getpwnam(): name not found: ‘admin’”

You can try restarting your server from the home page.

**Comment by willingc** [comment]
Closing this issue. Please discuss this on the JupyterHub discourse site.

> Can we move this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the different discussion places and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)
