### ISSUE TITLE
Update Issue Template for Technical Support

### ISSUE THREAD

**Issue by willingc** [jupyterhub/jupyterhub#2996]
When triaging issues this weekend, I was thinking that we may want to start encouraging those seeking tech support (installation help; configuration troubleshooting) to post on Discourse. This increases the likelihood that the user gets greater visibility of their question by other JupyterHub users.

This is our existing template: 
https://github.com/jupyterhub/jupyterhub/blob/master/.github/ISSUE_TEMPLATE/installation-and-configuration-issues.md

I used @betatim's suggested text to respond to a few issues this weekend.

cc/ @GeorgianaElena @choldgraf @betatim

**Comment by manics** [comment]
👍  from me. I think it would be good if all maintainers agreed on this as a general policy though. Currently sometimes we push people who open support issues on one of the JupyterHub repos to Discourse, other times we don't, and this inconsistency can make it difficult to encourage people to Discourse. Perhaps this should be a https://github.com/jupyterhub/team-compass/ issue?

**Comment by willingc** [comment]
Sure @manics that makes sense for issues that are opened. The intent of updating the Issue Template is to guide the user prior to filing any support issues.

**Comment by choldgraf** [comment]
I like the idea - anything that we can do to make it easier for people to know where to ask certain kinds of questions is a 👍 from me.

Are you suggesting to change the template text in the link?

**Comment by manics** [comment]
The Z2JH template is a bit more assertive in directing people to Discourse: https://raw.githubusercontent.com/jupyterhub/zero-to-jupyterhub-k8s/master/.github/ISSUE_TEMPLATE.md

Though I'm not so much bothered by the wording as knowing how we should respond. For example sometimes I feel uncomfortable about answering an issue by telling people to go to Discourse because other support issues are still active, and it seems unfair that some people can get a response on support issues here but not others.

**Comment by willingc** [comment]
@manics I would use the more assertive template and make it consistent with the other repo.

Hopefully, the discomfort is temporary. Historically we let folks ask support and config questions on the repo since the project was evolving and we had far fewer users. 

One thing that we could do to minimize the discomfort of telling people to go to Discourse would be to have a bot that posts the message to the issue and closes it whenever we triage it with Technical Support.

**Comment by GeorgianaElena** [comment]
I like the idea too :+1: 
Summarizing everybody's thoughts, what do you think of this workflow:
* Use an assertive issue template that instructs people to ask the question on Discourse (in all of our repos).
* If people still ask for tech support here, have a bot that closes the issue and reiterates the message in the template.
* Let everybody know about this and make it a general policy for all maintainers. This way we'll give everybody the same chance of getting an answer on Discourse.

I will gladly work on this :rabbit:, once I get my internet back. 
(There were 3 days with strong winds and snow in south Romania :cry:, so no internet for >32h, sometimes no power either and the mobile network is working poorly. I'm extremely sorry for being so slow to respond.)

**Comment by manics** [comment]
Sounds fine to me!

Just to clarify, my slight discomfort was due to inconsistency in how different team members respond, which can give the appearance that some people are treated specially in receiving an answer in issues whilst others aren't. If everyone's agreed with @GeorgianaElena's third point (`Let everybody know about this and make it a general policy for all maintainers. ...`) I don't think a bot is strictly necessary, though there's certianly no harm in having one especially if it's easy to setup.

**Comment by betatim** [comment]
I am in favour of this change!

In repo2docker we have a template for "support issues" that sends people to discourse: https://github.com/jupyter/repo2docker/blob/master/.github/ISSUE_TEMPLATE/support-question.md Because we have several issue template the user has to make a choice while opening an issue and gets a specific message about support.

This is what you see when you click "New issue" on repo2docker:
<img width="1007" alt="Screenshot 2020-03-26 at 12 37 11" src="https://user-images.githubusercontent.com/1448859/77642806-8bb93080-6f5e-11ea-9566-f950fa88157b.png">

On some repo somewhere in GitHub I saw the same screen when opening a new issue but there wasn't even a green button for "support". It was a direct link to their forum. I will try and find that repo again to see how they did that.

**Comment by betatim** [comment]
On the inconsistency front: I agree that it isn't good to decide case by case. It creates the impression that there are exceptions and of course everyone thinks they are an exception :). 

I think once we have an issue template on all the repos and get word out that we have this (I didn't know that we have this for some of the repos that do!) then we can be strict with people. I mgiht have tried to deal with a support question then and there if it appeared to be short instead of redirecting them. Also because it wasn't clear if the repo had a policy or not (mostly because I didn't bother to check). So I think getting the word out should get a higher priority than building a bot.

1. make an issue template that we reuse across repos
1. get the word out to maintainers
1. standard snippet for those that open an issue anyway. Agreement on whether to also close these issues?
1. Try and deal with existing support threads to get them closed so we reduce the "two class" system

What do you think?

**Comment by GeorgianaElena** [comment]
> On some repo somewhere in GitHub I saw the same screen when opening a new issue but there wasn't even a green button for "support". It was a direct link to their forum. I will try and find that repo again to see how they did that.

@betatim, can [`contact_links`](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) be what you saw and what we need?
Unfortunately there isn't a visual example of it.

**Comment by GeorgianaElena** [comment]
What do people think of something like this: https://github.com/GeorgianaElena/jupyterhub/issues/new/choose?

**Comment by manics** [comment]
👍 
What do you think about treating `Uncommon situation. Not sure what to do.` through discourse or gitter and reduce the options to four? I suspect too many options means people will default to "Not sure what to do" 😀

**Comment by choldgraf** [comment]
I love it the options! Agree with @manics about not having too many options. I'd even be a fan of removing both the "gitter" and "discourse" options, and then just having the "not sure what to do" one link to Discourse...

**Comment by GeorgianaElena** [comment]
Great ideas @manics and @choldgraf.
I will open a PR soon and see where it goes :sunny:

I was also thinking of opening an issue in `team-compass` to remember us adding this issue template (once we all agree to one and merge it here) to the standard building blocks @consideRatio started :yellow_heart:. I believe this will help with ensuring consistency. What do you think?

**Comment by manics** [comment]
Definitely have something in team-compass. Arguably this whole issue could go there since we're discussing all JupyterHub repos 😀

**Comment by GeorgianaElena** [comment]
Closed by https://github.com/jupyterhub/jupyterhub/pull/3001.

**Comment by choldgraf** [comment]
Great! Thanks @GeorgianaElena ✨
