### ISSUE TITLE
allow specifying location for jupyter-proxy.pid

### ISSUE THREAD

**Issue by atpage** [jupyterhub/jupyterhub#3004]
### Proposed change

`jupyterhub_config.py` currently supports specifying a PID file location for the `jupyterhub` binary, using the `c.JupyterHub.pid_file` setting.

However, there is no option to give a PID file location for the `configurable-http-proxy`, which writes its PID to `/jupyterhub-proxy.pid`.

I propose adding a setting such as `c.JupyterHub.proxy_pid_file`, which would be passed to the proxy on instantiation.

This idea is based on [this bug report](https://github.com/jupyterhub/jupyterhub/issues/2859), which was actually caused by a misunderstanding of the existing setting (which works correctly as far as I can tell).

### How much effort will adding it take?

I think this would be a trivial addition for someone who knows the codebase.  It looks like the proxy already has a parameter for PID file location.

**Comment by milliams** [comment]
I was just hitting this same issue. It turns out that you _can_ set the PID file with:

```python
c.ConfigurableHTTPProxy.pid_file = "/var/run/jupyterhub-proxy.pid"
```

That said, the default being what it is (`"jupyterhub-proxy.pid"`) will often break things (assuming a valid working directory for a daemon is brittle). This setting should also probably be put in the default-generated config file so that it is discoverable.

**Comment by atpage** [comment]
Good find, thanks!

**Comment by GeorgianaElena** [comment]
Closing this as it seems that the issue was solved :sunflower:

Please feel free to reopen this if there are any other questions about it, or post on  http://discourse.jupyter.org/ forum for any other questions (we use GitHub issues for specific discussions related to changing a repository's content, and let the forum be where we can more generally help and inspire each other).

Thanks :sunny:
