### ISSUE TITLE
Display resource availability on home page

### ISSUE THREAD

**Issue by gabber12** [jupyterhub/jupyterhub#3043]
### Proposed change
When using cluster spawners like kubernetes or mesoss, there is a limit to how many notebooks can be spawned limited by cpu and memory limits. It would be helpful to display the cluster resource on homepage.

### Alternative options
Alternative options would require users to have access to cluster admin pages listing resources.

### How much effort will adding it take?
The feature would require spawners to extend functionality used to display this information and ability to display this info on homepage

### Who can do this work?
I would be happy to add this functionality. Would require some direction on best way to achieve this though.

**Comment by gabber12** [comment]
Is this in the scope of jupyterhub?

**Comment by manics** [comment]
It sounds useful, but it also sounds tricky to implement since it involves extending Spawners which are designed for very different environments, here's a few of them: https://github.com/jupyterhub/jupyterhub/wiki/Spawners

 For instance:
- Kubernetes lets you define requests and limits for pods, but would the admin page display actual usage, or total resources assuming all pods used their full quota?
- How does this work with cluster autoscaling, or a HCS cluster?
- Does the spawner require additional permissions to query cluster usage?

At the moment mybinder.org provides a public Grafana https://grafana.mybinder.org/. JupyterHub already exposes Prometheus metrics: https://discourse.jupyter.org/t/how-can-prometheus-scrape-metrics-from-jupyterhub/2662

I'm wondering if embedding an existing dashboard/panel on the JupyterHub home page would be easier than adding a new API endpoint to spawners?

**Comment by gabber12** [comment]
I believe in the current ecosystem this could be solved by using  **Service** + **extending ui templates**

If we would need to implement it as 
```python
class Spawner(object):
    def get_resource_availability(self):
         return {"cpu":10, "mem": "1024G" ....}
```
This data could be passed to the homepage template. The template expects a simple key value dictionary and renders it as a single row table.

**Comment by gabber12** [comment]
One other usecase for more functionality in spawner -
Admin page displays currently running notebooks. Resources allocated would be a useful attribute here.

**Comment by manics** [comment]
I'm closing this as it's quite old and there's no concrete action point. If you're still having problems please post on the [Jupyter Community Forum](https://discourse.jupyter.org/) or open a new issue. Thanks!
