### ISSUE TITLE
Issue with named servers and traitlets > 5

### ISSUE THREAD

**Issue by rcthomas** [jupyterhub/jupyterhub#3170]
Right now `requirements.txt` says `traitlets>=4.3.2`.  I just ran into an issue with traitlets 5.0.4 and JupyterHub 1.1.0 that manifested with named servers.  From my logs and a lot of debugging it started off looking like JupyterHub "forgot" that I wanted a named server and not empty string one.  Further, it couldn't configure the notebook server port and the spawn would just seem to hang.  Forcing the port to be set in the JupyterHub config would result in a 404.

I tracked it down to `Spawner.server` not getting set when new traitlets was installed.  I haven't pushed further to figure out why that would be happening, but upon comparing the dependencies I'd picked up I noticed the major version of traitlets had changed from 4 to 5 in my container build.  Reverting it made things OK.

For now I've pinned to the older traitlets, but thought I'd file an issue at least in case anyone else bumped into it.

**Comment by rcthomas** [comment]
Clarification: "would result in a 404 _when I tried to spawn the notebook server"_

**Comment by manics** [comment]
The upgrade to traitlets 5 should've gone smoothly:
https://github.com/jupyterhub/jupyterhub/issues/3141

So this sounds like a bug.

**Comment by rcthomas** [comment]
The setup I'm working with includes wrapspawner, so I'm worried it's some complicated interplay of named servers, wrapspawner, and traitlets.  I could put some cycles into seeing if I can make a reproducer.

What would help me a bit would be to understand the logic of `Spawner.server`, what conditions cause it to be initialized one way or another or not at all.  It's one of the parts of the code I've had a harder time following from just reading it.

**Comment by minrk** [comment]
Most of the relevant changes have to do with command-line parsing. Can you provide an example command-line for a named server that isn't working?

Most of the failures we have seen with traitlets 5 relate to deprecation of literal-eval parsing of command-line options (the reason we have some double-quoting of strings on the command-line). This is deprecated because command-line parsing is now much more explicit and handled by the traits themselves, meaning the long-suffered "double-quoting" is no longer necessary (i.e. `--name 1234`  will no longer result in a `TraitError: 1234 is an int, expected a str`). But if we did this the simple way, the old workaround of `--name '"1234"'` would result in the string `"1234"` (including qutoes) not the string `1234` (no quotes). Keeping the deprecated way working is *supposed* to work in traitlets 5, but there are so many cases that not all of them have tests yet, and you've likely found a bug in one of these and we need a patch in traitlets.

**Comment by minrk** [comment]
We have had specific double-quoting in jupyterhub for e.g. usernames passed on the command-line (we don't do this anymore, I think), and we should probably shift jupyterhub to remove any remaining double-quotes and say that the cases this fixed should upgrade traitlets to 5.x, rather than rely on the deprecated double-quoting in jupyterhub itself to workaround old traitlets behavior.

**Comment by rcthomas** [comment]
@minrk I'm going to update jupyterhub/wrapspawner#41 with some more details on how to reproduce the issue.  The command lines for the running notebook look the same to me.  I think it's wrapspawner vs traitlets specific.

**Comment by manics** [comment]
Closing as it sounds like it's related to the external spawner
