### ISSUE TITLE
Jupyter skips spawn form after authentication

### ISSUE THREAD

**Issue by vpavlin** [jupyterhub/jupyterhub#3247]
### Bug description
We have just noticed a change in behaviour, probably coming from https://github.com/jupyterhub/jupyterhub/commit/6f2e409fb9bb4959310f26f2316bc4d4d228acc0

JupyterHub skips spawner now directly after authentication as it seems some params are passed along from auth and callback:

```
302 GET /hub/oauth_callback?code=[secret]&state=[secret] -> /hub/spawn?code=[secret]&state=[secret] (@::ffff:10.128.2.1) 261.56ms
302 GET /hub/spawn?code=[secret]&state=[secret] -> /hub/spawn-pending/vpavlin?code=[secret]&state=[secret] 
```

The `code` seems to trigger the code in the commit linked above.

This is our oauth config: https://github.com/opendatahub-io/jupyterhub-odh/blob/master/.jupyter/jupyterhub_config.py#L86-L143

Is it possible that it is a misconfiguration on our side? Could it be an issue with authenticator?

#### Expected behaviour
Spawner is shown

#### Actual behaviour
Spawner is skipped

### How to reproduce
I don't have a simple reproducer at the moment, but I can try to get one if this turns out to me more complicated

### Your personal set up

 - OpenShift 4.5
- Kubepawner, oauthenticator/openshift

**Comment by vpavlin** [comment]
cc @mroman-redhat

**Comment by vpavlin** [comment]
I believe the actual issue might be that the auth flow does not strip the `code` and `state` which are not needed in URL after the auth flow is done - https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/services/auth.py#L987

**Comment by vpavlin** [comment]
Ok, more digging...seems like the actual culprit of the issue might be https://github.com/jupyterhub/jupyterhub/commit/14378f4cc2da8ced635841547d396d07027f56d7 - this adds the `code` and `state` query parameters which causes the spawner to spawn instead of going to UI

**Comment by vpavlin** [comment]
I was able to verify that the `code` and `state` are indeed the problem - when the `pages.py` code ignores them, everything is fine - https://github.com/vpavlin/jupyterhub/blob/bug/remove-auth-args/jupyterhub/handlers/pages.py#L183-L185

This is not the solution, though - I don't think these should stay in the URL and should be removed after successful authentication. That said, I made couple attempts, but was not able to find the right place yet. If anyone has a pointer where that should happen, I am happy to produce a patch

**Comment by minrk** [comment]
Thanks for digging into this one!


Quick solution if you want a workaround before we issue a new release: override `append_query_parameters` in your OAuthCallbackHandler class to not append any parameters, since I don't think there are any parameters on oauth_callback that should be preserved:

```python
from oauthenticator.oauth2 import OAuthCallbackHandler
from oauthenticator.openshift import OpenShiftOAuthenticator

class PatchedOAuthCallbackHandler(OAuthCallbackHandler):
    def append_query_parameters(self, url, exclude=None):
        """JupyterHub 1.2 appends query parameters by default in get_next_url
        
        This is not appropriate for oauth callback handlers, where params are oauth state, code, etc.
        
        Override the method used to append parameters to next_url to not preserve any parameters
        """
        return url

# patch OpenShiftOAuthenticator to use our patched callback handler
OpenShiftOAuthenticator.callback_handler = PatchedOAuthCallbackHandler
```

To summarize:

1. it's definitely not right that code and state are preserved after they are consumed by the oauth handler
2. `get_next_url`, which is meant to parse the `next=...` param with a default has gotten increasingly more complex, and is also used in more places!
3. #3089 appends url params *unconditionally* when calculating the next url, even when `?next=...` is given
4. #3013 considers *any* params to indicate auto-spawn behavior, making it vulnerable to triggering auto-spawn unintentionally. We probably want an opt-out or maybe a more robust opt-in for this behavior
5. url params for not-authenticated requests to `/hub/` are not preserved in `?next` on redirect. This may be considered a bug, but still shouldn't happen! A request to `/hub/?xyz=test` doesn't have a reasonable expectation that `/?xyz=test`  should be sent along to any page other than `/hub/`. So while I think there is a bug, the sequence that isn't working *should not occur*. If you want to link a user to spawn with a param, the link should be to `/hub/spawn?xyz=test` in which case the url param *is* preserved

I think both #3089 and #3013 could use some refinement. Most directly, I believe the bug is that #3089 unconditionally appended url params, when it should only have done this when `?next=` is *not* defined. Fixing that one condition might solve this particular case, and be the best immediate fix, however that may not cover the case where oauth callback fires and no `?next=` has been specified. I'll try to cook up some redirect tests to get some coverage of these different cases. I also think it is oauthenticator's responsibility to pick the redirect target appropriately and override the url params behavior.

I do not think that blocking `?code=` for *all* redirects is the right thing to do in the immediate term, since that excludes a valid redirect e.g. `/hub/spawn?code="should-be-consumed"` based on reserved names that need not be reserved across all handlers.
