### ISSUE TITLE
Community feature / community openness / community accessibility: Keeping information highly visible

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyterhub/jupyterhub#3371]
I just saw this issue https://github.com/jupyterhub/jupyterhub/issues/3340 and did not see this information mentioned elsewhere before seeing it here. The advice given was to put it inside a forum, which is not easily accessible. A better solution is to put such information in a static readable wiki or readthedocs page, where it is available for everyone.

Putting such information in a forum, which is not well readable for search engines, seems a bad idea. I never see search results pointing me to the community forum and I have the hunch, that many people part of the community are not on that discourse forum.

My suggestion here is to keep this kind of information highly visible to people outside of javascript only forums like discourse, so that people can actually find that information, when searching for it, without having to create accounts anywhere.

For example I cannot currently report an issue, which is not a bug or a feature request. The choice only allows me to choose bug, feature request, or go to the discourse forum, which I do not plan to register in. This is a barrier to reporting issues and a barrier to community participation.

**Comment by manics** [comment]
Hi! The [Jupyter community Discourse forum](https://discourse.jupyter.org/) continues to grow in popularity, and it's where most of the Jupyter community have decided to congregate.

In an ideal world we'd maintain multiple resources for documenting and discussing issues to cater to all users, but in practice most Jupyter projects are maintained by volunteers with limited time. Discourse is configured to support GitHub logins, so if you already have a GitHub account it is easy to post there. For users who don't have a GitHub account they'll face the same barriers to GitHub and Discourse.

All forums/resources have their disadvantages, but since any change requires the support of the Jupyter community I'd encourage you to start a post on https://discourse.jupyter.org/ with what you see as the disadvantages of Discourse, others may be able to help.
