### ISSUE TITLE
[rbac] separate role creation from assignment

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#3441]
Right now, `init_roles` does two things:

1. define the roles, and
2. assign users, services, groups, tokens to those roles

The second part has to run after users and services exist, while the first part has to run before e.g. services with `admin: true` are created.

I just encountered this because jupyterhub with an admin service will fail to start because the admin role doesn't exist yet because `init_roles()` is called after `init_services()`.

I think we should rearrange this a bit to:

1. create roles before init_users or other entities
2. have a separate `init_role_assignments` stage that assigns entities to roles

And also probably *remove* support for assigning roles directly to tokens. Looking at it, I think that's maybe more complicated and niche than we need. Let's keep role assignment from config only to the other encapsulating entities.

Question: **Do we still have a single `load_roles` config with both role definitions and assignments, or two separate `load_roles` and `assign_roles` config inputs for the two stages?**

We should also make it *very* clear what happens between two jupyterhub starts with:

1. launch with load_roles with `{name: "myrole", users: ['alice', 'bob']}`
2. launch with load_roles with `{name: "myrole", users: ['alice'] }`

Does bob still have role `myrole` or not? If he does, how should I update bob's role assignment to remove `myrole`?

**Comment by IvanaH8** [comment]
> I think we should rearrange this a bit to:
> 
> 1. create roles before init_users or other entities
> 2. have a separate `init_role_assignments` stage that assigns entities to roles
> 
> And also probably _remove_ support for assigning roles directly to tokens. Looking at it, I think that's maybe more complicated and niche than we need. Let's keep role assignment from config only to the other encapsulating entities.

Agree, I'll look into this.

> Question: **Do we still have a single `load_roles` config with both role definitions and assignments, or two separate `load_roles` and `assign_roles` config inputs for the two stages?**

I am inclined to the latter, having separate definitions and assignments will be clearer.

> We should also make it _very_ clear what happens between two jupyterhub starts with:
> 
> 1. launch with load_roles with `{name: "myrole", users: ['alice', 'bob']}`
> 2. launch with load_roles with `{name: "myrole", users: ['alice'] }`
> 
> Does bob still have role `myrole` or not? If he does, how should I update bob's role assignment to remove `myrole`?

Right now bob will still have `myrole` (docs do mention this as well). We thought that removing roles will be left to APIs once we implement them. But I can see that we should indeed provide a way to do this now as well. If we split the definitions and assignments, it will be easier to track who has the role so removing a user/service/group from assignment part should result in them losing the role. @0mar what do you think?

**Comment by 0mar** [comment]
I agree, having the hub initialize roles before initializing the users and services leads to some awkward constructions in the code base. Splitting this would resolve it. 

As far as the config assignments are concerned, I don't really know what is the best solution. 
I would propose to make sure that each time the hub is restarted, it reinitializes all roles for the users/services mentioned in the configuration file (perhaps with a warning when overwriting roles).
This way, there is no need to define any delete/remove methods in the configuration, since I think that could lead to inconsistent situations (what if a role is assigned and stripped in the same configuration?)
A downside is that any assignments and removals are reset when the hub is reset, which might not be ideal. So perhaps, a compromise would be to reinitialize all roles only for the users/services that do not exist in the database yet.

What do you think?
