### ISSUE TITLE
Question: loginhandler mixin

### ISSUE THREAD

**Issue by fcollonval** [jupyterhub/jupyterhub#3471]
In the `JupyterHubLoginHandlerMixin`, a couple of static methods are defined to override the one in the notebook/jupyter_server handler; like

https://github.com/jupyterhub/jupyterhub/blob/6be3160d7487bb362df7095f24454ef2814951fc/jupyterhub/singleuser/mixins.py#L89-L90

I'm surprised that they are defined as static method although they override class method.

For example in `jupyter_server` the method signature is:

```python
    @classmethod
    def is_token_authenticated(cls, handler):
```

ref: https://github.com/jupyter-server/jupyter_server/blob/11879681c1f03698ccf5c85d5fd3141bda18b654/jupyter_server/auth/login.py#L146-L147

Would it be more correct to transform them to class method?

**Comment by minrk** [comment]
Static methods and class methods are interchangeable from an API perspective, it is an implementation detail for *each subclass* which to choose. Since they don't reference the class, there is no practical difference between a static method and a class method. If you in a subclass want to reference the class, a class method has the same signature as a static method, so it is fine to use a class method there and a static method somewhere else.

**Comment by fcollonval** [comment]
Thanks for the answer @minrk
