### ISSUE TITLE
Allow setting `auto_login` only for OAuth2 authorization requests

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#3487]
### Proposed change

If you set `auto_login` to `True`, anyone landing on the hub home page is automatically redirected to the login page - the homepage isn't shown. I want to have this behavior but *only* if the endpoint being redirected to is `/hub/api/oauth2/authorize`. The use case is when JupyterHub is being used as an authentication *provider* for other services (including other JupyterHubs!). The home page of the hub provides no context to the user that it is being used as a pass through login service, and creates quite a bit of confusion.

### Alternative options

Modify the hub home page template to provide different information based on wether the user is trying to OAuth to a different application, or just logging in to JupyterHub. This can get complicated quickly though.

### Who would use this feature?

People using JupyterHub as a *source* of auth for other oauth2 enabled applications.

### (Optional): Suggest a solution

Add a `auto_login_oauth2_authorization` traitlet to `JupyterHub`?

**Comment by minrk** [comment]
> If you set auto_login to True, anyone landing on the hub home page is automatically redirected to the login page

I think you mean the hub *login* page (`/hub/login`)? To be precise, `auto_login` should affect only the `/hub/login` page, which is always is the login url for all Hub pages. So if you visit `/hub/home` and aren't logged in, you are always redirected to `/hub/login`. Assuming an external (usually oauth) login provider, if auto_login is False, this shows the "Login with $Service" button, requiring a click to start login. If auto_login is True, `GET /hub/login` automatically redirects directly to the same URL, equivalent to clicking the 'login with...' button for the user. Completion of auth should also send you back to the same home page whether auto_login is on or off. The only difference should be that one extra user click or not.

> Add a auto_login_oauth2_authorization traitlet to JupyterHub?

I think that's the simplest, and makes sense. Probably put it on Authenticator since it's login-related, even though it's for internal oauth. WDYT?

We'd need to add a `get_login_url` method to [OAuthAuthorizeHandler](https://github.com/jupyterhub/jupyterhub/blob/d4ae68267cbc5467413cd1a40ea9698e3939cd68/jupyterhub/apihandlers/auth.py#L187) with roughly the logic from [these two lines in LoginHandler](https://github.com/jupyterhub/jupyterhub/blob/d4ae68267cbc5467413cd1a40ea9698e3939cd68/jupyterhub/handlers/login.py#L122-L123) to return the Authenticator's login url `if Authenticator.auto_login_oauth2_authorization`, `super()` otherwise.

**Comment by yuvipanda** [comment]
> I think you mean the hub _login_ page (`/hub/login`)?

yep, yep that's correct.

I opened https://github.com/jupyterhub/jupyterhub/pull/3488!
