### ISSUE TITLE
Set default permission of new file from Launcher

### ISSUE THREAD

**Issue by kangsan0420** [jupyterhub/jupyterhub#3489]
Hi, I'm using JupyterHub with my team due to the convenience of managing users and reducing ports.
However, the permission of new file created on **JupyterHub Launcher** is fixed to `-rw-r--r--` regardless of the umask, which force us to use <code>chmod</code> command outside JupyterHub to share the files (ipynb, ...) with coworkers.
I searched for it, but any method including <code>NB_UMASK</code> on <code>jupyterhub_config.py</code> is not working.

The hub admin page is not much functionality so far, thus I think the "setting default permission" feature for new files created on **JupyterHub Launcher** can be added to the admin page adequately.

**Comment by minrk** [comment]
Can you give a specific example of how you are trying to set umask and what Spawner you are using, and what image if it's a container-based Spawner (e.g. Docker, Kube)? The notebook server does try to respect umask (the test suite [attempts to verify that process umask is respected](https://github.com/jupyter/notebook/blob/6fe9755971dba3357054766806d56cb8c6c1bca7/notebook/services/contents/tests/test_fileio.py#L80-L94)), so this *should* be a matter of setting the umask on the process, depending on how filesystems are mounted, etc.

> JupyterHub Launcher

I'm not sure what the JuyterHub Launcher is. Can you be more specific? JupyterHub doesn't have anything called a a Launcher. Do you mean creating new files in JupyterLab?

> "setting default permission" feature for new files created on JupyterHub Launcher can be added to the admin page adequately.

Since this is highly sensitive to the user environment, and likely different per spawner, I think it's well outside the scope of the admin UI. But it should be possible in the configuration of the user environment by the Spawner (and more likely within the user environment).

**Comment by kangsan0420** [comment]
@minrk 
Thank you for replying, and sorry for confusing, the Launcher means that from JupyterLab:
<img src="https://user-images.githubusercontent.com/79678563/120791274-f5739800-c56e-11eb-8878-44bb2b9fb71a.png" width=300px>

I used a docker container `docker run ~ -e NB_UMASK='0002'`. (tried to use `NB_UMASK`)
On the docker container, I opened jupyterhub with root user: `jupyterhub &`
These lines are added on top of the **jupyterhub_config.py** before opening the server.

<pre><code>c.Authenticator.admin_users = {'kslee'} 
c.Spawner.default_url = '/lab'   
c.Spawner.notebook_dir = '/docker_volume'   
c.JupyterHub.ip = '0.0.0.0'   
c.JupyterHub.port = 9020   
c.Spawner.environment = {'NB_UMASK': '0002'} # tried w/wo this line, and SystemUserSpawner
</code></pre>

The below screenshot shows 2 files: 
1) **created_in_bash.txt** is made from `[kslee@...] $ touch created_in_bash.txt`
2) **created_in_jupyter.txt** is made by the Launcher(JupyterLab contrib) on the JupyterHub (I logged in to the JupyterHub with the same user "kslee".)

![image](https://user-images.githubusercontent.com/79678563/120792583-b47c8300-c570-11eb-84ea-d19b9fb32de5.png)

The second file (created on hub) has different permission from the first file and it always has the same permission(-rw-r--r--) regardless of any umask. 
If JupyterHub tries to respect umask, why did it happen? Is it the docker problem? What should I do?

**Comment by minrk** [comment]
Do you see the same behavior with the same image running regular jupyterlab (not jupyterhub) in docker directly?

**Comment by kangsan0420** [comment]
@minrk 
I set the umask temporarily and when I opened the server, the umask was restored because I used root for `jupyterhub`. 
Testing with jupyterlab was very helpful. 
Thank you!

**Comment by kangsan0420** [comment]
No... JupyterLab follows umask but JupyterHub keeps resulting in files with `-rw-r--r--` for any umask.

**Comment by bklaas** [comment]
I am seeing the same issue. In my case, jupyterhub is installed at the system level, not through a docker container. Spawner command is:
c.Spawner.cmd = ["jupyter", "labhub"]

I've tried adding
c.Spawner.environment = {"NB_UMASK": "0002"}

as @kangsan0420 also tried and it is not taking effect

Behavior:
files created via terminal inside Jupyterlab have proper umask (all non-root users on this system have umask 0002)
files created via notebook (e.g., a python cell that writes out to a file) do NOT have proper umask (0022)
files created via jupyter file editor (launcher->new file) do NOT have proper umask (0022)

as with @kangsan0420, the jupyterhub process is executed by root, which is the only user on this system that has a umask of 0022.

I need to find a way to have the jupyterlab server get launched so the NB_UMASK (or whatever environmental variable is correct) sets the umask of jupyter-created files to 0022.
