### ISSUE TITLE
Admin cannot delete user

### ISSUE THREAD

**Issue by henrywu2019** [jupyterhub/jupyterhub#3536]
![image](https://user-images.githubusercontent.com/47995124/125208716-1489d780-e249-11eb-9f70-5904307b5c9f.png)

I created a user somehow named as a single dot `.`. I tried to remove it but it doesn't work. How can I remove it?

**Comment by minrk** [comment]
The user creation should probably have been rejected by username validation. But since it wasn't, you may need to delete the user via the db. The simplest way to do this is via `python -m jupyterhub.dbutil shell`, which puts you in an IPython session with a connection to your db. Then, in your session:

```python
user = db.query(orm.User).filter_by(name='.')
db.delete(user)
db.commit()
```
