### ISSUE TITLE
Consider relaxing referer check on hub API requests

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyterhub#3556]
### Proposed change
Currently several hub API endpoints are protected by a referer check:
https://github.com/jupyterhub/jupyterhub/blob/c00c3fa28703669b932eb84549654238ff8995dc/jupyterhub/apihandlers/base.py#L53-L61

Which means API requests must originate from `http(s)://<hostname>/hub/`.

The RBAC work exposes more granular access to functions which were previously for admins only, which means a single-user extension might want to make hub API calls.

For example, in https://discourse.jupyter.org/t/plans-on-bringing-rtc-to-jupyterhub/9813/7 I made a user an admin of a group. I tried to get the list of users in the group using `GET /hub/api/groups/{group-name}` from a JupyterLab extension but this is blocked as the referer URL path starts with `/user/{username}` instead of `/hub`.

### Alternative options
Do nothing

### Who would use this feature?
Singleuser apps that want to take advantage of some functions that were previously limited to hub admins.

It would potentially also be useful for someone building an external JupyterHub interface.

### (Optional): Suggest a solution
Begin by describe the security risks this is intended to protect against. Then work out if those protections can be implemented in some other way.

**Comment by minrk** [comment]
I 100% agree that Hub API requests originating from e.g. JupyterLab extensions would be super useful.

> Which means API requests must originate from http(s)://<hostname>/hub/.

The referer check is only applied to cookie-authenticated requests. Token-authenticated requests are allowed cross-origin, so should work, whether they originate in the browser or from a server extension. The main thing this means is you can't rely on *cookies* for auth to `/hub` endpoints from single-user servers, you must use the token that's stored in your single-user server cookie in an auth header.

> Begin by describe the security risks this is intended to protect against. Then work out if those protections can be implemented in some other way.

The fundamental issue in our security model is that auth is implemented in the single-user server where users themselves have arbitrary execution permissions. This is the reason JupyterHub is only appropriate for 'semi trusted' user groups, and never for fully untrusted users without lots of extra security out of scope for JupyterHub itself (e.g. by implementing an auth proxy in front of the whole application). This model makes it fairly straightforward for a user to compromise their own server and execute XSS attacks within the JupyterHub deployment. For instance, if I compromised my own server to serve an arbitrary HTML page without auth, without this referer check, I could share a link that would immediately grant me full admin permissions across the Hub if I could convince an admin to visit that link one time. Because JupyterHub is typically served from a single domain, browser XSS protections don't apply, because the Hub and singleuser server are the 'same site'.

So there's no real distinction between a 'good' request from your own cool JupyterLab extension and my malicious self-served page (a jupyter server extension is an easy way to do this). I think the only way to do this kind of thing is to shift the authentication responsibility to the proxy itself, which dramatically changes the scope of a proxy's role in JupyterHub.

**Comment by hMED22** [comment]
> I tried to get the list of users in the group using GET /hub/api/groups/{group-name} from a JupyterLab extension but this is blocked as the referer URL path starts with /user/{username} instead of /hub.

Note that you can set the `referrer` from a JupyterLab extension while sending a request to Jupyterhub to avoid getting blocked, that's possible because as @minrk said 
> Hub and singleuser server are the 'same site'

so this should work:
```
await fetch('/hub/api/groups/{group-name}', {referrer: '/hub/'})
```
