### ISSUE TITLE
User able to re-login without providing credentials after logout (Azure AD authenticator)

### ISSUE THREAD

**Issue by ubalklen** [jupyterhub/jupyterhub#3576]
I set up the Azure AD authenticator. The login process is working fine, but if the user logs out, although he is redirected to the landing page with the "Sign in with Azure AD" orange button, clicking on the button immediately takes the user back to his environment, without him having to provide his credentials again. It seems the only way for the user to get a full logout is by closing the browser.

Is this the expected behavior?

**Comment by manics** [comment]
This is expected. Since Azure is a Single Sign On (SSO) provider automatically logging users out of Azure could be very disruptive as they'd be logged out of all other applications.

If you need more help please post on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from the discussions 😀.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/user-able-to-re-login-without-providing-credentials-after-logout-azure-ad-authenticator/10420/1
