### ISSUE TITLE
Enable SSL/TLS for internal communication

### ISSUE THREAD

**Issue by minrk** [jupyterhub/jupyterhub#370]
It should be possible to use SSL/TLS/PKI for all internal communication, but I think http is hardcoded a few places.

It would be doubly awesome if we could generate/use certs for this, a la DOCKER_CERT_PATH, DOCKER_TLS_VERIFY.

**Comment by minrk** [comment]
@rgbkrk said I should cc @smashwilson and @carolynvs for ideas about implementing this.

The gist:

- one proxy, one hub, N single-user servers
- hub connects to proxy, users
- proxy connects to hub, users
- users connect to hub

Awesome enough: HTTPS connections everywhere, just encryption, no auth
Double Awesome: authenticate with certs as well

**Comment by carolynvs** [comment]
I was just thinking about this the other day! I love the idea. :smile:

**Comment by tgmachina** [comment]
Hey folks, I wanted to outline/discuss some of the stuff I have been working       
on towards this goal. I brought up this topic in the security group, and I         
thought this would be a better place to have this discussion.                      
                                                                                   
The overall changes were in line with what @yuvipanda and I discussed:             
   * Create an ephemeral CA for creating and signing certs                         
   * Dole out certs to all components that need them                               
                                                                                   
The guiding requirements I kept for these changes were:                            
   * When internal SSL is disabled, JupyterHub works as it always has              
   * Enabling internal SSL should require no more than switching on a flag         
   * Bi-directional verification, always: all components should be able to         
   verify that they are talking within the realm of trust of the ephemeral CA.  
                                                                                   
Most components in JupyterHub support the use of SSL, so most of the               
development work involved getting certs into the right place via appropriate       
options parameters. As @minrk pointed out, there are a few places where            
http was hard-coded and I made sure those pieces changed to react to the           
environment they were in--SSL or otherwise.                                        
                                                                                   
For cert creation and management, I created a small, python utility that wraps             
pyopenssl that I import into JupyterHub.                                                                         
                                                                                   
With these changes, I have JupyterHub working with all communication legs running SSL. On        
startup, with the `internalSSL` flag on, JupyterHub will generate a CA (if         
none exists), generate certs for the proxy and hub, and sign/chown certs for       
each notebook that gets started.                                                   
                                                                                   
I also had to make some small changes to `configurable-http-proxy` to forward   
requests over SSL as well.                                                         
                                                                                   
I am still working on larger scale deployment here at work as well as starting  
the release process so that I can submit a PR back to you guys.                    
                                                                                   
In the meantime, I do have something I would like to discuss: tests. Indeed,       
with the `internalSSL` setting off, tests pass just fine, but they were not        
really made to run in an SSL environment. As requests are verified in both         
directions, requests made as part of testing also need to present trusted          
certs. I started by inserting certs into the mock hub and a creating a fixture  
that returns a requests session, but this also involved modifying all test         
functions to take the fixture (incredibly tedious). Instead, knowing that the   
`app` fixture is passed to most tests and contains the certificates in             
question, I think I could modify `api_request` methods to present those            
certs if they exist in `app`.                                                      
                                                                                   
If you folks had any thoughts or suggestions on how best to peform testing in   
this environment, please let me know. Also, I looked around for a contribution  
guide, but didn't have much luck finding one. In general, I looked to the          
source itself to inform my coding style/convention, but if there's any             
particular points I should be cognizant of, happy to apply those! This will be
easier to assess when I get permission to release a PR.                    
                                                                                   
Thanks!

**Comment by minrk** [comment]
This sounds great! What sort of changes did you require to CHP?

Feel free to open a PR as soon as you have something worth discussing. It doesn't have to work, yet. As for a style guide, we aren't strict, but when in doubt PEP 8 is a good reference. [Here](https://jupyter.readthedocs.io/en/latest/development_guide/coding_style.html) is our old, woefully out-of-date style reference. The only thing to avoid is file-wide auto-formatting / big 'cleanup' changes.

Testing this does sound a little tricky. I think you are on the right track re: `api_request` and the `app` fixture. You've probably noticed that there are lots of convenience methods on the MockHub, which are for this kind of thing. Indeed, I believe that the `app` fixture is already loaded for any test where requests to the API are going to be made. However, it might be easier to make `api_request` talk to the *public* URL of the Hub (via the proxy), which should eliminate the need to use the certs.

**Comment by tgmachina** [comment]
The changes to CHP were small. For that I added a `--forward-ssl` option so that forwarded requests would be performed over https in addition to flags to set the internal key, cert, and CA. When `forward-ssl` is set, I parse `data.target` in `ConfigurableProxy.prototype.add_route` using `URL.parse`. The `target` is ordinarily a string in CHP, but the underlying `node-http-proxy` also accepts an object (from `URL.parse`) to be used in making a request. I attach the key, cert, and CA to that object so that proxy requests can be verified/perform verification. I have on my todo list to generalize CHP's target to expect an object rather than a string, clean up logging and some other pieces--I think error page fetching--that's done over http only.

Noted with the PR. As soon as I get the go-ahead on this end, I'll submit that. Likewise with the style guide, I will keep all of that in mind!

Interesting idea: using the public URL to make requests; that would make things much easier, I agree. Would there be a worry about errors as a result of side-effects from going through the proxy, rather than directly to the component in question? In either event, I'll explore both of these avenues.

Thank you for the help and input!

**Comment by minrk** [comment]
Hm. I would think that it would not be forwarding ssl because the user->proxy connection should use ssl (or not) and the proxy->hub,notebook connection should be using internal *different* ssl. Or maybe I misunderstand what forward-ssl is meant to do?

> Would there be a worry about errors as a result of side-effects from going through the proxy rather than directly to the component in question?

Not for testing, since that's how ~all real-world access would be performed anyway. Personally, I'm a big fan of running tests in a realistic environment, so talking through the proxy makes sense since that's how most communications are likely to happen. But for a first go, whatever's simplest to get working is where I would start.

**Comment by tgmachina** [comment]
Perhaps the naming `forward-ssl` is confusing. CHP still terminates the external ssl between client-proxy, as it currently does, but additionally makes that request internally (proxy->hub, proxy->notebook) using internal ssl settings/ephemeral CA. To better illustrate:

client (browser) <- external ssl -> | proxy | <- internal ssl -> hub, proxy

On either side of the |, different ssl certs are used. Any component using internal ssl is set to verify inbound certs and vice versa, so the proxy must present proper, internal certs to talk internally.

I named the option based off of the `forward` option in `node-http-proxy` (made sense at the time). If there's some name that better conveys the option's purpose, I'd be happy to change it!

RE testing: Great! I'll try for that route first then as it seems simplest overall.

Thanks!

**Comment by minrk** [comment]
Ah. To me, that shouldn't be a flag, it should be determined based on if the proxy target uses `https:` or `http:`. I don't see why an additional flag would be needed to signal that.

**Comment by tgmachina** [comment]
Good point; you're right. I will remove that then. The only new options will be the ones to pass in the key, cert, and ca that are for internal use.

**Comment by minrk** [comment]
Sounds perfect. Looking forward to the PR!

**Comment by aseishas** [comment]
I'm curious: did anything come of this? We would like to use JupyterHub and BatchSpawner to allow users to submit notebook jobs to our public cluster and have a requirement to encrypt the connection between the Hub and jobs spawned on remote nodes. In our preliminary testing we've run into exactly this issue: while the underlying proxy seems to support HTTPS targets it looks like HTTP is always assumed.

**Comment by tgmachina** [comment]
@aseishas Yes, just a bit slow to upstream things from where I work. I'm in the middle of deploying JupyterHub with these changes in our center and then I can start the export review process to get a PR out.

**Comment by tgmachina** [comment]
@pranayhasan and @aseishas, My changes to submit to Jupyter are currently being reviewed before leaving my workplace. If all goes well, I think I should be able to submit a PR within 2 weeks.

**Comment by minrk** [comment]
Closed by #2055
