### ISSUE TITLE
Unable to disable user config with Jupyter Server

### ISSUE THREAD

**Issue by rcthomas** [jupyterhub/jupyterhub#3804]
The hub administrator is supposed to be able to prevent per-user notebook configuration scripts from running by setting

```
c.Spawner.disable_user_config = True
```

In the `jupyterhub_config.py` config.  This sets the environment variable `JUPYTERHUB_DISABLE_USER_CONFIG=1` for the spawned notebook server.  However this seems to be being ignored?

<details>
<summary>Using this Dockerfile</summary>

```
FROM jupyterhub/jupyterhub:2

RUN python3 -m pip install --no-cache jupyterlab

RUN \
    adduser -q --gecos "" --disabled-password user1     && \
    echo user1:user1 | chpasswd

ADD jupyterhub_config.py .

RUN mkdir -p /home/user1/.jupyter
ADD jupyter_notebook_config.py /home/user1/.jupyter/.
RUN chown -R user1:user1 /home/user1/.jupyter

CMD ["jupyterhub"]
```

</details>

<details><summary>
with this `jupyterhub_config.py` and example notebook config for `user1`:
</summary>

```
c.Spawner.disable_user_config = True
```

```
import os

print("HELLO FROM THE NOTEBOOK CONFIG")
print(os.getenv("JUPYTERHUB_DISABLE_USER_CONFIG"))

c.ServerApp.shutdown_no_activity_timeout = 600
c.MappingKernelManager.cull_idle_timeout = 600
c.TerminalManager.cull_inactive_timeout = 600
```

</details>

I see the "HELLO" message and the value 1 printed when the notebook starts up, and the timeout message indicating that my config setting is in effect:

```
[I 2022-02-22 22:35:23.167 SingleUserLabApp serverapp:2161] Will shut down after 600 seconds with no kernels or terminals.
```

Am I misunderstanding exactly what config files are excluded?  I see there's a test for this but I wonder is it actually verifying that the config is being ignored?

**Comment by manics** [comment]
It's a regression in 2.0.0 (works in 1.5.0)

**Comment by manics** [comment]
It's related to the interaction between JupyterHub and JupyterServer. The config is disabled in `NotebookApp` but not `ServerApp`

| JupyterHub version | `JUPYTERHUB_SINGLEUSER_APP` | `c.Spawner.disable_user_config = True` |
|---|---|---|
| 1.5.0 | notebook.notebookapp.NotebookApp | ✅ |
| 1.5.0 | jupyter_server.serverapp.ServerApp | ❌ |
| 2.0.0 | notebook.notebookapp.NotebookApp | ✅ |
| 2.0.0 | jupyter_server.serverapp.ServerApp | ❌ |
| 2.1.1 | notebook.notebookapp.NotebookApp | ✅ |
| 2.1.1 | jupyter_server.serverapp.ServerApp | ❌ |

**Comment by consideRatio** [comment]
@manics you are amazing! Thanks for all your investigative work!!

**Comment by rcthomas** [comment]
Thanks @manics, did you look further into `jupyter_server` and get a sense of what happened or would it make sense for us to open an issue over there?

**Comment by manics** [comment]
I haven't looked any further.

@blink1073 any chance you could give us some help?

**Comment by blink1073** [comment]
It looks like [SingleUserLabApp](https://github.com/jupyterlab/jupyterlab/blob/886b2ab9999dd281d47e9970f60e7d3398e7020f/jupyterlab/labhubapp.py#L27) needs to add handling of [`disable_user_config`](https://github.com/jupyterhub/jupyterhub/blob/3ed345f4960f083b2d35c72b330254aa3cf31fe9/jupyterhub/singleuser/mixins.py#L370).  cc @fcollonval @jtpio

**Comment by fcollonval** [comment]
@blink1073 shouldn't it be `jupyter_sever.serverapp.ServerApp` as `SingleUserLabApp` is inheriting from it (as well as other alternative app)?

**Comment by blink1073** [comment]
I don't think so, this is Hub-level only.  cc @Zsailer

**Comment by manics** [comment]
@blink1073 thanks for the clues.....

It looks like Jupyter-server calls `jupyter_config_path()`
https://github.com/jupyter-server/jupyter_server/blob/62607ce28576e50358217534161f9e7c4aab2611/jupyter_server/serverapp.py#L2142-L2157
which is defined in
https://github.com/jupyter/jupyter_core/blob/5ae115928f57ae55928d217f9221c68ef188153c/jupyter_core/paths.py#L213-L261
This could be relevant:
```py
    if os.environ.get('JUPYTER_NO_CONFIG'):
        # jupyter_config_dir makes a blank config when JUPYTER_NO_CONFIG is set.
        return [jupyter_config_dir()]
```
So maybe setting `JUPYTER_NO_CONFIG=1` in the spawner environment will disable the user config?

**Comment by fcollonval** [comment]
> So maybe setting JUPYTER_NO_CONFIG=1 in the spawner environment will disable the user config?

But that will block configuration from the environment too, isn't it? That is probably too broad.

**Comment by minrk** [comment]
I think it's `nbclassic` that's loading this config (maybe notebook_shim? Unclear to me.), but technically any ExtensionApp could introduce the same problem.

The general issue is that each ExtensionApp may load its own config, have its own paths to search, and the patches applied by JupyterHub to the base ServerApp do not apply to extensions. When we put together JupyterHub, all Applications were a single entrypoint for loading config, but ExtensionApps make this quite a lot more complicated. They are much more independent, so it's not feasible to patch them all.

https://github.com/jupyter-server/jupyter_server/pull/715 solves two problems:

1. locating server extensions ignored config_file_paths, reimplementing the same logic in a way that cannot be overridden (the original notebookapp does this, too, for server extensions)
2. ExtensionApps ignore the parent's config file paths

I think just number 2 solves this particular case, because the nbclassic ExtensionApp would inherit config_file_path.

Maybe we also need to special-case patches for nbclassic for other properties.

Perhaps the 'no_user_config' implementation really belongs in ServerApp (or even jupyter_core). It really is jupyterhub-specific, but server extensions make it challenging to exert the control we need.

I really want to move `jupyterhub-singleuser` to just _be_ a jupyter server extension, rather than a wrapper, but right now that's hard (especially while keeping support for NotebookApp).
