### ISSUE TITLE
about static resource redirect

### ISSUE THREAD

**Issue by wuyueandrew** [jupyterhub/jupyterhub#3986]
### Proposed change

i'm designing a jupyterhub+jupyterlab+enterprise gateway solution for data scientist.
Kernelspecs are supported by enterprise gateway.In fact, it can work but the logo of kernelspec's cannot be shown on jupyterhub cause it's on enterprise gateway.
The request of kernelspec's logo is sent to hub http://hub/kernelspecs/python_kubernetes/logo-64x64.png
And i think the real url is http://hub/user/user1/kernelspecs/python_kubernetes/logo-64x64.png 

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/28866983/180684518-c5e25b0a-721e-4da2-a0d1-1ee36270925c.png">

### Alternative options

1. I think add a static resources url config to hub is ok.
2. Maybe edit the parse logic  of the 'http://hub/user/user1/api/kernelspecs?1658717568882' response and add the lab's prefix.

**Comment by manics** [comment]
Hi! JupyterHub starts the singleuser server, but it's up to the singleuser server to correctly generate all paths. For instance, there's an environment variable `JUPYTERHUB_SERVICE_PREFIX=/user/binder-examples-conda-yi99w4um/` which provides the server prefix.

Since the image is inside JupyterLab you'll need to take that into account.

**Comment by wuyueandrew** [comment]
Thanks，i'll try later
