### ISSUE TITLE
ci: test against python 3.11

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#3991]
As @minrk noted in https://github.com/jupyterhub/jupyterhub/pull/3976#issuecomment-1184975768, we can't yet do this

> Can't test 3.11 on linux because sqlalchemy requires greenlet on linux (specifically because it's easy to install there), but greenlet can't be installed with Python 3.11 yet. Ref: https://github.com/gevent/gevent/issues/1867
>
>sqlalchemy issue about how optional greenlet should be: https://github.com/sqlalchemy/sqlalchemy/issues/6136

**Comment by minrk** [comment]
Since gevent is technically optional, we could get tests running by producing a requirements.txt and omitting gevent, as [described here](https://stackoverflow.com/questions/52126116/prevent-pip-from-installing-some-dependencies):

1. `pip-compile requirements.txt > frozen.txt` (resolves all dependencies)
2. `grep -v gevent frozen.txt > without-gevent.txt` (remove gevent)
3. `pip install --no-deps -r without-gevent.txt` (install only listed packages, including dependencies, avoiding resolving dependencies a second time)

We could also get it running by testing 3.11 on mac, where gevent is not listed as a default dependency of sqlalchemy
