### ISSUE TITLE
OAuth Callback should make `error` key optional

### ISSUE THREAD

**Issue by superfive666** [jupyterhub/jupyterhub#4014]
### Bug description
<img width="678" alt="image" src="https://user-images.githubusercontent.com/7760702/184474502-b7d1e035-dba7-42e9-a28e-438ed18efc08.png">
The handler expects the `error` argument in the URL string to be passed in (regardless if there is any error).
Otherwise the tornado.web will throw "Missing argument error" exception:
https://github.com/tornadoweb/tornado/blob/master/tornado/web.py

#### Expected behaviour
Expects the API call to work fine if the call back is:
https://example.com/hub/oauth_callback?code=xxxxx&state=xxxx 
(without &error=)

#### Actual behaviour
https://example.com/hub/oauth_callback?code=xxxxx&state=xxxx 
will throw error 
Http Bad Request, 400, `Missing Argument error`

### How to reproduce

1. open browser https://example.com/hub/oatuh_callback?code=xxxx&state=xxxx
2. The Missing Argument error will appear

### Your personal set up

 - OS:
 
 - Version(s):
 

<details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

<details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

<details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by superfive666** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/7760702/184474687-d3898485-960e-494e-898f-6486b10ae731.png">

**Comment by consideRatio** [comment]
Beautiful issue writeup!!!! Thank you @superfive666!

It seems that get_argument maybe not work as i think was expected, where the second argument would be the default value. Or there is another line of code of relevance maybe?

- Do you have a stacktrace associated with the error?
- What version lf jupyterhub is used?

**Comment by superfive666** [comment]
@consideRatio Apparently the `jupyter.log` only has one line of error which prints out the GET request (as described in the issue statement). 
And if you check the code in the tornado web implementation, it says:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/7760702/184475953-6eed0b16-a694-40ca-bffd-5f9cf0bbf3b0.png">

I guess we can use the default value there to prevent it from throwing "MissingArgumentError"?

**Comment by superfive666** [comment]
@consideRatio  we are using jupyterhub `JupyterHub 1.4.1 20220813081717` from AWS EMR integration.

**Comment by superfive666** [comment]
@consideRatio Anyway, I managed to bypass this error by using the following redirect_uri:
`https://example.com/hub/oauth_callback?error=`.
This will provide the get argument function with a default value, and when there are actual errors, the `get_argument` function will take the last value that appear in the url parameters (the default value will be overwritten). 
The above bypass redirect URI works for my case (for now).
Thanks.

**Comment by consideRatio** [comment]
Hmmmm I fail to find code that would cause a missing argument error in jupyterhub 1.4.1, not sure how to proceed in this issue.

**Comment by superfive666** [comment]
@consideRatio you can find it here:
https://github.com/jupyterhub/jupyterhub/blob/2096c956db8cb64b67f59eea51d252fe346d37a0/jupyterhub/services/auth.py
branch: `1.x`, line 1195

I guess is the same for all branches.

**Comment by ren276** [comment]
hey @superfive666 i would really like to fix this issue . Can you guide me through it+

**Comment by consideRatio** [comment]
Is that line throwing an error? Are you sure? That has a default fallback in case error isnt defined right?

**Comment by manics** [comment]
Hi! I've tried to reproduce the problem, but haven't been able to. Please can you provide a minimal reproducible example with JupyterHub 2.3.1?

**Comment by superfive666** [comment]
@consideRatio Yes, that is the line.
@manics please see screenshot of replicated error log on server side:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/7760702/184566435-53523f7b-0f2b-460a-a4fa-9707e6827d2b.png">

Referring to the screenshot above, it is calling the web.py function `get_argument` function:
https://github.com/tornadoweb/tornado/blob/master/tornado/web.py
<img width="677" alt="image" src="https://user-images.githubusercontent.com/7760702/184566515-91b8fb14-1e73-46b2-bb94-4c8221c8a7cb.png">

based on the code above, i would suggest trying:
```
# To avoid ambiguity in keyword arguments (maybe due to different python version)
self.get_argument("error", default = "", strip = False)
# instead of self.get_argument("error", False)
```

**Comment by superfive666** [comment]
@manics in the issue statement, the steps to reproduce is what I did:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/7760702/184566913-4aebae19-fb9a-410d-93e3-82cb6de723f6.png">

**Comment by minrk** [comment]
> you can find it here:
https://github.com/jupyterhub/jupyterhub/blob/2096c956db8cb64b67f59eea51d252fe346d37a0/jupyterhub/services/auth.py
branch: 1.x, line 1195

That's not where the error is raised. That handler doesn't serve `/hub/oauth_callback`, it only runs in single-user servers and services (`/user/:name/oauth_callback`). `/hub/oauth_callback` is a custom handler added by `oauthenticator`, which also sets the default to avoid this error [here](https://github.com/jupyterhub/oauthenticator/blob/15.0.1/oauthenticator/oauth2.py#L156).

Can you show a full `pip freeze`? And which authenticator you are using? Since the error is raised by the authenticator and not jupyterhub, it's likely in that package, and I suspect also fixed in the current version.

**Comment by superfive666** [comment]
Hi @minrk , thanks for pointing it out. Yes, you are right, the error is from the check error in the oauthenticator (15.0.1):
<img width="756" alt="image" src="https://user-images.githubusercontent.com/7760702/184621487-37ab10d2-e78d-4b06-9c93-9e652324f763.png">

The code is the same as the one screenshot in my previous reply. 
Anyway, is just my own suggestion on the coding style. 
And I have managed to bypass the error by manually inserting the error key in the `redirect_uri` value.
(`https://example.com/hub/oauth_callback?error=`) (in case any one else also hit the same error haha)

As can be seen from the implementation:
<img width="771" alt="image" src="https://user-images.githubusercontent.com/7760702/184621898-da6a2963-fcfc-4dd1-af8a-2b7482f55906.png">
The get argument function is returning the last `error` value found in the url, so this bypassing method will not  hinder the proper usage if there is indeed an error occurring.

Thanks for your time and have a nice day.

**Comment by superfive666** [comment]
@minrk oh, and the web.py is accepting `Union[None, str,  _ArgDefaultMarker]` as the default parameter
<img width="633" alt="image" src="https://user-images.githubusercontent.com/7760702/184623143-83e20809-a508-4e7c-861d-31064b95fa90.png">
So if you pass in a `bool` to the default keyward argument will trigger a warning message from your python linter :) as well

**Comment by minrk** [comment]
What version of tornado do you have? (complete `pip freeze` would be super helpful, that's why we request it in the issue template) And which class in oauthenticator are you using? I don't know what's different about your environment, but all the calls I've found call get_argument with a default, which means it won't raise. It _will_ raise if `code` or `state` is missing, as it should. I've also followed the repro steps and verified that `check_error` when `error` is not given does indeed pass without error with the provided URL and versions, returning the provided `False` and moving on. We can certainly change our default arg from `False` to `''`, but it won't change any runtime behavior, so it's highly unlikely to be the source of the error you are seeing. It only satisfies the (inaccurate) type annotation, which has no effect at runtime. Tornado could also update the annotation to accept Any, which it actually does.

Maybe there's another call somewhere else that's not in our code?

**Comment by superfive666** [comment]
@minrk Hi, the full list of pip freeze is very long and I don't think the rest of the packages matter. And the line regarding the tornado version is screenshot as below:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/7760702/184650887-3b928e7d-867b-4768-a6f2-45313dee2df7.png">

I am not an expert in python but as mentioned, we used JupyterHub from AWS EMR cluster which all the configurations and setup are pre-built into the clusters. As for the usage of the authenticator, we followed the documentation for jupyterhub:
https://jupyterhub.readthedocs.io/en/stable/reference/authenticators.html
together with some samples provided in the github repository:
https://github.com/jupyterhub/oauthenticator/tree/main/examples. 
And the jupyterhub application is containerized and run in a docker environment on the server, there is nothing much we can do to change runtim behavior too.

It took me quite a while to locate the `self.get_argument("error", False)` which is from the tornado web.py that raised the exception. We even tried the callback_uri to be `https://example.com/hub/oauth_callback?error=&` and that did not work i think.

**Comment by minrk** [comment]
Ah, custom installs without versions makes things tricky to track down since it's not reproducible and doesn't include version information. All I know is that the calls to `get_argument` we've found in both jupyterhub and oauthenticator do _not_ raise, so they are not likely to be the source of the reported error. So either there's a call somewhere to `get_argument("error")` that _doesn't_ specify `default` (more likely, though I don't know where that could be coming from - showing your Authenticator class might help), or a version of tornado that I'm not aware of that doesn't have the known behavior for the `default` arg (i.e. not between 5.1 and 6.2 or current master).

**Comment by superfive666** [comment]
I totally agree.
There are number of applications in the AWS EMR cluster that require SSO/SAML/LDAP integration. If hitting one small error means having to read tons of code on github is an absolute nightmare. 

Since your assessment on the original code does not have any bug and my current workaround does not throw any further errors, I will just close this thread. :)
