### ISSUE TITLE
Restructuring JupyterHub documentation: Which path to take? 

### ISSUE THREAD

**Issue by alwasega** [jupyterhub/jupyterhub#4272]
@sgibson91 and I are at a crossroad regarding how best to restructure the JupyterHub documentation and we would love some input from the community: 

1. We can select to restructure the docs using vanilla Diataxis framework, in which case, we would organize the articles into four main categories: `How-To Guides`, `References`, `Explanations`, and `Tutorials`. This way, we would end up with something similar to [Django's documentation](https://docs.djangoproject.com/en/4.1/).
2. Alternatively, restructure the documentation according to the needs of JupyterHub's core users (Developers and Sys Admins). This way, we would end up with something close to [2i2c's docs](https://docs.2i2c.org/en/latest/), but structured according to the Diataxis framework and segmented to meet the needs of the two user groups. 

Please give your thoughts regarding these two approaches.

**Comment by consideRatio** [comment]
Hey @alwasega, thanks for working on this!!!

I didn't understand the second idea well. I understand that you reason about two user groups, but didn't understand the groups. Was it "Developers and Sys Admins"? If so, those groups could need further clarification for me to think clearly about this.

I'm wondering for example if "Developers" was referring to JupyterHub developers, or perhaps users of a jupyterhub deployment doing development work in their started servers? I'm also wondering if "Sys Admins" was referring to people deploying a jupyterhub?

**Comment by sgibson91** [comment]
> I'm wondering for example if "Developers" was referring to JupyterHub developers, or perhaps users of a jupyterhub deployment doing development work in their started servers? I'm also wondering if "Sys Admins" was referring to people deploying a jupyterhub?

Sorry Erik, you beat me to the issue to add clarification :D You're on the right path though. We discussed "Developers" as "folk who work on the Python package called JupyterHub" and "Sys Admins" as "folk who are deploying their own JupyterHub".

I actually think we already have this distinction between our Contribution Guide, and all other documentation. So we shouldn't complicate things and just keep the Contribution Guide as it currently is, and reorder all other documentation into diataxis. We _could_ later on see if the Contribution Guide itself could benefit from being restructured into diataxis, but I know a lot of work has gone into improving that recently so let's let those changes settle first.

Allan, I do believe there is an opportunity to write new developer-focussed documentation with the other interns. For example, working with Sheila to document how a developer may setup the pytest plugin to test their Authenticator or Spawner. Those docs would obviously live in the pytest plugin repository and maybe there's a cross-link somewhere from JupyterHub's docs or elsewhere.

**Comment by consideRatio** [comment]
No worries at all @alwasega!

@sgibson91 ah nice okay! I agree with the idea to retain the contributing section as a standalone section. I think we can manage to avoid overlap between topics covered in the contributing section of the docs and the rest, and I think due to that it shouldn't complicate things having them separate.

**Comment by minrk** [comment]
Can we classify on both axes to see how things might separate (i.e. this page is a How-To for a developer, etc.)?

I think "developers" may also be further segmented into:

- contributors to JupyterHub itself, and
- authors of modular implementations (Spawners, Authenticators)

So I think there are really three audiences for JupyterHub docs:

1. contributors to jupyterhub itself
2. developers of Spawners/Authenticators
3. deployers (and prospective deployers) of JupyterHub

There's a lot of nitty gritty detail of how JupyterHub works that's not relevant to authors of  Spawners, but we should still have documentation for it for folks who want to understand how JupyterHub works. I'm not sure how much docs would be further separated along those lines, so it may not make sense to separate them, but I think it might be nice to get a view of what we have, to see how it might be divided.


My _initial_ inclination (before seeing how the classification breaks down), is that we follow diataxis once at the top-level, and maybe handle the audience separation at the index level. Because I suspect some of those lines may be a bit blurry, having to organize along harder lines at the top level may get in the way a bit. We could, for example, group the how-to index table of contents by audience (or whatever other grouping(s) makes sense based on the content we have).

**Comment by manics** [comment]
I don't know what's best. Would it be useful to map out some example user journeys through the docs to compare the options?

For example, suppose I'm an administrator planning to upgrade to the next major version of JupyterHub. Starting from the JupyterHub docs home page@
- What do I click on? e.g. straight to the upgrade section vs going to an admins section and from there another click to get to the upgrade info.
- What information on upgrading is provided? Technical info with all the breaking changes, or just general upgrade instructions? Does some information come under a different diataxis area which is cross-referenced?
- How does this journey compare if I'm a developer wanting to ensure my spawner/authenticator/addon is compatible instead of an administrator?

**Comment by alwasega** [comment]
Hello!
Thank you @manics, @minrk, @consideRatio, and @sgibson91 for your input. I am leaning toward Min's suggestion about following the diataxis framework at the top level and implementing audience separation at the index level. 

I have classified the present docs following the diataxis framework in the Google sheet [here](https://docs.google.com/spreadsheets/d/1Nnwji40YXMklnQ2yvO3rcfGnMP8S_LsVlkKdobo8ZjM/edit#gid=307391957). Kindly review the mapping (final version in tab 4 - Mapping v.2) and give me any feedback and suggestions by Monday (9th Jan). 

I would like to incorporate your feedback before I start marking gradual changes to the documentation.

**Comment by sgibson91** [comment]
> and suggestions by Monday (9th Jan)

Just to point out that this is only one working day in actuality given the weekend and we have a combination of (i) a volunteer team, and (ii) not everyone may have returned to work yet. Can we maybe extend this to the end of next week instead?

**Comment by alwasega** [comment]
> Can we maybe extend this to the end of next week instead?

Sure @sgibson91. Let's work with the end of next week.

**Comment by minrk** [comment]
I left some feedback on the spreadsheet, mostly on the 'unsure about placement' pages. It looks very good!

I think the hardest distinctions for me are:

1. we do have some 'explanations' in some of our reference material. For these, I think keeping them in reference as they present reference information, and flagging them for possible rewrite/split.
2. how-to vs tutorial in our examples

For how-to vs tutorial, it seems the main distinguishing goal is "achieving the final result" vs "understanding how things work". Part of why I think classifying our examples is hard is that this question wasn't taken into account during writing, so they do a bit of both. Looking at the layout, I think we probably do want more tutorial content, and perhaps one way to do that is to place some of the docs like 'basics' in tutorials and mark them for rewriting with the diataxis tutorial definition in mind.

**Comment by alwasega** [comment]
Thanks @minrk. Let me look at the comments and will get back to you.

**Comment by alwasega** [comment]
I responded to some of your comments on the spreadsheet @minrk . 

Also, I agree with flagging some of the articles for possible rewrites/ splits. At the end of the internship, I will write an issue/ report detailing these articles and how they can be improved. 

> Looking at the layout, I think we probably do want more tutorial content, and perhaps one way to do that is to place some of the docs like 'basics' in tutorials and mark them for rewriting with the diataxis tutorial definition in mind.

I will mark the docs that can be made into tutorials and mention the need to rewrite them in both the PR moving them to the tutorials section and in the issue/ report mentioned above. 

Thank you for your feedback. I will now progress to restructuring the docs in the repository in small and manageable PRs.
