### ISSUE TITLE
Provide interface to create local envs and install libs

### ISSUE THREAD

**Issue by YannBrrd** [jupyterhub/jupyterhub#430]
Hi,

Would it make sense to provide in Jupyterhub interface a place to create a local user env and reigster it (conda env or virtual env, depending on config) ? It would allow to have local user envs ans activate them with no CLI, which would be a good thing in terms of UX. 

Other option to explore is to use bash kernel to do this, with default notebook provided by local admin...

Let me know your thoughts about this.

Cheers,
Yann

**Comment by minrk** [comment]
I'm not sure what you mean by providing an interface for this. Can you explain further? If you want user servers to run in envs and each user to get their own env, then this sounds like a task that should be covered by a custom Spawner.

**Comment by YannBrrd** [comment]
The idea is to provide a Menu entry or something in Jupyterhub to avoid
users to have CLI access to create a local env and run the server in user
home dir  ?

Le mar. 16 févr. 2016 à 16:11, Min RK <notifications@github.com> a écrit :

> I'm not sure what you mean by providing an interface for this. Can you
> explain further? If you want user servers to run in envs and each user to
> get their own env, then this sounds like a task that should be covered by a
> custom Spawner.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/issues/430#issuecomment-184720963>.
>
-- 
Cordialement,
Yann Barraud

**Comment by aeroevan** [comment]
The semi-solution I've found is that users can create a virtualenv, install ipykernel in the virtualenv, python -m ipykernel install --user [--name some_name] and then the user can start a kernel that is in the virtualenv.

The only issue that I've noticed is that the virtualenv isn't actually activated, so the PATH doesn't get updated so that calls to !pip use the system pip, not the pip in the virtualenv as expected. A hacky workaround I've found is that the kernel.json can be edited to add "env": {"PATH": $(echo $PATH)} (where the PATH is echo'd from the active virtualenv).

https://github.com/jupyter/jupyter_client/issues/127 may be a path to actually activate the virtualenv before the ipykernel is run, but supporting creating new ipykernels inside virtualenvs (creating and user installing the kernel) would be really nice.

**Comment by YannBrrd** [comment]
Indeed but I'd like to have this done through user browser...

Le mer. 17 févr. 2016 03:15, Evan McClain <notifications@github.com> a
écrit :

> The semi-solution I've found is that users can create a virtualenv,
> install ipykernel in the virtualenv, python -m ipykernel install --user
> [--name some_name] and then the user can start a kernel that is in the
> virtualenv.
>
> The only issue that I've noticed is that the virtualenv isn't actually
> activated, so the PATH doesn't get updated so that calls to !pip use the
> system pip, not the pip in the virtualenv as expected. A hacky workaround
> I've found is that the kernel.json can be edited to add "env": {"PATH":
> $(echo $PATH)} (where the PATH is echo'd from the active virtualenv).
>
> jupyter/jupyter_client#127
> <https://github.com/jupyter/jupyter_client/issues/127> may be a path to
> actually activate the virtualenv before the ipykernel is run, but
> supporting creating new ipykernels inside virtualenvs (creating and user
> installing the kernel) would be really nice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/jupyterhub/issues/430#issuecomment-184978527>.
>
-- 
Cordialement,
Yann Barraud

**Comment by minrk** [comment]
@YannBrrd but my question is do you want this to be a UI for creating and using *many* envs for kernels, etc., or just making sure that each user's server runs in an env? If it's the latter, I don't see a need for UI at all, since that's covered by a custom spawner. If it's the former, then this is really a single-user notebook feature, since the Hub doesn't necessarily have access to the filesystem where the single-user server runs.

**Comment by YannBrrd** [comment]
Was for the second option... Will try to mature the idea...

**Comment by minrk** [comment]
@YannBrrd thanks! Hopefully we can come up with something that works, whether it's in this repo or a custom spawner, or a notebook extension.

**Comment by joefromct** [comment]
Do most folks circumvent the need for virtualenv's by installing  pip packages globally so all kernel users have access? 

That is a bad idea still.... right?  

To me this sounds like it would provide users package install access and still not mess up the global site-packages, unless i'm missing something.

**Comment by minrk** [comment]
@joefromct using a global, shared env (whether it's a system install or an actual env) is common and isn't a bad idea for admin-controlled environments. If you want to give users total control, creating user-owned envs is a good idea, whether that's a virtualenv or a docker container, etc. It all depends on what permissions the users should have, which varies quite a bit.

**Comment by AlJohri** [comment]
hi @minrk, just checking if you've come across any more ideas on how to do this in the past year. I'm looking into setting up jupyterjub for my team but we make large use of project specific virtualenvs. we often install generic package names such as `lib` within the virtualenv (`pip install ../lib -e`) and won't be able to install such things globally.

I don't mind giving users shell access. The plan was that the ssh into the server and clone down their repository- then use jupyterhub to run the notebooks. Any ideas on how to incorporate a virtualenv into the picture here?

**Comment by AlJohri** [comment]
Throwing some links for future google-ers here:

- https://github.com/bhrutledge/jupyter-venv
- https://github.com/minrk/a2km
- https://github.com/Cadair/jupyter_environment_kernels
- https://github.com/Anaconda-Platform/nb_conda_kernels

**Comment by sjillidimudi** [comment]
@AlJohri  I have  a similar requirement where i want to provide user specific virtual environments accessible as kernels in the jupyterhub .  Did you used https://github.com/Anaconda-Platform/nb_conda_kernels ? Can you share your experience .

**Comment by consideRatio** [comment]
This is a complicated topic relating to storage assumptions which relates to assumptions on how the user environment is deployed etc, due to that, I think this must become a question for specific distributions of JupyterHub rather than JupyterHub itself. For example, in tljh.jupyter.org, z2jh.jupyter.org, or https://github.com/Quansight/qhub. The latter has the most advanced system for managing user environments currently, I have not tested it yet.

Closing this issue as out of scope for JupyterHub itself, or at least without a clarification on how it can be in scope without becoming dependent on user environment assumptions.
