### ISSUE TITLE
Services are moved to a subdomain if subdomain_host is set

### ISSUE THREAD

**Issue by akhmerov** [jupyterhub/jupyterhub#4306]
### Bug description

Specifying `c.JupyterHub.subdomain_host` moves the services URL to `//services.<subdomain_host>/services/`. This was a bit tricky to figure out, and I in the end only discovered it by querying the proxy via its API.

#### Expected behaviour

- Either services should stay at the main hub domain
- Or the behavior should be documented when describing the service behavior and additionally the admin panel should take this into account when computing service URLs (now it does not).

### How to reproduce

1. Setup a whoami service
2. Configure the jupyterhub to use a subdomain_host
3. Check proxy paths

### Your personal set up

Jupyterhub 3.1.0

**Comment by minrk** [comment]
Yes, services are meant to be on the `services.` subdomain to keep everything but the Hub off of the Hub's own domain. We should add this to the subdomain docs in websecurity.md (and probably have a clearer how-to doc just for this). Arguably, it's sensible also to make the separate subdomain behavior for services an independent toggle so that you can choose to only apply subdomains to _users_ rather than everything.

The incorrect nav links are defined [here](https://github.com/jupyterhub/jupyterhub/blob/cb0073e9b8f4d38a65e820779c67ff85a0f44420/share/jupyterhub/templates/page.html#L134), which should take subdomain config into account.

**Comment by akhmerov** [comment]
I encountered a related question: given the hub config, I find it really unclear how to compute the service URL. Do you have any advice for that? It seems like there should be a single source of truth for this, but I can't find it.
