### ISSUE TITLE
Documenting the current use of the `io_loop` fixture within JupyterHub's test suite

### ISSUE THREAD

**Issue by Sheila-nk** [jupyterhub/jupyterhub#4336]
### Overview
Currently, the JupyterHub repository relies on the `io_loop` fixture to call coroutines. This is done using the `run_sync` method.

Given the current state of the `pytest-asyncio` plugin, that the JupyterHub test suite uses, we can now use top-level awaits to call coroutines within async functions.

*Example:*
```python
def example_function():
    server = io_loop.run_sync(get_server)
    return server
```
*would now be:*
```python
async example_function():
    server = await get_server()
    return server
```

### Proposed change

I believe it is important to document the current event-loop integration within JupyterHub using the `io_loop` fixture for anyone not familiar with it. 

It will also help guide the work of moving towards complete use of top-level awaits. Refer to [Min's PR](https://github.com/jupyterhub/jupyterhub/pull/4332) for a clear picture of what this work looks like.

Also, refer to this [Georgiana's issue](https://github.com/jupyterhub/pytest-jupyterhub/issues/30) that sparked the idea.

**Comment by minrk** [comment]
After #4332, we don't generally use `io_loop` for `run_sync`, but rather to make sure the test (or fixture) is run while the global io loop object exists and hasn't been cleaned up. These are relatively rare, and mostly boil down to the `app` fixture itself.

**Comment by Sheila-nk** [comment]
I noted that the JupyterHub `app` module uses `run_sync` in [this instance](https://github.com/jupyterhub/jupyterhub/blob/63f164ca53d222d9e65d35f5422c9fd635b577a0/jupyterhub/app.py#L3388). In this case, can we use `await` instead? 

Since #4332 sorted this out, I don't think there is a need to work on this issue.

**Comment by GeorgianaElena** [comment]
> Since https://github.com/jupyterhub/jupyterhub/pull/4332 sorted this out, I don't think there is a need to work on this issue.

@Sheila-nk, I believe this issue should be instead rescoped to track the gathering of the information that was exposed about the jupyterhub's tests, when understanding the use of `io_loop` fixture (that has since almost been removed).

So, instead of documenting the `io_loop fixture`, I believe what would be useful to have, is a short paragraph (maybe in a README.md in the tests directory) with general info about jupytehub's test suite (maybe scoped around testing against a running hub app in the `pytest-asyncio` context ) gathered from https://github.com/jupyterhub/pytest-jupyterhub/issues/30 and https://github.com/jupyterhub/jupyterhub/pull/4332 and maybe linking where appropriate to other resources for people wanting to learn more about asyncio, event loops, pytest scopes, fixture initialization and cleanup, etc.

What do you think?

**Comment by Sheila-nk** [comment]
> What do you think?

I agree. It would be more useful to center the documentation around that instead. 
I will work on it and update this issue accordingly to reflect the work done.
