### ISSUE TITLE
Can we with a metric measure if jupyterhub is CPU constrained?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4353]
I've watched a few grafana dashboards, most recently [examples from here](https://github.com/jupyterhub/grafana-dashboards/pull/59) where hub response times can peak to seconds. Seeing that I got thinking that the hub pod from time to time get starved on CPU.

In practice though, it is perhaps rather that some responses are stuck waiting on something, like stopping a server, before it completes. So, it would be incorrect to draw the conclusion that the hub pod is overburdened by requests when we see long response times.

The question I raise is then instead, can we understand if jupyterhub is overburdened somehow using exposed prometheus metrics? If not, can we develop a new metric for this somehow?

**Comment by yuvipanda** [comment]
I think the most useful metric here is 'tick duration' - how long does a single 'tick' of the event loop take? I know that when we were on the tornado ioloop @minrk has this be printed during debug, and it was *super* helpful. However when we moved to asyncio ioloop we lost this. A tick duration that's too long usually means there's too much CPU bound stuff going on that's not async enough, and causes responsiveness problems.

I don't know if we can measure that though.

**Comment by minrk** [comment]
> when we moved to asyncio ioloop we lost this

To be clear, it's _tornado_ that switched to asyncio.

asyncio has its own [debug mode](https://docs.python.org/3/library/asyncio-dev.html) that logs similar info. I don't think it quite includes tick duration, but it does note each _individual coroutine_ that blocks for more than 100ms (configurable threshold). Lacking the 'tick duration' metric means the asyncio debug log wouldn't capture the 'everything individually is async and cooperative and fast, but there's just too damn many coroutines right now' case.

 I'm not sure how we could hook it up to metrics. Maybe we could hook up the asyncio debug logger and count 'long task block' events? It would be hard to get labels on them, I think.

**Comment by minrk** [comment]
Looking into asyncio, we _could_ patch asyncio's `_run_once` as is done [in the asyncio test](https://github.com/python/cpython/blob/8a2b7ee64d1bde762438b458ea7fe88f054a3a88/Lib/test/test_asyncio/test_events.py#L1708-L1714) to add a timer for the tick, equivalent to what we had in tornado. This is a private API, but private APIs in the standard library are very stable, so can generally be safely written against for debugging purposes, as long as you gracefully handle their eventual removal, which should be easy enough for a metric like this.

Something like:

```python
loop = asyncio.get_running_loop()
original_run_once = loop._run_once
def _run_once(*a, **kw):
    tic = time.perf_counter()
    original_run_once(*a, **kw)
    toc = time.perf_counter()
    gauge_metric.set(toc-tic)
loop._run_once = _run_once
```

gated by `if hasattr(loop, '_run_once`)`.

Profiling inner loops like this (or asyncio.set_debug) does have a nontrivial cost on the performance you are measuring, since they are called _a lot_, so should generally be opt-in.

**Comment by minrk** [comment]
I opened a feature request after digging some more into tornado history: https://github.com/python/cpython/issues/101946

We definitely _can_ implement this ourselves, with a small amount of private-api usage.

What would be the right metric to use? Histogram? It is an event that happens _a lot_.

**Comment by consideRatio** [comment]
![image](https://github.com/jupyterhub/jupyterhub/assets/3837114/841a1bc7-dd75-4f66-a697-76fd60e779b1)

I saw that the dask scheduler provides a dashboard, in it it lists the workers it controls, and they report `event_loop_interval`. I found code to emit that data [in dask/distributed 's worker.py](https://github.com/dask/distributed/blob/7d0ba9c402f435ce0cdeef5fae33173c59d17153/distributed/worker.py#L1074)

**Comment by minrk** [comment]
Nice, we could definitely do a similar metric.

It's a little tricky to wrap my head around [the metrics](https://github.com/dask/distributed/blob/7d0ba9c402f435ce0cdeef5fae33173c59d17153/distributed/core.py#L734-L759), but it _doesn't_ actually measure event loop ticks when things are responsive below a certain threshold, though it _can_ catch when ticks take _longer_ than that threshold.

In their case, the metric is an instant scalar metric for the _average_ event loop interval by counting the number of times a PeriodicCallback with a short interval is called over a longer interval. The default behavior is 20ms for the short interval and 1s for the collection.

Another way to represent the metric is a _histogram_ of tick intervals, which might better represent how often ticks are within different buckets, since it would capture more granularity. But would be a bit more costly to represent.

I've run this metric with an artificial blocking sleep of ~1 second every second, and it still reports an _average_ event loop interval of ~0.1 seconds, because it's still running 10-20 fast ticks for each slow one. It doesn't really capture that 50% of the time, it's blocking for 1 full second.

Maybe that's right for dask, but I'm not sure if the _average_ ("in general, how many ticks to we get in a second") is as useful for us than the Histogram ("how often is a tick more than X milliseconds; Y seconds; etc.").

**Comment by minrk** [comment]
and I realize you can use count/sum of a histogram to compute the average (over the prometheus collection interval, at least), so maybe just the histogram is ideal?

**Comment by minrk** [comment]
#4615 adds the histogram metric
