### ISSUE TITLE
Expose `oauth_no_confirm_list` configuration to users

### ISSUE THREAD

**Issue by trungleduc** [jupyterhub/jupyterhub#4370]
### Proposed change
Currently, the `needs_oauth_confirm` method of `OAuthAuthorizeHandler` checks for the oauth clients that don't need confirmation. It ignores the clients in the `oauth_no_confirm_list` set 
(https://github.com/jupyterhub/jupyterhub/blob/ce7085b720f690144f9fe987eb373c3a0bd83db2/jupyterhub/apihandlers/auth.py#L180-L189)

But the `oauth_no_confirm_list`  is generated automatically at startup and is not configurable by users. 

https://github.com/jupyterhub/jupyterhub/blob/ce7085b720f690144f9fe987eb373c3a0bd83db2/jupyterhub/app.py#L2722-L2729

It would be useful if users could define the initial value of this set before populating it with the other services. And since it is a white list, we could support the `regex` pattern in this list to allow more freedom on service names.
 
### Alternative options
I don't know if we have other ways to populate this `oauth_no_confirm_list` set.

### Who would use this feature?
In our use case, we use `JupyterHub` as an OAuth provider for external applications which are not managed by `JupyterHub`, this feature will help us to bypass the confirmation screen of all applications at once.

### (Optional): Suggest a solution

- Allow users to define `oauth_no_confirm_list`  in the configuration file with a list of services name or regex patterns, e.g:

```python
c.JupyterHub.oauth_no_confirm_list = ['my-oauth-service', '^(my-prefix)']
```
- Update the current logic of populating the `oauth_no_confirm_list` set and the verification in the `needs_oauth_confirm` method.

**Comment by minrk** [comment]
JupyterHub shouldn't in general support anything that requires manual interaction with its database. The JupyterHub database is considered an entirely private implementation detail, and should only ever be interacted with via JupyterHub config or REST APIs (we're even working to remove all _Python_ API access to the database from extension points).

So I think we should take a step back and understand the use case of why you need to define services not via config, and see if we can address that in a supported way, rather than enabling a config option that would only be useful for something that isn't supported. Can you describe how you are using services that the existing config doesn't support? If it's registering services at runtime, would a REST API for registering new services with the same inputs as services coming from config suffice?

**Comment by trungleduc** [comment]
Thanks @minrk  for your input! Indeed we are registering services at runtime via our REST APIs by manipulating the JupyterHub database manually. I want to expose this setting to pave the way for the second PR which will add the REST APIs for registering services dynamically.

**Comment by trungleduc** [comment]
I will try to propose the services API PR next week, then we can come back to this PR to see if we really need to expose this setting.

**Comment by minrk** [comment]
Thanks, that sounds great!

We will need to resolve the reconciliation of runtime-defined vs config-defined services at startup, as discussed for roles in #3858. This can probably be a boolean column.

**Comment by yuvipanda** [comment]
Closing based on https://github.com/jupyterhub/jupyterhub/pull/4371#issuecomment-1463743820
