### ISSUE TITLE
Issue reported from pip for 1.2.2's wheel

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4405]
In #4404 there was a test failure involving upgrading to or from jupyterhub 1.2.2 specificially. This failure related to the released wheel for that version.

```
Downloading jupyterhub-1.2.2-py3-none-any.whl (3.6 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━                  2.1/3.6 MB 227.2 kB/s eta 0:00:07
  ----------------------------- Captured stderr call -----------------------------
  ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
      jupyterhub==1.2.2 from https://files.pythonhosted.org/packages/47/15/b2c89e4b6fc5f1c321bfc416311236f168e83f5e07c519e5a58fe2b9e94d/jupyterhub-1.2.2-py3-none-any.whl:
          Expected sha256 4bd19a9e9efc5b79bf70622f8f4fcbdc7030f7c1cc897c924f00fc0b579f5219
               Got        84eaf00a9d8492fdc210e36b064987597cf755144580b5a7204298e89d7aa2d2
```

Since i merged #4404 i wanted to offload this into an issue at least for now.

**Comment by minrk** [comment]
We don't have a requirements file with hashes in it, so the error appears to be at least a bit misleading. My guess is the hash would have come from the PyPI API. I suspect there was an intermittent problem with either the PyPI server, because another test run at the same time hit a connection error trying to download from PyPI:

```
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
```

and the tests all passed once that PR was merged merged.
