### ISSUE TITLE
Ideas for new authenticator config

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4487]
I agreed with @minrk in a the recent June jupyterhub team meeting to describe an idea of new config without coupling it to suggesting how it should be implemented.

I want directly configured behaviors instead of behavior following from if `allowed_users` is truthy or falsy. Currently the following behaviors can follow from declaring `allowed_users`:

1. Declaring `allowed_users` truthy currently [implies allowing existing users](https://github.com/jupyterhub/jupyterhub/blob/4.0.0/jupyterhub/auth.py#L647-L648) to login as well.
2. Declaring `allowed_users` falsy can for some authenticators in certain configurations imply allowing all authenticated users to login.

I suggest new authentication config like below to provide a way to directly configure the otherwise implied behavior:

1. `allow_existing_users`
2. `allow_all`

I think such new config could make:
- a deployments jupyterhub config easier to understand without reading the docs
- easier to provide as secure by default
- easier to document, maintain, and implement

## Related

- Discussion related to `allow_existing_users`: #4483
- Discussion related to `allow_all`: #4484
- Discussion related to defaulting to not allowing existing users in OAuthenticator, introducing `allow_existing_users` and defaulting to False: https://github.com/jupyterhub/oauthenticator/issues/619
- Discussion related to defaulting to not allowing all users in OAuthenticator when no users is explicitly allowed, introducing `allow_all` and defaulting to False: https://github.com/jupyterhub/oauthenticator/issues/620

**Comment by minrk** [comment]
Is this a separate issue? It seems to be a summary of the two already existing issues and there are no additional actions to take or separate conversation to have. Do you want to close the other two and merge the discussion here?

**Comment by minrk** [comment]
I think your proposal is solid, and we have a good path forward on the issues you've linked, individually. Maybe here is a good place to try to get a high-level overview of the use cases we want to make sure work, and what their config looks like, so we have something that won't get auto-closed by PRs addressing individual issues. I think it's appropriate to start at a high level and say "I want these user login/creation patterns to work, and I think the config should look like this" ignoring (at first) how everything actually works. Then we can try to fill the gap between what we have and what we want.

For example:

- fully deferred configuration to an Authenticator's authentication mechanism (e.g. PAM, LDAP, default behavior)
- users managed via the API (e.g. most target uses of nativeauthenticator)
- always-config-specified users and groups (revoking membership revokes permission - `allow_existing_users`)
- documenting that allowed_users when combined with other allow mechanisms should be a _union_ instead of an intersection (in-progress implementation change in oauthenticator, can be part of the 'spec' in base Authenticator, though implementation is still up to subclasses). Maybe some API changes in the base class can make this easier to implement in a consistent way.
- pre-populating a user list while also allowing future logins

Further related questions, that might help (or might not):

- do we need to more explicitly separate authentication from authorization? We have historically conflated these two, but we do now have _granular_ authorization in role membership. What there isn't currently (for the most part) is a separation between an _authenticated_ user and membership in the `user` role, despite the fact that it's technically possible. There aren't easy ways to make it happen.

**Comment by manics** [comment]
There's an open PR adding some authorisation support (user/admin/none) for Azure: https://github.com/jupyterhub/oauthenticator/pull/446

So there's clearly demand for it. I think we should come up with a position regarding authorisation, even if it's that we can't support it, to provide clarity to developers.

**Comment by minrk** [comment]
We do already have support for logging in and being granted a variety of permission levels (JupyterHub supports it, authenticators must implement the mapping within authenticate and can return things like group membership). I don't yet see any demand for allowing users to complete authentication _at the jupyterhub level_ without granting at least `user`-level permission.
