### ISSUE TITLE
"Invalid client_id" error message when real problem is that oauth_redirect_uri is missing

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#4551]
### Bug description

When configuring JupyterHub to run an external service, I forgot to set `oauth_redirect_uri` in the JupyterHub service config. However, this resulted in an error message saying 'invalid client_id' for the end user, rather than 'invalid oauth_redirect_uri'. This was confusing and led us down a couple blind alleys before debugging.

#### Expected behaviour

Show an error message saying 'invalid oauth_redirect_uri'

#### Actual behaviour

A client error message saying 'invalid client_id'. No details in the JupyterHub logs.

### How to reproduce

1. Check out https://github.com/jupyterhub/jupyterhub/pull/4550 (or `main` if that PR is merged)
2. Go to `examples/external-oauth`
3. Follow instructions in the README to run the service. Note that this *works*, and you can access the external service.
4. In `examples/external-oauth/jupyterhub_config.py`, uncomment `oauth_redirect_uri` in the services config. Restart JupyterHub to load new config. In your browser, clear all cookies for `127.0.0.1:5555` by going to the 'Storage' tab under developer tools - the example oauth process doesn't have logout functionality.
5. Try accessing the the external service now.

You should get an error saying:

<img width="556" alt="image" src="https://github.com/jupyterhub/jupyterhub/assets/30430/188c0f77-0895-4b7c-a02a-8f93386fd70d">

**Comment by minrk** [comment]
By the time the request is made, the error from the oauth provider is correct, in that no oauth client with that id is registered.

The source of the issue is [here](https://github.com/jupyterhub/jupyterhub/blob/9f7fc24a926e3805df3bc0d54f490a016e988440/jupyterhub/app.py#L2628), where oauth clients are only created if oauth is [availalble](https://github.com/jupyterhub/jupyterhub/blob/9f7fc24a926e3805df3bc0d54f490a016e988440/jupyterhub/services/service.py#L346), which is to say that a URL is configured _and_ a redirect URI is defined.

So the problem is that an oauth_client_id is specified explicitly, but it's still deciding that oauth should not be available. That should probably raise an error on startup, or a warning at the very least.

**Comment by minrk** [comment]
#4555 makes this config fatal and logs each Service creation including whether oauth is enabled for the service.
