### ISSUE TITLE
jupyterhub/jupyterhub image fails (`alembic.ini` missing) by default - is it a bug?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyterhub#4593]
I'm not sure what the intented behavior of the jupyterhub/jupyterhub image is, but currently it fails to startup by default without additional mounted configuration files etc via a `docker run docker.io/jupyterhub/jupyterhub:main` command.

```
docker run docker.io/jupyterhub/jupyterhub:main

[I 2023-10-02 10:16:39.360 JupyterHub app:3076] Running JupyterHub version 5.0.0.dev
[I 2023-10-02 10:16:39.360 JupyterHub app:3106] Using Authenticator: jupyterhub.auth.PAMAuthenticator-5.0.0.dev
[I 2023-10-02 10:16:39.361 JupyterHub app:3106] Using Spawner: jupyterhub.spawner.LocalProcessSpawner-5.0.0.dev
[I 2023-10-02 10:16:39.361 JupyterHub app:3106] Using Proxy: jupyterhub.proxy.ConfigurableHTTPProxy-5.0.0.dev
[I 2023-10-02 10:16:39.384 JupyterHub app:1768] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[E 2023-10-02 10:16:39.425 JupyterHub app:3639]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/app.py", line 3636, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/app.py", line 3118, in initialize
        self.init_db()
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/app.py", line 1897, in init_db
        self.session_factory = orm.new_session_factory(
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/orm.py", line 1161, in new_session_factory
        check_db_revision(engine)
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/orm.py", line 1052, in check_db_revision
        with _temp_alembic_ini(engine_url) as ini:
      File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
        return next(self.gen)
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/dbutil.py", line 71, in _temp_alembic_ini
        write_alembic_ini(alembic_ini, db_url)
      File "/usr/local/lib/python3.10/dist-packages/jupyterhub/dbutil.py", line 34, in write_alembic_ini
        with open(ALEMBIC_INI_TEMPLATE_PATH) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/jupyterhub/alembic.ini'
```

**Comment by manics** [comment]
It's a bug- there's an interaction between the Python build system, Docker build, and the omission of the `.git` directory:
https://github.com/jupyterhub/jupyterhub/blob/29e954c407c017c045fc534410ffcd1ec6318727/.dockerignore#L8

```
python -mvenv venv
. venv/bin/activate
git clone https://github.com/jupyterhub/jupyterhub
cd jupyterhub
pip install .
cat /x/venv/lib/python3.11/site-packages/jupyterhub/alembic.ini
...
```
Without `.git`:
```
git clean -dxf
mv .git .git-hide
pip install .
cat /x/venv/lib/python3.11/site-packages/jupyterhub/alembic.ini

cat: /x/venv/lib/python3.11/site-packages/jupyterhub/alembic.ini: No such file or directory
```

**Comment by sgaist** [comment]
To the best of my knowledge, that file not being code, it should be part of the `data_files` entry in `setup.py`

Changing `setup.py` like so:

```
def main():
    setup(
        cmdclass=cmdclass,
        data_files=["jupyterhub/alembic.ini"] + get_data_files(),
    )
```

makes the installation process include `alembic.ini` and the Docker image working as expected.

If the solution is satisfactory, I am happy to do a PR.

**Comment by manics** [comment]
It would be good to understand the root cause since it's specific to the Docker build, so we can avoid it happening with other files.
We use https://github.com/jupyterhub/jupyterhub/blob/main/ci/check_installed_data.py to check the content of the wheel, maybe we should run that in the built Docker image too?

**Comment by sgaist** [comment]
From a hunch I removed the unused `setuptools-scm` from the `[build-system]` `requires` entry and the installation fails as expect with and without a .git folder in the project directory. I did the installation on my host machine first to confirm and then built the Docker image.

So it seems that this plugin does something unexpected with `.ini` files.

**Comment by minrk** [comment]
setuptools-scm is _not_  unused, it is the package responsible for collecting files for distributions. I think the fix should be to remove `.git` from .dockerignore.

**Comment by minrk** [comment]
btw, we have [ci/check_installed_data.py](https://github.com/jupyterhub/jupyterhub/blob/efe98ba7a3b0c7d6763dce87b3c5a7ddf85a00c7/ci/check_installed_data.py) to verify these things. Probably worth running that to validate the docker installs as well, which I think would have caught this.

**Comment by sgaist** [comment]
@minrk my bad, I misunderstood the plugin's documentation. Thanks for pointing that out.

Since it's a multi-stage Docker build, sending the `.git` folder in the context can be a solution but can become costly as time goes by and the history gets bigger. It's already a 33MB folder on a fresh clone.

As for the check, do you mean run in as part of the `jupyterhub-builder` stage creation ?

**Comment by minrk** [comment]
As you said, since it's a multi-stage build there's ~no cost to including .git in the build stage, since it doesn't end up in the actual image. On CI, a shallow clone tends to be used, so it would be even smaller.

> As for the check, do you mean run in as part of the jupyterhub-builder stage creation ?

Yeah, that's a good idea. Copy [these steps](https://github.com/jupyterhub/jupyterhub/blob/efe98ba7a3b0c7d6763dce87b3c5a7ddf85a00c7/.github/workflows/release.yml#L63) to the build stage, so it validates the wheels before proceeding to the real image.

Another way is a check after build and before test via `docker run`, but I don't think that works as well with the single `build-push-action`.

**Comment by sgaist** [comment]
It's even trickier than what we thought ! The wheel installation is incomplete not only because `alembic.ini` is missing but also `v1.yml` and `page.html` that are located somewhere under the `jupyterhub` code folder.

`setuptools-scm` works for the sdist build part but not for the wheel.

For the sake of testing I added the missing files to the `data_files` list and now the Docker image building ends up with all the checked files.
