### ISSUE TITLE
User should not view Token and Admin tabs if not admin anymore

### ISSUE THREAD

**Issue by luanabeckerdaluz** [jupyterhub/jupyterhub#4827]
### Bug description

Once an user has been set as admin in the c.Authenticator.admin_users list of helm chart, it keeps admin even the chart is deployed again without its name in c.Authenticator.admin_users. It means that if an user is not admin anymore, JupyterHub local database is not updated and the user remains with admin permission. The only way to remove admin role for an user that is not admin anymore is to enter in Admin tab, click in Edit button and disable admin checkbox.

### How to reproduce

1. Set c.Authenticator.admin_users = {"user1"} in the helm chart;
2. Deploy JupyterHub in a kubernetes cluster;
3. Log in with **user1**, you should view _Admin_ and _Token_ tabs; 
4. Update helm chart to c.Authenticator.admin_users = {"user2"} and deploy helm chart;
5. Log in with **user1**, you continue to view _Admin_ and _Token_ tabs; 

### Personal set up

Kubernetes cluster built using k3d
Helm chart 3.3.7
oauthenticator==16.3.0
jupyterhub==4.1.5

**Comment by minrk** [comment]
You're right, `admin_users` (like `allowed_users`) is a way to _add_ admins, it is not an authoritative list because other actions, such as Authenticators and UI, can modify admin status which shouldn't be lost upon reload of config.

You can, however, specify membership of the admin _role_, which is considered authoritative and complete, which means it will revoke admin permissions from users not explicitly assigned (this was added as a backward-compatible solution to the problem you are currently seeing):

```python
c.JupyterHub.load_roles = [
    {
        "name": "admin",
        "users": ["admin1", ...],
    }
]
```

which will always set the complete admin list, overriding any past sources of information.

But generally better is to not use admins at all, and create roles with only the required permissions. Role assignments are authoritative from config, unlike the earlier `admin_users` config.

**Comment by luanabeckerdaluz** [comment]
Dear @minrk,

Thank you very much for clarifying this information and for giving the instructions.

Cheers!
Luana
