### ISSUE TITLE
c.Authenticator.username_map doesn't work with local users

### ISSUE THREAD

**Issue by vbraun** [jupyterhub/jupyterhub#485]
- Jupyterhub is running under local (unix) user "alice"
- Log in as "alice" works
- I want to map Jupyter hub user "bob" to log in as unix user "alice"

I tried all three of 

```
c.Authenticator.username_map = { 'bob': 'alice'}
c.Authenticator.username_map = { 'alice': 'bob'}
c.Authenticator.username_map = { 'alice': 'bob', 'bob: 'alice'}
```

but neither works. The logs contain the suspicious line:

```
[W 2016-03-19 20:24:08.092 JupyterHub auth:372] PAM Authentication failed (@::x.x.x.x): [PAM Error 7] Authentication failure
[D 2016-03-19 20:24:08.093 JupyterHub login:81] Failed login for None
```

Obviously `None` has no unix account.

**Comment by betatim** [comment]
`username_map` is used only after authenticating the user. I think the idea behind it is to turn the name used by the auth service (say an email address) into a username for jupyterhub.

Take a look at [`Authenticator.get_authenticated_user()`](https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/auth.py#L113-L138) which sets out the order in which things happen. Which means (I think) you'd have to write your own authenticator that inherits from `PAMAuth` and knows to translate usernames before doing the authentication.

The fact that `authenticate()` returns `None` for your login attempt is interesting. As in it should really show you the username not `None` as that isn't particularly useful.

**Comment by minrk** [comment]
Yeah, username_map is meant to perform normalization on logins after logging in. The point of it is for email-address-type logins, or other logins where the username of the login service is not the username you want JupyterHub to use in URLs, etc. What you enter into the form should be what the authentication service expects (`alice`), and then the URL will be transformed to `bob` if you have:

```python
c.Authenticator.username_map = {'alice': 'bob'}
```

There is currently no mechanism in place other than a custom Authenticator to transform the name typed into the form prior to passing it to the authentication service. We could consider a reverse lookup in `username_map`, so that if you type *either* `alice` or `bob`, you authenticate as `alice`, but I'm not sure about that.

**Comment by consideRatio** [comment]
I think this is an answered question, and the issue is stale - so I'm closing it.
