### ISSUE TITLE
Configuring JupyterHub Notebooks for streamlined user interactions 

### ISSUE THREAD

**Issue by cenveoanalyst** [jupyterhub/jupyterhub#565]
Hello, I've just rolled out initially a deployment of Jupyter Notebooks hosted on JupyterHub for reporting in our small team in our organization. I've used a cell magic to toggle visibility of the input code on cell run; and have instructed my user base to run all the cells upon report load. Then I've instructed my users to clear out all the cells (to aid in visibility of Bokeh plots, not specifically Jupyter related), and then close and halt to shutdown the notebook server. I know Jupyter isn't built specifically as a business intelligence platform but since BI is Data Science I feel it's suited to be used that way. Is there any way I can configure the notebook (or JupyterHub since this may be better configured there) so that a trusted notebook may be executed automatically upon open, and I can add a button to clear out the output and close the notebook server for that user? I love the complete canvas nature of Jupyter, but I've been getting pushback on usability when the user has to click several different buttons to use a notebook essentially as a report/webpage. Appreciate any tips or pointers!

**Comment by minrk** [comment]
Yes, you can do this with an nbextension. The extension would watch for the `notebook_loaded.Notebook` event, and check if it's trusted. If so, run the notebook.

However, while this is technically possible, if you did it that way, such that *all* notebooks are executed on load, that could get quite annoying because it would be impossible to open a notebook without executing the whole thing - refreshing the page would re-execute everything, for instance.

You may be interested in the [Jupyter dashboards](https://github.com/jupyter-incubator/dashboards) project, which is aimed more at the reporting task. [Here is an example](http://jupyter.cloudet.xyz/files/2015-notebook-ux-survey/analysis/deployed_dashboard/index.html).

cc @parente for more dashboard info.

**Comment by cenveoanalyst** [comment]
Minrk, 

Thank you very much for your reply. I managed yesterday to figure out how to write an extension to do what I need and am working to deploy it to JupyterHub today. Yet, in looking at the Jupyter Dashboards project, that is exactly where I need to take the tool in the future. I played around with the example and it fits my vision perfectly. I'll be working on implementing that later. Thanks!

**Comment by parente** [comment]
@cenveoanalyst Feel free to reach out via the google group or issues against the dashboards projects. Be sure to check out this blog post which talks about how the notebook server(s), dashboard extension, and dashboard server all fit together to turn notebooks into standalone web apps.

http://blog.ibmjstart.net/2016/04/26/2822/

We're actively migrating the recipes for bringing up all the components for people to play to https://github.com/jupyter-incubator/dashboards_setup.

**Comment by willingc** [comment]
I'm going to close this issue @cenveoanalyst since it looks as if @minrk and @parente have shared some pointers as well as information about dashboards. Thanks everyone!
