### ISSUE TITLE
Will python2.6 able to add in Jupyterhub Notebooks?

### ISSUE THREAD

**Issue by Balajideivam** [jupyterhub/jupyterhub#573]
May I know whether is it possible to add python 2.6 notebook in jupyterhub?

**Comment by minrk** [comment]
It's a bit tricky, because the last version of IPython to support Python 2.6 was 1.0, before the kernelspec machinery was added to make it manageable to deal with different kernels. It should be possible to hand-write a kernelspec for an IPython 1.0 env that will work, though. If you copy the kernelspec for a current version of IPython, you can change the `argv` in kernel.json to:

    ["/path/to/ipython-1.0-env/bin/ipython", "kernel", "-f", "{connection_file}"]

it might work.
