### ISSUE TITLE
python3 now required for juptyerhub-singleuser

### ISSUE THREAD

**Issue by robnagler** [jupyterhub/jupyterhub#616]
267994b191fc72fbbaec00b1ad41627e6539fdae added the requirement that scripts/juptyerhub-singleuser must be installed with python3, because it now depends on jupyterhub. For now, I'm using previous commit, but that's incompatible with jupyter/notebook@master so I'm going back a few commits there. You may want to label a couple of branches to help people like me out. :)

Perhaps the code required for jupyterhub-singleuser could be moved to another package that is py2/3 compatible?

Most of our particle accelerator codes do not run with python3 and probably won't be compatible for some time. That creates a problem for us, because we don't really want to show the alternative to run a python3 notebook in the drop down in Jupyter. This would be confusing. Perhaps we can fake a menu entry or something so that it says "beamsim", which would let people know which notebook version to use.

Also, we are not using Anaconda and instead using pyenv. I haven't tried it so we can't really fake using pyenv. Note sure the python2 install method for kernels would work with that without a wrapper. Need to try that.

**Comment by willingc** [comment]
Thanks @robnagler for bringing up this use case. I'm going to defer to @minrk on what is possible to help your situation.

**Comment by minrk** [comment]
The main reason that single-user requires Python 3 is that the authentication code (HubAuth) is now part of JupyterHub, and can be used to authenticate any service with JupyterHub (e.g. nbgrader), not just the single-user server. I'm reticent to make it a separate package because it won't be independent - there would be only one version for both, released in lock-step, and it makes coordinated changes in both repos really difficult to work with. I will investigate multiple packages in a single repo, though, and see if that can work. If that is manageable, it would probably be:

- jupyterhub (the hub)
- jupyterhub-auth (the HubAuth stuff)
- jupyterhub-singleuser (depends on jupyterhub-auth)


> we don't really want to show the alternative to run a python3 notebook in the drop down in Jupyter.

That's solvable with the configuration (in /etc/jupyter/jupyter_notebook_config.py):

```python
c.KernelSpecManager.whitelist = {'python2'}
```
 to limit the kernel list to python2. Or you can specify:

```python
c.KernelSpecManager.ensure_native_kernel = False
```

to prevent the python3 kernel from being listed even when the python3 kernelspec has not been installed.

> we are not using Anaconda and instead using pyenv.

A Python 2 kernel with pyenv should work just fine. There's no requirement that Anaconda is used anywhere. I haven't used pyenv, but several of my kernels are installed with venv.

**Comment by willingc** [comment]
@robnagler I'm going to close this and tag it as reference. If you have additional questions on this, please do reopen. Thanks.
