### ISSUE TITLE
Config option `log_file` not recognized

### ISSUE THREAD

**Issue by davis68** [jupyterhub/jupyterhub#619]
Oddly, JupyterHub now raises the warning for me:

    [W 2016-06-23 15:56:46.334 JupyterHub configurable:169] Config option `log_file` not recognized by `JupyterHub`.  Did you mean one of: `config_file, extra_log_file, logo_file`?

Has this been deprecated or is something unseemly going on?  Version 0.6.1

**Comment by willingc** [comment]
@davis68 Thanks for the question.

@minrk Is this due to a IPython traitlets change or something in JupyterHub?

**Comment by minrk** [comment]
I don't believe log_file has been an option in the past. There was a recent improvement in traitlets.config where you get a warning if invalid config is going to be ignored, which it would do silently before, so I'm guessing this never had any effect, and now it's telling you why.

The best way to send log to a file is by redirecting output of the process, because that will capture subprocess output, which logging configuration (extra_log_file) will not.

**Comment by davis68** [comment]
Interesting.  True that I've not had to use it in the past.  It's referenced in [getting-started.md](https://github.com/jupyterhub/jupyterhub/blob/master/docs/source/getting-started.md) and may be generated in the default `jupyterhub_config.py` (would double-check that).  I'll just drop it in mine then.

**Comment by minrk** [comment]
@davis68 thanks for pointing that out, I've updated the doc in #622 to something that actually does what it claims to.

**Comment by willingc** [comment]
@davis68 Thanks again 👍  I've merged @minrk's doc update.
