### ISSUE TITLE
Python kernel not represented in external environment 

### ISSUE THREAD

**Issue by kwotuveang3k4bk** [jupyterhub/jupyterhub#630]
I have to bit, it is a quite complex software and maybe not the best way of doing to, but maybe you can help me. 

I run the following: 
```
import os
import sys
print(sys.version)
print(sys.path)
f = open("testing.py","w")
f.write('import sys\n') 
f.write('f = open("sys.log","w")\n')
f.write('a = [f.write(l) for l in sys.path]\n')
f.write('f.write(sys.version)\n')
f.write('f.close()\n')
f.write('print(sys.version)\n')
f.write('print(sys.path)\n') 
f.close()
os.system("python testing.py")
l = open("sys.log", "r")
for line in l:
    print line  
l.close()
```

In short I print the environment variables once directly and once via os.system(python). Obviously the first environment has the preferences of my kernel, the second has the environment jupyterhub is running in. Now I was wondering if there is any way similar to: 
`source /etc/profile`
to restore the user environment, when running external scripts ? I am not so familiar with Popen, so I though you might have an idea.

**Comment by minrk** [comment]
with `Popen(command, shell=True)` a shell environment is created for running the process.

**Comment by minrk** [comment]
`os.system("python")` will find the first `python` on $PATH (`shutil.which("python")` will generally show you what this will be). Jupyter does not generally touch your PATH, so that's up to you. This means that `sys.executable` and `shutil.which("python3")` are not guaranteed or required to be the same. This can happen e.g. if a kernel is launched via an _absolute_ path (`/path/to/prefix/bin/python3 -m ipykernel`) that is not required to be  on your $PATH at all.

In general, if you want to run a subprocess with the current Python, you should use `sys.executable`, not `python`. This is true of all Python programs, not just in the context of IPython or Jupyter.
