### ISSUE TITLE
automatic logout not working as desired

### ISSUE THREAD

**Issue by simtos** [jupyterhub/jupyterhub#673]
Hi,

I installed jupyterhub and set logout parameter as a 1minute. If i login and dont do any activity for a minute and then click on Control Panel then I get logout. But when I click on existing .ipynb file or New button etc it does not get automatically logout and also am able to save my notebook.
Is automatic logout only works with Control Panel??
Please find attached the config file.
[jupyterhub.zip](https://github.com/jupyterhub/jupyterhub/files/393414/jupyterhub.zip)

**Comment by minrk** [comment]
The single-user server caches the Hub's cookie responses for five minutes by default, so that would be a lower limit for the cookie invalidation to take place. Do you see cookies being invalidated after more like 10 minutes?

**Comment by simtos** [comment]
Hi, Thank you for the details. I set timeout parameter to 6min but it didnt work then I set to 12mins then also it didnt work.. 
I tried setting this parameter in the jupyterhub service command and also in jupyterhub config file with value as 12mins.. It is working now for more than 10mins.
PFB the jupyterhub service command as below:
===========================================
[Unit]
Description=Jupyterhub
After=network-online.target

[Service]
User=jupyterhubusr
ExecStart=/usr/bin/jupyterhub --config /etc/jupyterhub/jupyterhub.py --JupyterHub.spawner_class=sudospawner.SudoSpawner --JupyterHub.cookie_max_age_days=0.00828 --no-ssl --log-level=DEBUG --PAMAuthenticator.open_sessions=False --JupyterHub.extra_log_file='/var/log/jupyterhub.log'
WorkingDirectory=/etc/jupyterhub

[Install]
WantedBy=multi-user.target
=============================================
Few questions still exist
1. Why it doesnt work for timeout less than 10mins
2. Why we need to set this parameter in jupyterhub service command and also in jupyterhub config
3. When I set parameter like 1min etc why it working when I click on Control Panel but doesnt work if I open new notebook etc
As of now issue resolved. I will set timeout parameter more than 10mins. Thanks.

**Comment by minrk** [comment]
Answers:

> Why doesn't it work for timeout less than 10mins

I'm not sure how you are testing, but since the SU server caches the most recent reply for five minutes, you should test that it logs you out after your timeout plus five minutes. So if you have set the timeout to 6 minutes, it could take 11 minutes before the SU server starts rejecting requests from a given cookie, etc.

> Why we need to set this parameter in jupyterhub service command and also in jupyterhub config

You don't. Setting it in either place is sufficient, but config is preferable.

> When I set parameter like 1min etc why it working when I click on Control Panel but doesnt work if I open new notebook etc

The Hub server sets and checks all cookies, so expiry takes effect immediately for requests made directly to the Hub (anything on `/hub/`). The single-user server has to ask the Hub if a cookie is valid, which is expensive. For this reason, it caches responses for five minutes. This is what leads to the delay on single-user server requests (`/user/name/`).

**Comment by simtos** [comment]
Thank you Min RK.

**Comment by willingc** [comment]
@simtos It looks as if @minrk helped you with this issue. Is there anything further that you need from us or would you like to close the issue? Thanks!
