### ISSUE TITLE
`KeyError("User %k does not not exist.")` when Unix user has been deleted.

### ISSUE THREAD

**Issue by ksze** [jupyterhub/jupyterhub#687]
JupyterHub version: 0.6.1
OS: Debian Jessie

We had followed this wiki to setup JupyterHub to run as a service on Debian Jessie, using the init.d script instead of a systemd service unit file: https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service

However, we are running into the exact same problem as this guy: https://serverfault.com/questions/794938/jupyterhub-error-on-start-keyerror-user-k-does-not-exist

His solution is to delete the jupyter.sqlite file.

In our case, we allow Unix account users to log into JupyterHub. But one of the users has left the company, so we removed his Unix account, and his username is showing up in the KeyError.

Oddly enough, this problem only happens if we try to start JupyterHub as a service. If we run JupyterHub at the terminal, the KeyError doesn't show up, and users can actually use JupyterHub.

Is it safe to just delete the jupyterhub.sqlite file while JupyterHub is not running?

**Comment by willingc** [comment]
@ksze Thanks for the issue report.

Pinging @minrk.

**Comment by minrk** [comment]
We should add a check in the startup for the removed users.

Deleting the jupyter.sqlite is usually fine, as long as the Hub and all servers are stopped, especially if you are just using the system to manage users. If you were managing Hub users via the admin interface, any changes made there not reflected in config files would be lost.

You can be less drastic by deleting just the problematic user from the database:

```python
from jupyterhub import orm
db = orm.new_session_factory('sqlite:///jupyterhub.sqlite')()
u = orm.User.find(db, name='thename')
db.delete(u)
db.commit()
```

The other fix would be to delete users via the JupyterHub admin interface prior to deleting the system user.

#689 should demote the error to a logged exception, rather than a fatal one, so that you can at least start the Hub and then delete the user from the admin interface after the fact, rather than not being able to start the Hub at all.
