### ISSUE TITLE
Possible race condition in Spawner stop?

### ISSUE THREAD

**Issue by stefanoborini** [jupyterhub/jupyterhub#721]
I am doing an overall audit of our own code, which is built using jupyterhub, and that is bringing me into the current jupyterhub spawners. I observed what I believe is a potential for race condition, but I am not 100% sure, hence this request for comments. I doubt it's critical, but it might produce unexpected rare behavior.

The method `LocalProcessSpawner.stop()` is abundant in yields. During the whole execution of that coroutine, anything can happen, driven by user interaction, including calling back into `start()`. This call will change a few things, including the pid. When `stop()` resumes, the pid is now different and will send signals to the newly spawned process, forgetting about the pid of the old one.

This `yield self.poll()` [line](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py#L547) and equivalent a few lines later are the source of potential problems. Note that, while `poll` invokes `_signal` which is not a generator (hence it won't pass through the `Runner`, see `tornado.gen._make_coroutine_wrapper`) `self.poll` itself is, hence it will be invoked through a `Runner` and therefore it goes in the event queue for later dispatch, meaning that `self.poll()` does indeed leave a race condition window during which start() can be called, and replace the pid.

Sorry if this is not the case.

**Comment by minrk** [comment]
`start` should not be allowed to be called while stop is pending, due to the `.stop_pending` flag, which is meant to protect against exactly this sort of race condition. If it is possible to `.start()` during a `.stop()`, that would be a bug somewhere where `.stop_pending` is not being checked. Have you encountered a case where one or more of these races actually occur?

Similarly, a `start_pending` flag is set during a pending start call that should also be avoiding race conditions while start has not finished.

**Comment by stefanoborini** [comment]
@minrk Ah ok, so you prevent that at the level above, guaranteeing that the method is never called to begin with. 

I haven't encountered any problem. I was just checking our own spawners and I found the code suspicious, but yes, I forgot you actually check for the flag on the user object.

**Comment by minrk** [comment]
Yup, that should be set. There's always a chance that some checks are missed, but if you haven't found one, I'm inclined to close here as I *believe* these are protected against.
