### ISSUE TITLE
Deprecation of old spawners doesn't have a fallback

### ISSUE THREAD

**Issue by stefanoborini** [jupyterhub/jupyterhub#726]
The current code in `user.py` says:

    233                 # prior to 0.7, spawners had to store this info in user.server themselves.
    234                 # Handle < 0.7 behavior with a warning, assuming info was stored in db by the Spawner.
    235                 self.log.warning("DEPRECATION: Spawner.start should return (ip, port) in JupyterHub >= 0.7")

It's probably better to raise an exception instead
As it is, it gives the impression that the code can keep working as is, but in practice, the server ip and port are not set and the wait_up times out.

**Comment by minrk** [comment]
The deprecation should be correct because the 0.6 mechanism should indeed still work if ip, port are not returned. This is tested and confirmed to work in a few Spawners. What Spawner are you using where you see this failing?

**Comment by stefanoborini** [comment]
@minrk we built our own spawners, so I was surprised when nothing worked anymore because our start didn't return the pair ;)

**Comment by minrk** [comment]
Can you share them? This would be a bug if the old way doesn't work anymore, because I tested it with Spawners that store the ip/port the old way and they do work with 0.7, so I'm not sure what yours are doing differently.

**Comment by stefanoborini** [comment]
@minrk  I had to change this line https://github.com/simphony/simphony-remote/blob/master/remoteappmanager/spawners.py#L179

**Comment by stefanoborini** [comment]
@minrk it is possible we are misusing the Local spawner...

**Comment by minrk** [comment]
@stefanoborini aha! I see what happened. LocalProcessSpawner itself updated to the new mechanism, removing the old way because it knows it's no longer necessary. But *subclasses* of LocalProcessSpawner could implicitly rely on the base class's setting of the values in the db, which was removed.

If your subclass passed through the return value from `super().start()`, then it would work correctly in all JupyterHub versions, but since it was a safe assumption that the return value could be discarded before, there's no reason to assume that you would pass it through.

I'll add the old way back so that subclasses of LocalProcessSpawner continue to work, and trigger the deprecation warning.

**Comment by minrk** [comment]
#734 should keep the 0.6 assumption working with a deprecation message.
