### ISSUE TITLE
root can't login on debian BUT other users can

### ISSUE THREAD

**Issue by bourguig** [jupyterhub/jupyterhub#745]
Hi everybody !
I discovered that **root** can't login to jupyterHub as any other users on a debian system.
Is this made by design or a misconfiguration that I made somewhere ?!
Thanks for some pointing !

**Comment by minrk** [comment]
Is root in your user list? What are your user list and admin list? What do you see in the JupyterHub logs during startup?

**Comment by bourguig** [comment]
Thanks for replying minrk,
i thought that jupyterhub is loading its user list automatically from the system (using PAM ...). I can see it's the case when I add a new user to the system and launch jupyterhub without specifying any configuration file using the -f option, even being outside the jupyterhub_config.py directory. The Hic is that there would be No Admin Interface Available, and Root Can't Sign in.
Otherwise,
Root isn't in the admin list, but I'm not aware of any user list to set somewhere in the configuration. if i had to, could you please tell me where/how to set it ?
Thank you very much ;)

**Comment by minrk** [comment]
`c.Authenticator.whitelist` is the set of users allowed to use the Hub. `c.Authenticator.admin_users` is the set of users allowed to *administer* the Hub. If you want root to be able to admin, it needs to be in admin_users.

You can use `c.PAMAuthenticator.group_whitelist` to use system groups to determine who should have access, rather than the user whitelist.

**Comment by bourguig** [comment]
Thank you very much minrk
Could you please point me about the default behaviour of the Hub when none of the lists you mentioned above is set ?
