### ISSUE TITLE
Kernel not found

### ISSUE THREAD

**Issue by spalkovits** [jupyterhub/jupyterhub#746]
Hello,

I have to prepare a Jupyterhub for a lecture on the road on my MacBook within Docker. Everything works more or less but I get one issue that the right kernel cannot be found:

<img width="715" alt="Kernel not found" src="https://cloud.githubusercontent.com/assets/15083970/18529331/e9003e3a-7acc-11e6-8157-ed9211abb6d7.png">

I am not sure if this is an issue of the Jupyterhub or the notebook I wrote?

**Comment by minrk** [comment]
This is an issue with the notebook that you wrote, caused by a bug in Anaconda's nb_conda_kernels that has since been fixed. Everything is behaving as intended, in that you don't have an exact match for the kernel used to create the notebook, so you are getting a dialog to pick from a list of available kernels. The notebook will work after this. The issue is that Anaconda's default Python kernel name is different from any other environment, so you will get this "kernel not found" dialog any time the notebook is opened in an environment that doesn't have this package.

I recommend upgrading the nb_conda_kernels package:

    conda upgrade nb_conda_kernels

if you are still using it. You can also remove it to get back the default behavior:

    conda remove nb_conda_kernels

If you open the notebook and select the 'Python 2' or 'Python 3' kernel and save, you should be set and not see this dialog again.

**Comment by spalkovits** [comment]
OK, this helps me quite a bit. Where do I do the suggested kernel upgrading? On my local environment or on the Jupyterhub?

Thank you!

**Comment by minrk** [comment]
From the error message, it's the environment where the notebook was written that has outdated nb_conda_kernels.

**Comment by spalkovits** [comment]
It works like you intended. Thank you!
