### ISSUE TITLE
Start server automatically after login (custom authenticator)

### ISSUE THREAD

**Issue by katsar0v** [jupyterhub/jupyterhub#759]
I am using a custom-written oauthenticator with DockerSpawner and after login I always need to start the server. Is there a way to start it automatically after login?

**Comment by minrk** [comment]
There isn't an option for always guaranteeing that spawning a server is triggered at login at the moment, but it could be added.

**Comment by katsar0v** [comment]
@minrk How can I implement this locally?

When loging in without a custom authenticator, servers usually start automatically, when using an Authenticator Class, this does not happen anymore.

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:

**Comment by glehmann** [comment]
I've very interested in this feature. Can someone point where the decision to start the server or not is done? I'll be happy to submit a pull request when I'll get it working.

**Comment by yzq89** [comment]
Hi, we're also very interested in this, was it ever resolved / is there any workaround?

**Comment by consideRatio** [comment]
It is available, i think auto_login or similar is what you want. Look in the jupyterhub documentation for something like that.

**Comment by yzq89** [comment]
@consideRatio, thanks very much for the response! I should have been clearer, the issue we were facing was that users were getting presented with the hub home page with the "Start Server" button, after authenticating with our custom JWT authenticator, like this:
![image](https://user-images.githubusercontent.com/28737246/71813253-0b76e380-3071-11ea-8379-b2ba9ed27c1b.png)

Having done a bit more digging, I think it's due to our authenticator redirecting to `/hub/home` as opposed to `/hub/`, post-authentication.
