### ISSUE TITLE
running notebooks can be seen by different users from running tab.

### ISSUE THREAD

**Issue by jai11** [jupyterhub/jupyterhub#790]
if you click on running tab,

notebooks and terminal can been seen  not launched by the user but running on instnace.

**Comment by willingc** [comment]
Hi @jai11, I'll need some additional information to understand your issue or question. First, is this the running tab that you mean?

<img width="1221" alt="screen shot 2016-09-30 at 14 26 12" src="https://cloud.githubusercontent.com/assets/2680980/19007482/1952966a-871a-11e6-9ece-319cd2a1b9ed.png">

Next, what is your jupyterhub deployment configuration? OS? Docker or not?

Also, what authenticator and spawner are you using? Are you an admin as well as a user?

Thanks!

**Comment by jai11** [comment]
@willingc  Yes thats the running tab I meant.

OS level, using ldap authenticator . spawner is customized one.

**Comment by minrk** [comment]
Can you show a screenshot? These listings are only populated from in-memory objects that have been created when the notebook server spawns things, so I'm not sure how they would get extra items from other users.

**Comment by jai11** [comment]
@minrk , Here I am using single static user for spawning the single server. and jupyter login users are ldap ones.   so might that be an issue to show all running ones.

**Comment by minrk** [comment]
Can you post some details about your Spawner? It sounds a bit like your Spawner might be re-using a single server for all users, which would have this effect.

**Comment by jai11** [comment]
I am using https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/spawner.py

functions def set_user_setuid(username,path) and def _try_setcwd(path):  only.

calling set_user_setuid(username)  function from return call of make_preexec_fn of spawner.

**Comment by jai11** [comment]
just in above username is static .. means every time I am running single server with same  user and which is a OS user.

**Comment by minrk** [comment]
If it's a different notebook server process, then you won't see any terminals or notebooks from other server processes.

**Comment by jai11** [comment]
But I can see ... Any solution for this.

**Comment by jai11** [comment]
In you way .. can you please describe a simple spawner which will run notebook , terminal as static user say test user.

**Comment by minrk** [comment]
@jai11 can you show a screenshot of this? What's the URL of the server when you see this, and what's the URL of the server that started the processes that you see but shouldn't? When you click on a termian

I can't think of a way for it to be possible for the running tab to list any processes not started by that server, because it doesn't look at any processes or files to produce the list, only an in-memory record of subprocesses it has launched. If you are seeing this list having processes that you didn't start, that more likely means that multiple users are actually sharing a notebook server, rather than populating the list from other servers.

Can you share your custom Spawner implementation?

Here is a local spawner that disables the user-switching:

```python
from jupyterhub.spawner import LocalProcessSpawner

class NoSwitchSpawner(LocalProcessSpawner):
    
    def make_preexec_fn(self, name):
        return lambda : None
    
    def user_env(self, env):
        return env
```

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue at the [jupyter/help repo](https://github.com/jupyter/help) or reopen this issue. Thanks! :sunflower:
