### ISSUE TITLE
Password not passed on to PAM when opening session

### ISSUE THREAD

**Issue by Fleckenteufel** [jupyterhub/jupyterhub#810]
I try to open a PAM session on login at jupyterhub. I want to use this for automatically mounting a user folder with the user credentials entered on login. The PAM session gets successfully opened, as I see in the logs, but pam_mount states that it doesn't have the password (it tries to retrieve it interactively). Consequently the mounting fails. Here an excerpt of the `auth.log`:

```
Oct 12 18:25:49 local-server python3.5: (pam_mount.c:365): pam_mount 2.14: entering auth stage
Oct 12 18:25:49 local-server python3.5: (pam_mount.c:133): clean system authtok=0x22a54a0 (0)
Oct 12 18:25:49 local-server python3.5: pam_unix(login:session): session opened for user user by (uid=0)
Oct 12 18:25:49 local-server python3.5: (pam_mount.c:568): pam_mount 2.14: entering session stage
Oct 12 18:25:49 local-server python3.5: (pam_mount.c:477): warning: could not obtain password interactively either
Oct 12 18:25:49 local-server python3.5: (mount.c:267): Mount info: globalconf, user=user <volume fstype="cifs" server="remote-server" path="home" mountpoint="/home/user/remote-server" cipher="(null)" fskeypath="(null)" fskeycipher="(null)" fskeyhash="(null)" options="domain=." /> fstab=0 ssh=0
Oct 12 18:25:49 local-server python3.5: (mount.c:664): Password will be sent to helper as-is.
Oct 12 18:25:49 local-server python3.5: command: 'mount' '-t' 'cifs' '//remote-server/home' '/home/user/remote-server' '-o' 'username=user,uid=1048,gid=1000,domain=.'
Oct 12 18:25:50 local-server python3.5: (mount.c:72): Messages from underlying mount program:
Oct 12 18:25:50 local-server python3.5: (mount.c:76): mount error(13): Permission denied
Oct 12 18:25:50 local-server python3.5: (mount.c:76): Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
...
Oct 12 18:25:50 local-server python3.5: (pam_mount.c:522): mount of home failed
```

If I login via SSH, the password is correctly recognized and the remote directory gets mounted:

```
Oct 12 18:34:13 local-server sshd[25603]: (pam_mount.c:365): pam_mount 2.14: entering auth stage
Oct 12 18:34:13 local-server sshd[25603]: Accepted password for user from ... port ... ssh2
Oct 12 18:34:13 local-server sshd[25603]: pam_unix(sshd:session): session opened for user user by (uid=0)
Oct 12 18:34:13 local-server sshd[25603]: (pam_mount.c:568): pam_mount 2.14: entering session stage
Oct 12 18:34:13 local-server sshd[25603]: (mount.c:267): Mount info: globalconf, user=user <volume fstype="cifs" server="remote-server" path="home" mountpoint="/home/user/remote-server" cipher="(null)" fskeypath="(null)" fskeycipher="(null)" fskeyhash="(null)" options="domain=." /> fstab=0 ssh=0
Oct 12 18:34:13 local-server sshd[25603]: (mount.c:664): Password will be sent to helper as-is.
Oct 12 18:34:13 local-server sshd[25603]: command: 'mount' '-t' 'cifs' '//remote-server/home' '/home/user/remote-server' '-o' 'username=user,uid=1048,gid=1000,domain=.'
```

I suspect that the password is not passed on to PAM when calling the open_session command.

**Comment by willingc** [comment]
Hi @Fleckenteufel, Is this the same deployment as in #809?

**Comment by Fleckenteufel** [comment]
Yes. It is identically the same system.

**Comment by dsoares** [comment]
I have a running jupyterhub instance that also uses PAM and pam_mount to mount the user's home (also CIFS) on login. The user's home can only be mounted using the user's credentials.

I could not get it to work with `pamela` so i wrote `pampylho`. That's basically a fork of `pamela`, but opens a session before calling `pam_end()` in the `auth` phase. Then, i extended `PAMAuthentication` to use `pampylho` instead of `pamela`. 

You may give [it](https://github.com/dsoares/pampylho) a try.

**Comment by Fleckenteufel** [comment]
Thank you! This sounds good. I will give it a try and report, as soon as I find the time.

**Comment by Fleckenteufel** [comment]
I tried the authentication with pampylho. Therefore I just installed pampylho from git
`pip3.5 install git+https://github.com/dsoares/pampylho.git`
and replaced `import pamela` by `import pampylho as pamela` in `.../jupyterhub/auth.py`.

After restarting the server this works like a charm. Thanks @dsoares for sharing. I think it would be nice if these changes would be merged to pamela.

Btw. this does not resolve #809 for me.

**Comment by willingc** [comment]
@minrk I'm going to pass this along to you re: pamela. Thanks.

**Comment by bla123454321** [comment]
I am using pam_mount to connect to a cifs mount and it works very well when I use `pampylho` instead of `pamela`. The resources are mounted to "/home/$user/mnt".

Unfortunately, I still get a problem when multiple users (more than 1) want to connect to JupyterHub. The second user who wants to connect always gets a "invalid username or password" message. First one works (and it doesn't matter who is first) but the second user cannot connect.

When I check the home directory of the user who gets the error message I can see that still the mounting of the cifs drive worked - he just could not connect.

Any help any ideas?

**Comment by willingc** [comment]
@minrk Thoughts?

**Comment by willingc** [comment]
Closing this issue as it's been inactive for several months. Please feel free to request reopening this issue if the issue persists. Thanks! :sunflower:
