### ISSUE TITLE
Surprising behavior when no state is kept in spawner

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyterhub#819]
In https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/app.py#L1061, we assume that if a user's spawner has no saved state, the server doesn't exist. This isn't necessarily the case for all spawners - the kubernetes spawner right now doesn't actually need to store any state (since it can derive all the state it needs from configuration + username), and this leads to super confusing behavior. Restarting the Hub doesn't make the hub notice the still running servers, but since kubernetes can't have two pods with same name, spawning a new container fails.

I don't know the reason we assume empty state means no server - where is that true? It's not necessarily true everywhere, so we should either clearly document that or figure out a clearer way of accomplishing what that was trying to accomplish.

**Comment by minrk** [comment]
> I don't know the reason we assume empty state means no server - where is that true?

In every Spawner that exists so far, I think. I can remove this, but I'll need to be careful, because it puts existing Spawners into a new undefined condition. As it stands, `poll` will never be called if a Spawner has been through neither `load_state` nor `start`. Removing the assumption that Spawners have state means that `poll` must be able to be the first method called, before the first call to start. This would be a new API requirement of Spawners, and I'll have to investigate how careful I need to be when introducing that. On first glance, LocalProcessSpawner is fine and handles this okay already.
